### ISSUE TITLE
[FEATURE] More powerful color controls

### ISSUE THREAD

**Issue by VitoFe** [Mahmud0808/Iconify#100]
### Describe the feature

Using 6.1.0, I noticed that the saturation and lightness sliders do not really have the desired effect when put on 0% and 100%. What I mean is I would expect everything going black at background lightness 0%, and everything being saturated at 100% saturation.
I know this has been developed the way it is in order to preserve some kind of gradient, so I'd suggest adding a fourth slider for contrast, that would make it possible to flatten the gradient or to emphasize it more, and make transitions more or less accentuated.

### Why would it be useful to add?

More control over the color scale, since it's not configurable for each color step individually.

### Example(s)

Just another slider in the exact same UI

**Comment by Mahmud0808** [comment]
You are right, it is not actually 0% or 100% of the original color. It's just a visual representation I used to let user know if the saturation has been increased or decreased which doesn't represent the accurate value. It's quite hard to represent saturation value because different colors have different level of saturation.

I am curious to know why do you want more flat colors? As this will completely break the purpose of color palette generated by monet.

**Comment by VitoFe** [comment]
> You are right, it is not actually 0% or 100% of the original color. It's just a visual representation I used to let user know if the saturation has been increased or decreased which doesn't represent the accurate value. It's quite hard to represent saturation value because different colors have different level of saturation.
> 
> I am curious to know why do you want more flat colors? As this will completely break the purpose of color palette generated by monet.

Let's say I'm in dark mode and using magenta as accent color. On most apps I'd get washed-out magenta or some very light magenta which looks like pink basically. The issue is with the brighter part of the scale, I'd rather have them be white than the washed out lighter accent color, and on the part of the scale near the center I'd rather have a single lighter accent color, the actual accent color and then the darker variations till the end.

Why? Because a lot of apps appear to pick different steps of those colors, and I'd rather have them use just a restricted set of them, as it makes every app look slightly off-theme.
