### ISSUE TITLE
[BUG] Changed colors not working in work profile

### ISSUE THREAD

**Issue by matt1432** [Mahmud0808/Iconify#101]
### Describe the bug

I am using Shelter and the work profile of Android to isolate some apps for privacy, and whenever I go on those apps, the colors that I've changed on the Monet Engine are the default ones, picked by my wallpaper's colors.

### Steps to reproduce

1. Install Shelter and a Material You compatible app.
2. Go on app

### Expected behavior

Whenever I go on an app in my work profile, I expect the colors to follow the change I've done using this app.

### Device information

- Device: [Oneplus 9 Pro]
- OS: [LineageOS ROM Android version 12.0]
- App version: [6.1.0]

**Comment by Mahmud0808** [comment]
Work profile is completely isolated. It's a thing from Google. This issue can not be considered as bug.
