### ISSUE TITLE
[FEATURE] Separated Notification/QS Panels

### ISSUE THREAD

**Issue by devycarol** [Mahmud0808/Iconify#103]
### Describe the feature

I think this could be accomplished in a few simple steps (simple-seeming to me as an outsider, that is).

1. Allow the notification panel QS rows to be set to zero
2. Allow the disabling of gesturally switching between and/or closing the notification & QS menus
    - QS would still be accessible via two-finger statusbar pulldown or the user's quick pulldown gesture config, and perhaps a button in there that allows switching between the two
3. Allow changing the QS menu so that dismissing it via swipe-up gesture or back button press closes it entirely rather than returning to the notification screen

### Why would it be useful to add?

The vanilla system of amalgamating the notification and QS menus is and always has been fundamentally clunky and unintuitive in my opinion. It creates a number of problems:
- A passive uneasiness when it comes to the 'quick pulldown' gesture and what exactly it's doing.
- Ambiguity between swipes to scroll through the menus versus dismissing/switching between them.
- Over-crowding on the notification screen, especially when the media player is present—this is even true on my super-skinnytall Pixel 5a! I can't even imagine what it'd be like for someone who permits persistent notifications in their workflow.

I think it would be good to compartmentalize these two menus to give each of them more breathing room on the screen, and to instead have the mechanism for switching between the two be a simple button. Bonus accessibility + hardware-support points for mapping this to the 'menu' button, though you can probably see from my screenshots that this would be getting increasingly tailored to my personal setup ;).

### Example(s)

I believe this is how the OS used to be, although this may only be true of my old CyanogenMod 11 phone and whatever its software cousins were.

But as a visual example, I think that a notification panel that looks something like this ordinarily—disregarding my personal customizations to border radius, the navigation bar,  etc.—would be a good thing.

![Screenshot_20230311-192626](https://user-images.githubusercontent.com/69347329/224521460-01d9efb9-792b-46a8-9f24-b0b0cb354303.png)

CM11's quick toggles looked like this. The button in the top right switches between QS and notifications.
![CM Quick Toggles](https://user-images.githubusercontent.com/69347329/224522004-bee4b1fb-8175-499e-886f-a37cd4eb2c42.png)

### Additional context

I can understand if this feature is deemed to be outside of the scope of this project. If so, and you happen to know of this functionality being replicated elsewhere such as a different project, that information would be appreciated.

**Comment by Mahmud0808** [comment]
You are right, this feature is indeed outside of the scope of this project. This kind of functionality is not available in any project yet afaik. And this might not even be feasible as it's very complex to achieve.
