### ISSUE TITLE
Fastlane: changelogs much too long

### ISSUE THREAD

**Issue by IzzySoft** [Mahmud0808/Iconify#107]
### Describe the bug

Changelogs in your fastlane tree exceed the limit of 500 char by far and hence are simply truncated.

### Steps to reproduce

Take a look at them :wink: 

### Expected behavior

As per fastlane specifications, they don't exceed 500 char.

### Device information

n/a

**Comment by Mahmud0808** [comment]
Me adds too much changes. 😢 Will keep it short next time.

**Comment by IzzySoft** [comment]
Thanks for picking this up that fast!

Btw: You can always have it end with something like "full changelog at {link}" (just no `<a href` please, as changelog is expected to be plain text) – and have the link like `https://github.com/Mahmud0808/Iconify/releases/tag/v6.1.0` as you put a nice changelog there :smiley:
