### ISSUE TITLE
Roundness

### ISSUE THREAD

**Issue by bugycugy** [Mahmud0808/Iconify#11]
"Roundness of qs tile, brightness bar and notification" this problem still persists for me.
Rom: OctaviOS (A13 - Alpha)
Device: Tucana

**Comment by Mahmud0808** [comment]
Try a clean install of v2.0-Beta and let me know if it still happens. (Uninstall iconify, remove magisk module, reboot phone, then install again)

**Comment by bugycugy** [comment]
First of all, thank you, my problem was solved when I did a clean install.
I am having text problem in QS Panel. The text of the active QS icon is not visible, can you help with this?

[https://ibb.co/PW5r7cS](url)
[https://ibb.co/h8MzMHD](url)

**Comment by Mahmud0808** [comment]
Currently the app isn't ready for multi language support. I will merge other languages when it's ready. Thank you.
