### ISSUE TITLE
[FEATURE] Add please Paranoid volume style

### ISSUE THREAD

**Issue by dedsecproyt** [Mahmud0808/Iconify#114]
### Describe the feature

![IMG_20230329_200101](https://user-images.githubusercontent.com/60039962/228613729-484ed171-4d40-46cd-ab30-879dbded5f49.jpg)

### Why would it be useful to add?

Perfect volume style and very usefull style

### Example(s)

You can see your volume step on %

**Comment by Mahmud0808** [comment]
Can you provide the link of the commit of this volume panel from Paranoid's github repo?

**Comment by dedsecproyt** [comment]
> Can you provide the link of the commit of this volume panel from Paranoid's github repo?

I don' t can find Paranoid volume commit but i have app whith it's volume 
https://play.google.com/store/apps/details?id=com.tombayley.volumepanel
Paranoid OS Repo - https://github.com/AOSPA
