### ISSUE TITLE
Force Light Mode on QS Pannel on non Aosp rom like nothing phone, Pixel phone [FEATURE] 

### ISSUE THREAD

**Issue by allenevan** [Mahmud0808/Iconify#117]
### Describe the feature

It would be very nice to have a light qs Pannel on Non Aosp rom like Nothing Os, or stock Pixel os

### Why would it be useful to add?

It seems pretty bad when everything is in light mode except the qs Pannel 

### Example(s)

![Screenshot_20230401-150119~2](https://user-images.githubusercontent.com/92501868/229276621-487000d2-bc7e-4fef-b553-1d661335a7fa.png)

**Comment by Tenun-negi** [comment]
It is not nice with Iconify overlay, color is weird when i use aosp mod light qs panel with Iconify qs tiles/brightness overlay
