### ISSUE TITLE
Add an option to Hide Statusbar Completely [FEATURE] 

### ISSUE THREAD

**Issue by allenevan** [Mahmud0808/Iconify#118]
### Describe the feature

Could you please add an option to hide the Statusbar Completely.. like notchbar killer or something like this please 

### Why would it be useful to add?

There are lots of people who love to have a clean and simple ui . Wanted to get the full display 

### Example(s)

Similar to notchbar killer

**Comment by Mahmud0808** [comment]
So you want the statusbar gone and also want all apps to use that empty space? This will make issue with phones which has notch and punch hole display.

Edit: Added notchbar killer, hereby closing this issue as completed.

**Comment by allenevan** [comment]
Previously i used to use ( G- visual Mod ) mod to hide the notch...

**Comment by Mokura** [comment]
I use a similar app and while the camera on my phone does obscure a bit of the top screen (Pixel 6a), getting the space back and avoiding burn-in is worth it to me.
