### ISSUE TITLE
[FEATURE] Export/import settings 

### ISSUE THREAD

**Issue by ddnexus** [Mahmud0808/Iconify#119]
### Describe the feature

Simple setting menu that can save a file (backup settings) and apply it at later time.

### Why would it be useful to add?

Would help reinstalling/changing ROMs by reapplying consistently a tons of mods!

### Example(s)

N/A

**Comment by Mahmud0808** [comment]
Backup and restore settings was there in previous versions but has been removed in latest update (v6.1.1) as it was getting more complex for me to maintain it with new features being added regularly.

**Comment by ddnexus** [comment]
> more complex for me to maintain

Understandable. Thank you.

**Comment by Mahmud0808** [comment]
https://github.com/Mahmud0808/Iconify/commit/fb3849346fb0fc80ec2500e29c633c4777741c99

**Comment by ddnexus** [comment]
Thank you!!!
