### ISSUE TITLE
[BUG] Control Center appereance

### ISSUE THREAD

**Issue by Tutruelove** [Mahmud0808/Iconify#127]
### Describe the bug

There is an error. When I choose a theme it appears like this, when a function is chosen the icon dissapear like this.
It doesnt look good.

### Steps to reproduce

.

### Expected behavior

.

### Screenshots

![Screenshot_20230409-214856](https://user-images.githubusercontent.com/116581012/230822309-9f191052-05a8-46aa-8df0-2d556aa4320c.png)
![Screenshot_20230409-214830](https://user-images.githubusercontent.com/116581012/230822325-30998452-92c9-495c-a0ba-5cb5cfa9afc1.png)
![Screenshot_20230409-214800](https://user-images.githubusercontent.com/116581012/230822352-a60b507b-6111-4107-b12a-e42f30a9efac.png)

### Device information

- Device: [Motorola G60]
- OS: [e.g. stock ROM Android version 12.0]
- 

### Additional context

.

**Comment by Mahmud0808** [comment]
Enable QS text color fix from Tweaks -> QS Panel -> Icon & Label. After that try restarting SystemUI.

**Comment by Tutruelove** [comment]
> Enable QS text color fix from Tweaks -> QS Panel -> Icon & Label. After that try restarting SystemUI.

![Screenshot_20230410-083658](https://user-images.githubusercontent.com/116581012/230923299-0848b010-322b-4eee-b779-8a7510d5dafe.png)
It doesnt work for me 😿

**Comment by Mahmud0808** [comment]
Is the rom open source? Provide link so that I can look into it. If not, can't do much about it.

**Comment by Tutruelove** [comment]
> la rom es open source? Proporcione el enlace para que pueda investigarlo. Si no, no se puede hacer mucho al respecto.

1) It is open source
2)You mean this? https://motostockrom.com/motorola-moto-g60-xt2135-1
3) It is a motorola G60 stock ROM

**Comment by Mahmud0808** [comment]
>    2)You mean this? https://motostockrom.com/motorola-moto-g60-xt2135-1

I need link of the source code of ROM. This is not the source code.

**Comment by EleoXDA** [comment]
> > la rom es open source? Proporcione el enlace para que pueda investigarlo. Si no, no se puede hacer mucho al respecto.
> 
> 1) It is open source
> 2)You mean this? https://motostockrom.com/motorola-moto-g60-xt2135-1
> 3) It is a motorola G60 stock ROM

I don't think motorola is releasing open source firmware code. It has to be closed source as they have looots of differences with respect to clean AOSP
