### ISSUE TITLE
[FEATURE] ios battery style

### ISSUE THREAD

**Issue by CRYSTAF** [Mahmud0808/Iconify#134]
### Describe the feature

I think I'm not the only one who liked the style of the battery, like ios 16 version seems to have a percentage of charge inside the icon. I would like to see this feature in iconify. And in general, I would like to be able to change the battery icon to your liking, because there are very few styles now.

### Why would it be useful to add?

Design

### Example(s)

<img width="391" alt="1tuh2j7bzh3m14banehw4gst32ivmyk3" src="https://user-images.githubusercontent.com/67143925/232345522-b739b98d-82c4-4bc7-8373-d4f162885989.png">

**Comment by Mahmud0808** [comment]
These battery styles are possible to make with XPosed Framework but it's very much hard and not worth it. Better to use rom which already has these styles as it's easier to include them in rom's source.
