### ISSUE TITLE
Custom Header Clock - Extended QS Panel[BUG] 

### ISSUE THREAD

**Issue by Undisputed00x** [Mahmud0808/Iconify#135]
### Describe the bug

Custom Header Clock when QS Panel gets extended clock stays static and does not drop down like the rest statusbar icons

### Expected behavior

When QS Panel is extended it Custom Header Clock should be expected to drop down to the same horizontal level like the other statusbar icons

Have disable/enable the feature - restarted SysUI - rebooted device - disable/enable Xposed module - disable/enable all features 

### Screenshots

![Screenshot_20230417-235059_Trebuchet](https://user-images.githubusercontent.com/80290008/232612761-b09a700a-d69b-4295-85b9-aed50da1c90b.png)
![Screenshot_20230417-235106_Trebuchet](https://user-images.githubusercontent.com/80290008/232612775-0d111dac-dabe-434e-b090-c5450e4f6467.png)

### Device information

- Device: Xiaomi Poco X3 Pro
- OS: LineageOS 19.1 (latest build) Android 12L
- App version: 6.1.1

**Comment by Mahmud0808** [comment]
It is intended and not a bug. If I make it move with the status icons while expanding, it will be buggy with large header clocks. Clock will collpase with QS Tiles and increasing qs top margin will make it more collapsed. That is why I chose to make the header clock in a fixed position.

**Comment by Undisputed00x** [comment]
I think that's already buggy in static place in case you increase size which overrides QS tiles.
Can you make an option in settings for my case that would be great

**Comment by Mahmud0808** [comment]
> I think that's already buggy in static place in case you increase size which overrides QS tiles.

XPosed Menu > Quick Settings > Top margin
