### ISSUE TITLE
Custom Lockscreen Clock - not working[BUG] 

### ISSUE THREAD

**Issue by Undisputed00x** [Mahmud0808/Iconify#136]
### Describe the bug

Custom Lockscreen Clock when enabled is not working, instead it show an empty space in its intented place. Customizing margins does not help.

### Expected behavior

Custom Lockscreen Clock is expected to be shown as it is intented 

### Screenshots

![Screenshot_20230417-235305_System UI](https://user-images.githubusercontent.com/80290008/232614158-9b385358-457d-44d4-bcba-ddca71ebe5bf.png)
![Screenshot_20230417-235351_Trebuchet](https://user-images.githubusercontent.com/80290008/232614169-d66f403f-2a55-4375-b798-5eb6472eabe5.png)
![Screenshot_20230417-235404_Iconify](https://user-images.githubusercontent.com/80290008/232614177-906664c9-fdc5-43ef-aeb9-c181733dbd1d.png)

### Device information

- Device: Xiaomi Poco X3 Pro
- OS: LineageOS 19.1 (latest build) Android 12L
- App version: 6.1.1

**Comment by Mahmud0808** [comment]
Did you tap on a different clock style? Provide LSPosed logs.

**Comment by Undisputed00x** [comment]
Issue solved

I had to configure a little bit size margins and line height for clock to be shown 
probably my settings were conflicting as a result clock wasnt able to be shown

https://imgur.com/a/IchAvdx
