### ISSUE TITLE
BLACK SCREEN[BUG] 

### ISSUE THREAD

**Issue by zerotracex** [Mahmud0808/Iconify#137]
### Describe the bug

After i applied surrounded quick tile my device screen is completely black and just showing battery icon pls help me faster pls

### Expected behavior

i expected to change qs tiles

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. v4.0-Beta]
android 13
nusantara os

**Comment by Mahmud0808** [comment]
You are using v4.0 while the latest version is v6.1.1
For faster response, use telegram support group.

To fix the issue, just remove module, uninstall old version and use the latest version.
https://github.com/Mahmud0808/Iconify#in-case-of-bootloop

**Comment by zerotracex** [comment]
its not bootloop issue device is loaded and calls sounds also coming but just black screen with battery indicator at status bar level so please help me

**Comment by Mahmud0808** [comment]
It's called BSOD (Black Screen of Death), just follow what I said. It should be fixed.

**Comment by zerotracex** [comment]
in my device twrp showing internal storage 0mb how can i follow

**Comment by Mahmud0808** [comment]
Reboot into safe mode.

**Comment by zerotracex** [comment]
i cant see power menu ,how i can go into safe mode?

**Comment by Mahmud0808** [comment]
Bruh why do I even provide help when you are clearly not reading anything at all?

https://github.com/Mahmud0808/Iconify#in-case-of-bootloop

Everything you need to fix black screen issue is there.
