### ISSUE TITLE
[BUG] Custom lockscreen clock not updating from idle

### ISSUE THREAD

**Issue by Pop28** [Mahmud0808/Iconify#138]
### Describe the bug

If you turn on any of the custom lockscreen clocks, the time will be behind or not updated after waking the screen.

### Steps to reproduce

1. Turn on 'Custom Lockscreen Clock'.
2. Tap on any 'Clock Style'.
3. Restart system ui.
4. Turn off the display and wait around 15 minutes.
5. Wake the display to see the lockscreen clock is behind.

### Expected behavior

Lockscreen clock should display the correct time when waking the screen.

### Device information

- Device: OnePlus 7 Pro
- OS: YAAP, Flamingo, and CrDroid, all on Android 13
- App version: 6.1.1

**Comment by saipr0** [comment]
Facing the same issue

**Comment by Mahmud0808** [comment]
Known, no fix yet.

Alternatively you can hide stock clock and use Lockscreen Widgets instead.

**Comment by devanteweary** [comment]
I see that you've acknowledged it. Just wanted to chime in and say this happens to me too and actually I was late for work from this bug the other day before I knew it was a bug! haha

**Comment by Mahmud0808** [comment]
> I see that you've acknowledged it. Just wanted to chime in and say this happens to me too and actually I was late for work from this bug the other day before I knew it was a bug! haha

That's a terrible thing to hear. Sorry for the inconvenience. I will add a warning in app to avoid such circumstances in future. Again sorry for the trouble.
