### ISSUE TITLE
[BUG] not fully working on motorola stock a13

### ISSUE THREAD

**Issue by Mersand** [Mahmud0808/Iconify#139]
### Describe the bug

after i switched to the newest stock rom there&install iconify as usual,i noticed that most of the tweaks doesn't work anymore.
almost most of styles is not working,except icon packs which still changes icon but without changing wifi.
for tweaks,only qs icon&label setting,and transparency&blur setting works.

### Steps to reproduce

1.apply option in app
2.wait for double trigger dark mode/systemui restart/manually reboot to be done
3.nothing happens

### Expected behavior

/

### Device information

- Device: motorola edge 20 pro
- OS: motorola stock ROM Android version 13
- App version: 6.1.1(dev build not working as well)

### Additional context

iconify was working well with stock a12 and custom aosp(lmo&lineage) on the device.so im assuming its not fully compatible with a13 yet? hope for a solution,anyways.

**Comment by Mahmud0808** [comment]
That's weird. Tried reinstalling iconify?

**Comment by Mersand** [comment]
> That's weird. Tried reinstalling iconify?

yep.i first assume it's conflict with aospmods,so i tried several times reinstall to see if both mods work well alone.figured out only iconify not working it seems

**Comment by Mahmud0808** [comment]
check if IconifyCompanion files are available in /system/product/overlay/ directory

**Comment by Mersand** [comment]
![Screenshot_20230424-175856](https://user-images.githubusercontent.com/103516218/233964904-a1c5c418-17df-4114-b498-58adedfa9300.png)
is anything wrong with them?

**Comment by Mahmud0808** [comment]
Run this command in terminal emulator or termux and send me screenshot of the result

`>> su`
`>> cmd overlay list |  grep -E '^.x..IconifyComponent' | sed -E 's/^.x..//'`

**Comment by Mersand** [comment]
![Screenshot_20230424-182904](https://user-images.githubusercontent.com/103516218/233972132-7b5a3d71-19a4-4cae-be27-1a54a2710a88.png)
tried multiple times but no output

**Comment by Mahmud0808** [comment]
> tried multiple times but no output

Did you not enable any option? If you enable options in iconify, you'll get output here in termux with the provided command line. If you already enabled some options but still no output, then I need more logs. Use matlogs, enable disable multiple options which are not working, then provide me the logs so I can check more thoroughly.

Edit:
> so im assuming its not fully compatible with a13 yet?

Iconify works on A14 beta too. I am using Iconify on A13 QPR2 right now. A few xposed features are broken, but everything else are working.

**Comment by Mersand** [comment]
[Log_2023-04-24_19-07-49.txt](https://github.com/Mahmud0808/Iconify/files/11309782/Log_2023-04-24_19-07-49.txt)
i tried to enable all options,then only the switch applied and shown in terminal output.
by the log,i tried to enable lightness slider and disable and re-enabled it.

**Comment by Mahmud0808** [comment]
Forgot to ask, are you using official magisk? can you try version 25.2 of magisk?

**Comment by Mersand** [comment]
am currently on 25.2 official
or shall i try 26.1?

**Comment by Mahmud0808** [comment]
I am totally confused why it's not working. My guess is Iconify isn't able to enable or disable overlays for some reason. Try updating magisk if it isn't too much.

**Comment by Mersand** [comment]
unfortunately updating magisk didn't work too.i did reinstall iconify as well..
as im not a developer,just assume moto have their own overlay over systemui too.anyways if more log will help i will try catch

**Comment by Mahmud0808** [comment]
Motorola roms are not open source and source isn't same as stock pixel roms, so can't fix. Closing this issue.
