### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hua1yan** [Mahmud0808/Iconify#144]
### Describe the bug

I use wifi6, so there will be a number 6 on the status bar wifi icon. If I modify the status bar icon, the others will change and the wifi icon will not change.

### Device information

- Device: [Xiaomi 10s]
- OS: [pixel experience]
- App version: [6.11 dev(#827)]

https://photos.app.goo.gl/TBBWZPUb9YEsHG5e9

**Comment by Mahmud0808** [comment]
Kindly fix the title and description.

Edit: Use latest debug. WiFi 4, 5, 6 icons have been added. If still not fixed then re-open the issue and send framework-res.apk from /system/framework directory
