### ISSUE TITLE
[FEATURE] Landscape QS tiles Rows/Columns/QuickQS customization

### ISSUE THREAD

**Issue by Username1-a** [Mahmud0808/Iconify#147]
### Describe the feature

Hello and thank you for this module

It would be nice to have an ability to change the rows/columns/quick QS rows for a landscape orientation, too, in Tweaks>QS Panel>Row and Column, not just portrait.

There's a "QS Grid Generator" magisk module for A12/13 that does similar stuff, but it has limitations, as it only allows 4 columns max in a landscape orientation (same like on a stock).

### Why would it be useful to add?

For example, it could make much more easier navigating Quick Settings in landscape orientation while media player is shown next to it, because it would allow to show more QS tiles at one time, not just 4 like on a stock Android 12/13 (a poor use of space, see attached screenshot). 

At least, that's the way landscape QS tiles layout customization works in some A12/13 custom ROMs – it allows you to show 6 tiles at the same time while the media player is shown.

And in general, it would've made sense to have landscape layout customization since there's already portrait layout customization out there.

### Example(s)

![Screenshot_20230509-014440_Iconify](https://user-images.githubusercontent.com/47947180/236956803-f7835b11-270d-451e-9c11-b3771e2c04c6.png)

![Screenshot_20230509-015112_Settings](https://user-images.githubusercontent.com/47947180/236957006-feeac9a4-33f8-4382-b479-00abab0c656c.png)

![Screenshot_20230509-015122_Settings](https://user-images.githubusercontent.com/47947180/236957043-00b75d22-951c-40d0-812b-132f65bb87b0.png)

![Screenshot_20230509-014952_Termux](https://user-images.githubusercontent.com/47947180/236956848-81840a52-c0b8-4e7a-bab6-bed8e154026d.png)

**Comment by Mahmud0808** [comment]
That implementation (QS Grid Generator) doesn't work with 600+ dpi users, that's why I had to go with a different implementation which unfortunately isn't orientation depended.
