### ISSUE TITLE
[BUG] status bar header clock

### ISSUE THREAD

**Issue by AGARAN24** [Mahmud0808/Iconify#156]
### Describe the bug

If I enable custom header clock, my existing system clock is also in the background therefore overlapping each other. Attached image for reference.

![Screenshot_20230518-002922~2](https://github.com/Mahmud0808/Iconify/assets/45871692/be40bc88-8b3a-456c-b49a-1fd25d862de9)

### Steps to reproduce

1. Turning on custom header clock under lsposed tweaks.

### Expected behavior

It shouldn't overlap each other, the default clock must disappear right? I tried searching the app if there is an option to turn it off, I couldn't find it. 

### Screenshots

![Screenshot_20230518-002922~2](https://github.com/Mahmud0808/Iconify/assets/45871692/34c41cb1-a6ad-4d63-9a28-f059ce77a281)

### Device information

- Device: Google Pixel 7 Pro
- OS: stock rooted, lsposed, android 13 march
- App version: latest 6.1.1

### Additional context

I tried re optimising in lsposed, restarting phone, disabling and enabling multiple times.

**Comment by Mahmud0808** [comment]
Already fixed on debug version.
