### ISSUE TITLE
Settings switches, lockscreen clock and pin entery screen not affected by color engine

### ISSUE THREAD

**Issue by etenium** [Mahmud0808/Iconify#16]
I'm using lineageOS 20 (Android 13) and some accent colors still are monet generated and not the one i picked in Color Engine like:

Lockscreen clock:
![Screenshot_20221118-131940_Kiwi Browser](https://user-images.githubusercontent.com/99820286/202922210-fd013139-1956-4699-8ad6-41bdf0185121.png)

Some buttons when entering PIN code:
![Screenshot_20221118-132014_Settings](https://user-images.githubusercontent.com/99820286/202922230-5b12c80f-cadb-4d0e-b38e-8265074d4b3d.png)

Switches in settings:
![Screenshot_20221120-202604_Settings](https://user-images.githubusercontent.com/99820286/202922365-5480749e-0a37-47e1-aac9-d2f92b6ba51a.png)

Hope you can add options to change colors of those items because the blue washed out color does not fit the red accent color at all.

**Comment by Mahmud0808** [comment]
Color Engine only changes the basic accent colors used by various components of Iconify. If you want to change every shade of color, I think Repainter is the best option available out there as it is freemium currently.

**Comment by etenium** [comment]
The problem with repainter is that it does not work unless you have google services installed. Project Themer is not an option either since I'm trying to stay away from Google Play Store

**Comment by Mahmud0808** [comment]
I will try to do something about it. Wait for the next release.
