### ISSUE TITLE
Arabic Langauge support [FEATURE] 

### ISSUE THREAD

**Issue by muhammadbahaa2001** [Mahmud0808/Iconify#161]
### Describe the feature

Add Arabic language support.

### Why would it be useful to add?

I understand English well but, it is nice to see your language.

### Example(s)

.

### Additional context

Not only I want to see Arabic language support, Iconfiy should support RTL system UI because some applied customization are broken.

**Comment by Mahmud0808** [comment]
Add proper translations, make a pull request. I will review and merge changes.

Also let me know which customizations are broken in RTL mode, I will try to fix.

**Comment by chlorospingus** [comment]
For RTL being broken, you can quickly disable and re-enable RTL with a qs tile and that should fix it.

**Comment by Mahmud0808** [comment]
Create a pull request, I will review and merge. Closing this issue.
