### ISSUE TITLE
[BUG] Enabling QS shade bg transparency also makes lockscreen keyguard bg transparent

### ISSUE THREAD

**Issue by Username1-a** [Mahmud0808/Iconify#164]
### Describe the bug

Hi, don't know if this could be fixed or if this expected behavior, but it looks like enabling QS/Notification shade transparency in Tweaks>Xposed Menu>Transparency & Blur, also makes lockscreen keyguard (the screen with PIN/Pattern/Password) background transparent. It looks like QS background and lockscreen keyguard background somehow linked together. So, if user, for example, wants to set Transparency Alpha to 0 (or any value lower than 30), then lockscreen keyguard will have poor readability

### Steps to reproduce

1. Go to 'Tweaks>Xposed Menu>Transparency & Blur'
2. Set Transparency Alpha to 0
3. Restart SystemUI
4. Observe that lockscreen keyguard bg also changed

### Expected behavior

Lockscreen keyguard background will remain unchanged 

### Screenshots

![Screenshot_20230520-173504_Lawnchair (Debug)](https://github.com/Mahmud0808/Iconify/assets/47947180/54ed8dfd-6910-4807-9dc4-8277f622e48b)
![Screenshot_20230520-173545_Lawnchair (Debug)](https://github.com/Mahmud0808/Iconify/assets/47947180/6ae7f218-fff6-47c1-9bbe-44e314180cae)

### Device information

- Device: Redmi Note 10 Pro
- OS: Android 13 QPR1, Pixel Experience custom ROM
- App version: v6.2.0

### Additional context

Alternatively, an option to enable blurred bg on a lockscreen keyguard (just like in QS shade) could probably fix poor readability issue

**Comment by Mahmud0808** [comment]
As far as I can understand from AOSP source code, QS panel and lockscreen both are using the same shade. I don't think it can be unlinked.
