### ISSUE TITLE
[BUG]  Misaligned Margin for GCam using Notch Bar Killer

### ISSUE THREAD

**Issue by Jerrriell** [Mahmud0808/Iconify#165]
### Describe the bug

It seems the notch bar killer is affecting apps margin to be misaligned

Using Pixel 6 on stock rooted A13

### Steps to reproduce

1. Go to 'iconify'
2. Click on 'tweaks'
3. Scroll down to 'miscellaneous'
4. See enable Notch bar killer
5. Check gcam and margin is not aligned properly

### Expected behavior

Should have no changes in the margin for camera apps

### Screenshots

![Screenshot_20230520-235756_Camera](https://github.com/Mahmud0808/Iconify/assets/129885189/748f2efe-84b4-452a-8af4-603dc19a6b0f)
Normal look of gcam (notch bar killer disabled)

![Screenshot_20230520-235425_Camera](https://github.com/Mahmud0808/Iconify/assets/129885189/ebae0da4-88d0-4ce1-a41b-6fd1a72aaf17)

Look of gcam after notch bar killer is applied

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. v4.0-Beta]

**Comment by Jerrriell** [comment]
note: Im on a13 not sure why it shows a12

**Comment by Jerrriell** [comment]
Using the latest build (6.2.0)

**Comment by Mahmud0808** [comment]
I don't know if it still works but this one is a better solution in your case
https://github.com/ccat3z/no-display-cutout

**Comment by Jerrriell** [comment]
Just used it and the margin is still not aligned this must be a gcam issue?

**Comment by Mahmud0808** [comment]
> Just used it and the margin is still not aligned this must be a gcam issue?

Probably yeah, also google did something on A13 which made immersive mode look weird. This might be related to that.
