### ISSUE TITLE
Want universal icon changer 

### ISSUE THREAD

**Issue by AraafRoyall** [Mahmud0808/Iconify#167]
### Describe the feature

Hi developer. Can you make the app to change Any icon image in any app from internal storage using Xposed or Lsposed framework. 

### Why would it be useful to add?

Because some app contains icons images which looks bad. 

### Example(s)

Hope you understand

**Comment by Mahmud0808** [comment]
Any good 3rd party launcher should be able to do that. If something can be done without xposed, then don't use xposed. Xposed hooking method isn't the most reliable thing as different roms and launchers have different changes made into source code.

**Comment by AraafRoyall** [comment]
> Any good 3rd party launcher should be able to do that. If something can be done without xposed, then don't use xposed. Xposed hooking method isn't the most reliable thing as different roms and launchers have different changes made into source code.

I think you dont understand ... I told to change icons and images from inside the app not app icon. Hope you understand

**Comment by Mahmud0808** [comment]
You should better approach with substratum theme method for that. Overlays can easily change in-app icons if the app isn't obfuscated.

**Comment by AraafRoyall** [comment]
> You should better approach with substratum theme method for that. Overlays can easily change in-app icons if the app isn't obfuscated.

I want to change in-app icons as per my coise by selecting from internal storage . to make app design as per my choice.  Ok still thanks for your reply.
