### ISSUE TITLE
Always use light accent on black qs

### ISSUE THREAD

**Issue by Rubberxgum** [Mahmud0808/Iconify#168]
### Describe the feature

There should be an option to always use light accent on black qs.

### Why would it be useful to add?

Dark accent just looks bad on black qs. And it's always on dark mode anyways, so it makes sense to only have light accent.

### Example(s)

I don't think this even needs a picture.

**Comment by Mahmud0808** [comment]
By default dark mode uses lighter accent and light mode uses darker accent. Are you talking about more light accent than the current one?

**Comment by Rubberxgum** [comment]
No, I am talking about the default light accent. When my phone is in light mode, the qs panel has a dark accent, even if I am using black qs. 

 The feature that I am suggesting is for the qs panel to always have a light accent regardless of whether the phone is in light mode or dark mode.

**Comment by Mahmud0808** [comment]
![Screenshot_20230529-124306_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/29881338/5c49442c-82e0-4e74-87e6-f46308874418)

It's already there. Enable it and if you are using Iconify's monet engine then re-apply colors from monet engine.

**Comment by Rubberxgum** [comment]
This option also applies a light accent to the notification panel and volume panel. I only want it on the qs panel.

**Comment by Mahmud0808** [comment]
> This option also applies a light accent to the notification panel and volume panel. I only want it on the qs panel.

Oh okay understood, I will check if that's possible.
