### ISSUE TITLE
[FEATURE] MD2 Toggles

### ISSUE THREAD

**Issue by gaussandhisgun** [Mahmud0808/Iconify#169]
### Describe the feature

So we have custom switches in Iconify. I propose adding a Material Design 2 switch (the one from older android releases) to it, because why not?

### Why would it be useful to add?

Some people might like it more that way. Me, for example.

### Example(s)

![image](https://github.com/Mahmud0808/Iconify/assets/63512006/25b7d923-2aeb-412e-a364-a2df81b99fba)
Captured under Waydroid on Android 11.

### Additional context

It should not be that hard to do, just copying over the code for Material Switch and modifying a few values (notably colors and borders) should do the trick.

**Comment by Mahmud0808** [comment]
A12+ forces the minimum track height to be at least equal to thumb's height. So I don't know if MD2 switch style is possible anymore. I will add if I get any workaround.

Edit: Not possible anymore.
