### ISSUE TITLE
[FEATURE] Integrated Tablet Quick Settings for phones

### ISSUE THREAD

**Issue by gaussandhisgun** [Mahmud0808/Iconify#170]
### Describe the feature

There's this Magisk overlay floating around, https://t.me/modulesrepo/4479 - it moves the quick settings to the left in landscape view and displays notifications on the right, to make better use of wider display and screen real estate.

### Why would it be useful to add?

It makes using Android in landscape less frustrating, because you see more content at a glance.

### Example(s)

![image](https://github.com/Mahmud0808/Iconify/assets/63512006/0caa2e7c-9332-489a-93e7-0049d33c7abb)
![image](https://github.com/Mahmud0808/Iconify/assets/63512006/36b1877b-1a80-4272-bc33-7c608fbb2907)
(ignore the notification tiles shape, its my rom thing)

### Additional context

it is just two overlays, and one of them is notchkiller, so it should not be hard to add the other one too

**Comment by Mahmud0808** [comment]
This is tablet view and I can only add this if I get permission from the owner. As I saw that the owner wanted to make it paid module, so I don't think he will be willing to give permission for it.

Edit: Got permission.
