### ISSUE TITLE
Header Clock on QS is bugged.

### ISSUE THREAD

**Issue by ScottN13** [Mahmud0808/Iconify#171]
### Describe the bug

![Screenshot_20230527-162225_Nova Launcher](https://github.com/Mahmud0808/Iconify/assets/87974560/54bd12ac-decf-41d8-bb68-0ef2948b878b)
This is well, what it looks like.

### Steps to reproduce

1. Go to 'Xposed tweaks'
2. Click on 'Header clock'
3. Apply anything and restart sysUI

### Expected behavior

What it looks like in the image above.

### Device information

- Device: Samsung Galaxy S10+ Exynos
- OS: PixelExperience 13
- App version: 6.1.1

**Comment by Mahmud0808** [comment]
Use Iconify v6.2.0

**Comment by ScottN13** [comment]
Do i have to disable everything or use the built in updater? @Mahmud0808

**Comment by ScottN13** [comment]
Oh nvm, update from new apk.
