### ISSUE TITLE
Rebooted into core-only mode after update

### ISSUE THREAD

**Issue by ScottN13** [Mahmud0808/Iconify#172]
### Describe the bug

Just rebooted back and i got rebooted into core-only.

### Steps to reproduce

1. Update from 6.1.1 to 6.2.0 using apk
2. Reboot
3. Go through the lockscreen
4. Immediately get restarted to core-only.

### Expected behavior

Like said above 

### Device information

- Device: Samsung Galaxy S10+
- OS: PixelExperience 13
- App version: ??

### Additional context

I just made this issue after the reboot.

**Comment by Mahmud0808** [comment]
Remove module and try to clean install 6.2.0

This issue is happening randomly and that's why I can't figure out the exact reason. Although never happened to me.

**Comment by ScottN13** [comment]
If this helps:

After update, i entered the app and i got back to the setup screen.

**Comment by Mahmud0808** [comment]
> After update, i entered the app and i got back to the setup screen.

That is intentional as the new overlays need to be recreated.

**Comment by ScottN13** [comment]
So do i delete the old overlays or just go?

**Comment by Mahmud0808** [comment]
> So do i delete the old overlays or just go?

No need to delete.

**Comment by ScottN13** [comment]
I hadn't have time today but ill do the following:

1. Install Iconify 6.2.0 apk
2. Delete modules (no reboot)
3. Setup
4. Reboot

**Comment by ScottN13** [comment]
Is this ok?

**Comment by ScottN13** [comment]
Is this ok?

**Comment by ScottN13** [comment]
@Mahmud0808

**Comment by Mahmud0808** [comment]
> I hadn't have time today but ill do the following:
> 
> 1. Install Iconify 6.2.0 apk
> 2. Delete modules (no reboot)
> 3. Setup
> 4. Reboot

Was busy with my exams, so didn't visit github much.

Clean installation steps are:
1. Remove old version and module.
2. Reboot phone.
3. Install new version.
4. Reboot phone and done.

**Comment by ScottN13** [comment]
Closing issue cause it worked.
Phone died later cause of hardware issue. Thanks anyway!
