### ISSUE TITLE
[FEATURE] Make the QS page indicator color customizable

### ISSUE THREAD

**Issue by gleniu87** [Mahmud0808/Iconify#173]
### Describe the feature

A user should be able to decide if the QS page indicator (the dots under expanded quick settings tiles) is in white or accent color.

### Why would it be useful to add?

Just another feature to make this awesome app more awesome. Also, it gives the theme more consistency with system, as indicators in accent color are used system-wide (in settings, etc.).

### Example(s)

For now, it looks like this using default theme:
![how it is now](https://github.com/Mahmud0808/Iconify/assets/103249101/e1c26014-cddb-4d2c-9cf6-e2a24c887443)

It would be nice if we can customize indicator color to be using accent color:
![how should it be](https://github.com/Mahmud0808/Iconify/assets/103249101/3ec03d06-8344-4a68-871c-d696a3e1650a)

**Comment by Mahmud0808** [comment]
It's a side effect of using gradient supported QS tile styles. Even if you are using solid color, it is actually a gradient color with same color on both side. Unfortunately fixing the indicator color means you'll loose ability to use gradient colors. So it won't be happening.
