### ISSUE TITLE
[FEATURE] Add another "stock" brightness bar theme / Add an option to show a sun icon on brightness bar

### ISSUE THREAD

**Issue by gleniu87** [Mahmud0808/Iconify#174]
### Describe the feature

There are a lot of brightness bar styles available in the app, but I'm missing the one slider style that is default in AOSP. Also, user should be able to display a sun icon on brightness bar slider. See screenshots below.

### Why would it be useful to add?

Just another customization option.

### Example(s)

I'm personally missing this brightness slider theme that is the default style in AlphaDroid ROM:
![brightness bar](https://github.com/Mahmud0808/Iconify/assets/103249101/c2b14e15-b748-4fa1-b7ba-27d34078b756)

Also, it would be nice, if there is an option to show a sun icon on brightness slider:
![brightness bar sun icon](https://github.com/Mahmud0808/Iconify/assets/103249101/5d5ddd2b-8750-41e3-ac0b-5fb9c91289b1)

**Comment by Mahmud0808** [comment]
The reason I did not add sun icon in any of the custom brightness bars is because it will be hardcoded and icon packs won't be able to change the icon. So basically that sun icon won't match with rest of the icons' style.

**Comment by EleoXDA** [comment]
Is Alphadroid considered as "stock"?
