### ISSUE TITLE
[FEATURE] Custom font support

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#175]
### Describe the feature

Can you add option to change Android's default font?

### Why would it be useful to add?

AOSP Mods has this feature, but they said that it will no longer be maintained. It would be cool to be sure that someone will fix it if it will be broken. It is also in Android's Themes app, but in LineageOS there are only 4 fonts available.

### Example(s)

![s1](https://github.com/Mahmud0808/Iconify/assets/99012892/d9fe0a0f-928c-4c83-a0c2-a37c21e78820)
![Screenshot_20230529-213532_Tapeta i styl](https://github.com/Mahmud0808/Iconify/assets/99012892/5626260d-73d4-4ecc-befb-497c853d5a36)

### Additional context

https://github.com/siavash79/AOSPMods/issues/627

**Comment by Mahmud0808** [comment]
Do not worry, those fonts shouldn't break any time soon.

Also there are modules to change to any font you want. Example: [MFFM](https://t.me/MFFMMain)
