### ISSUE TITLE
[FEATURE] add semi transparent toast, bigger clock in statusbar & darker transparent heads up notification 

### ISSUE THREAD

**Issue by Alex1kurdin** [Mahmud0808/Iconify#177]
### Describe the feature

Thank you for your wonderful work, please add some features like:
Resize or bigger clock in statusbar, 
Semi-transparent toast, 
Darker heads up notification (in transparent notification)&
Reduce gap between icons and clock in left statusbar.
Good job🙏🏼

### Why would it be useful to add?

All of them help me using my phone to be comfortable and convenient in better way.

### Example(s)

![IMG_20230601_114523](https://github.com/Mahmud0808/Iconify/assets/132998706/d793e124-929e-4f3a-887b-156878be2a37)

**Comment by Mahmud0808** [comment]
The space between clock and notification icon appears only after disabling clock chip. Restarting systemui fixes the issue.

Heads up notification background is currently linked with QS panel notification background. I will check if I can do anything about that.

Edit: Don't know why you want bigger clock as statusbar has no extra space, making it larger will just cut the font.

**Comment by Alex1kurdin** [comment]
Thank you, seems ok now.
Good job bro🙏🏼❤️
