### ISSUE TITLE
[FEATURE] Suport for Mp4 files as header image along with gif and jpg and png

### ISSUE THREAD

**Issue by Man3006** [Mahmud0808/Iconify#178]
### Describe the feature

There is already support for images in header and gifs too....but good gifs are mostly 50-100 mb large and are cumbersome to make...if instead there was support for mp4 video which are only 3-4 mb...it would be lot convient and less taxing on system too

### Why would it be useful to add?

Beacuse its will be less resources taxing than gif and will be convienct for everyone ...and by this way people can also set upto 120hz headers which will be a lot more visually appealing.

### Example(s)

the thing is possible... beacuse if iconify can support images and gifs .. Suporting mp4 ahouldnt be hard too.....

### Additional context

if mp4 support can be done but has some hurdles like not proper cropping mechanism....i suggest u still add because most of the people can crop the videos according to need so app wont have to do cropping or streching.....

features shouldnt be withheld due to some people who dont have skill or knowledge for such procedure

**Comment by Mahmud0808** [comment]
That's gonna be a huge battery consuming feature.
