### ISSUE TITLE
Make the "hide status icon" customisable at the user-end

### ISSUE THREAD

**Issue by altCK129** [Mahmud0808/Iconify#184]
### Describe the feature

There is feature under Xposed menu>others known as "disable status icons" which automatically disables time , date and battery icon from qs panel . It would be really helpful if the icons to be disabled can be choosen by the user .

### Why would it be useful to add?

In Pixel experience particularly which a lot of people use you cant disable the estimated time left of the battery and it takes a lot of space . (Talking about phones with punch hole display) it makes other icons which are much more useful like bt status appear as a dot which is annoying.

### Example(s)

![Screenshot_20230617-044826_Iconify](https://github.com/Mahmud0808/Iconify/assets/86251706/e553514f-f3b0-401b-bfc5-4fa592c08fc6)

### Additional context

.

**Comment by Mahmud0808** [comment]
You can simply disable battery estimate by chaging bool resource with an overlay I guess.

Edit: Hiding only battery icon on QS panel is not possible on A13 QPR2+ roms as it creates more bug.
