### ISSUE TITLE
[FEATURE] Bring back old background color as an option.

### ISSUE THREAD

**Issue by Pop28** [Mahmud0808/Iconify#185]
### Describe the feature

After updating to version 6.20, the quick settings tile background color is much darker. The feature would either give you the option that reverts back to the old/brighter quick settings background color, or let you customize the background color.

### Why would it be useful to add?

The new qs background color is very dark and hard to see when using it with the pitch black theme.

### Example(s)

6.20:
![new](https://github.com/Mahmud0808/Iconify/assets/69476932/b12196ac-8983-4f4f-86c0-376272c0b24a)

Pre-6.20:
![old](https://github.com/Mahmud0808/Iconify/assets/69476932/029790dd-d061-42ee-8058-6cb8fe8b6834)

**Comment by Mahmud0808** [comment]
The old quick settings offstate color took the main accent color, blended it with black and little bit of white to get the colorful look. The downside was that it didn't support monet color, which means changing accent color wouldn't change the offstate color. Everytime you wanted to change the offstate color, you had to re-apply any of the pixel variant options from iconify and it would generate a new color based on the current accent.

This was a headache so now I just made it to always follow a variant of background color. Now it supports monet color and no need of manual interaction to change the color. I don't see a way to make it optional, I would have to revert everything to get the previous color behavior.
