### ISSUE TITLE
 [Cleaning up iconify] 

### ISSUE THREAD

**Issue by desirexel** [Mahmud0808/Iconify#188]
### Describe the feature

Strip down iconify by removing on unused preset and AOSP icons 

### Why would it be useful to add?

AOSP icons are Ugly and add nothing to the app it makes no sense to keep them because all AOSP ROM already have them.

### Example(s)

Useless ugly icon pack 
![Screenshot_20230619-085759](https://github.com/Mahmud0808/Iconify/assets/31364886/4b38ab87-feb7-4554-bbe5-0a21bbb5d2f4)

### Additional context

Thanks

**Comment by chlorospingus** [comment]
I'm assuming the AOSP icons are there for people using ROMs with custom icons like OxygenOS, but would rather use AOSP icons.

**Comment by desirexel** [comment]
No problem 😁
Thanks for replying.

**Comment by Mahmud0808** [comment]
> No problem 😁 Thanks for replying.

We already talked about it on Telegram. Someone's trash might be another's treasure😉

**Comment by desirexel** [comment]
Haha, thanks! .. sure but the objective is for iconify to be completed
differently from what is already available. It's True we've already
discussed this on telegram. Till now I saw no single screen shot with those
ugly aosp icon.
What makes me insist on the need to remove them is that some aosp ROM are
now using iconify icons pack especially Aurora which I adore 🥰 , despite
having their ugly icons..

**Comment by desirexel** [comment]
I also suggested further customisations with the possiblity to edit Qs
tiles but  I know this is hard work

Thanks for being nice with us

**Comment by Mahmud0808** [comment]
> I also suggested further customisations with the possiblity to edit Qs tiles but I know this is hard work Thanks for being nice 

Further customizations like what? Can you be more specific?
