### ISSUE TITLE
Power button is too large and overflows 

### ISSUE THREAD

**Issue by nonetrix** [Mahmud0808/Iconify#19]
**Describe the bug**

**To Reproduce**
1. Enable default quick settings option or any other
2. Open quick settings
3. See power button is too big

**Expected behavior**
Power button isn't clipped, and has reasonable margin around settings like usual when Iconify is not enabled

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS Name: CalyxOS
 - Android Version: Android 13
 - Iconify Version: 1.0-beta

**Additional context**
Display size
![Screenshot_20221120-201423](https://user-images.githubusercontent.com/45698918/202946185-b5bfd325-860f-4014-8c58-d9eac8a94bc5.png)

Issue
![Screenshot_20221120-201033_1](https://user-images.githubusercontent.com/45698918/202946223-ec685470-22b2-49ba-8f71-fe88d1b49c7f.png)

**Comment by Mahmud0808** [comment]
Thanks for the report. Already fixed in internal release. Wait for the next version.
