### ISSUE TITLE
[FEATURE] disable combined qs header "disable qpr2 clock in qs"

### ISSUE THREAD

**Issue by 1Kilany** [Mahmud0808/Iconify#191]
### Describe the feature

flag_combined_qs_headers

### Why would it be useful to add?

Qs lags alot in qpr2 roms due to combined qs header google added 

### Example(s)

https://github.com/Evolution-X/frameworks_base/commit/18e043574438e40fb27dcd51ec88db3005e46c6d
https://github.com/Evolution-X/frameworks_base/commit/c2b943d2c7ddded900141d8fdedbef3e7187eb46

**Comment by Mahmud0808** [comment]
This is a custom boolean resource added in some custom roms which is not even available in AOSP. So I can't add it.
Also changing the flag with xposed doesn't work either.

Workaround:
Enable `Tablet Header` from Tweaks > Miscellaneous along with custom QS/QQS Top Margin. These are available in latest debug. It will remove the header transition animation and reduce lag.
