### ISSUE TITLE
[BUG] Recents menu is not always blurred

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#196]
### Describe the bug

When blur (and Android's gestures) are enabled, recents menu is blurred only when holding the screen. Can you make it blurred always?

### Steps to reproduce

1. Enable transparency and blur
2. Open any app
3. Swipe and hold from bottom to see the recents menu
4. Until the screen is holded, the background is blurred. When releasing, it becomes solid color.

### Expected behavior

It should be always blurred.

### Screenshots

[https://raw.githubusercontent.com/tadekdudek/a/main/v.mp4](https://raw.githubusercontent.com/tadekdudek/a/main/v.mp4)

### Device information

- Device: Redmi Note 7
- OS: LineageOS 20.0 (Android 13)
- App version: 6.2.0

**Comment by Mahmud0808** [comment]
This is launcher related feature. I can't do anything about that. You can flash a custom launcher magisk module instead. Some launchers like CrDroid launcher has blur on recents page.
