### ISSUE TITLE
[BUG] impossible to remove theme

### ISSUE THREAD

**Issue by Aarqw12** [Mahmud0808/Iconify#198]
### Describe the bug

1) I apply theme in iconify app 

2) disable all theme + systemui restart no work 

3) I uninstall iconify app but I see all iconify apk is still in product/overlay { rm -rf is no working I get device or resource busy }

### Expected behavior

All theme is removed

### Device information

- Device: [Google Pixel 6]
- OS: [stock ROM Android version 14 beta 3.1]
- App version: latest stable 

### Additional context

-

**Comment by Mahmud0808** [comment]
Remove the magisk module.

**Comment by Aarqw12** [comment]
> Remove the magisk module.

Ho I'm almost stupid to no verify that
