### ISSUE TITLE
[BUG] Media player options and appearance not changing

### ISSUE THREAD

**Issue by nukiatrics** [Mahmud0808/Iconify#203]
### Describe the bug

This bug has to do with the media player in Android 12. With the color engine settings having the monet accent on, the system monet disabled, and custom colors being used, whenever i try to change any settings for the media player in tweaks, when i exit the category and go back inside media player again, the setting is off again, and there are no changes made to the media player.

### Steps to reproduce

1. Go to 'Media Player'
2. Click on any option
3. Close the 'Media Player' category
4. Go back and see the options turned off
5. Check the media player and see it unchanged

### Expected behavior

I expected the options to be kept on by the app, and to see a change in the media player's look.

### Screenshots

Attaching a screen recording to make the issue clear:

https://github.com/Mahmud0808/Iconify/assets/59058664/7ceec678-9095-42c8-a1da-edba02b9989d

### Device information

- Device: Sony Xperia XA2 Ultra
- OS: LineageOS 19.1
- App version: 6.2.0

**Comment by Mahmud0808** [comment]
Looks like it's working on older versions of android 12.1 but not on latest versions. I will try to find a fix for it.

Edit: Found the silly mistake. Working on a fix.

**Comment by JonathanRMartinezHernandez** [comment]
Hello I am also experiencing this problem, though I don't have a menu to change how the Media Player looks like in the recorded video. I have set colors using the Color Monet Engine and the QS Tiles and Notifications change color but the media player remains the sameWas this menu removed or moved somewhere else? 
 Device: Google Pixel 3a
OS: Android 13
App version: 6.5.0

**Comment by Mahmud0808** [comment]
> Was this menu removed or moved somewhere else?

It is for android 12 and 12L only.
