### ISSUE TITLE
[FEATURE]Always on display edit

### ISSUE THREAD

**Issue by Anto426** [Mahmud0808/Iconify#204]
### Describe the feature

it would be possible to add an option that allows you to modify Always on display.

### Why would it be useful to add?

they would be nice since other ROMs have it

### Example(s)

an example would be to add a custom image to change the clock style or font

### Additional context

.

**Comment by Mokura** [comment]
I haven't tried it much because I'm not a big fan of AOD, but until this issue gets considered or closed you could try this: https://github.com/Domi04151309/AlwaysOn (GNU GPL3)

**Comment by Mahmud0808** [comment]
My device has LCD display and no AOD 🙂

Edit: As iconify custom lockscreen clocks are already shown on AOD, I think that counts as AOD customization. Moreover I don't have a device with AOD, so can't help much. Hence closing this issue.
