### ISSUE TITLE
[BUG] Hidden status icons when privacy chip is shown

### ISSUE THREAD

**Issue by Undisputed00x** [Mahmud0808/Iconify#206]
### Describe the bug

Status bar icons only on QS panel (not extended) are hidden when privacy chip is shown after app launches e.g camera app.
When QS is extended status bar icons are correctly displayed.

### Steps to reproduce

Tried to disabled both **backround chip** and **accented privacy chip** which i use but the problem still persists.

### Expected behavior

Status bar icons should be diplayed like in the extended QS screenshot

### Screenshots

![Screenshot_20230705-180905_Camera](https://github.com/Mahmud0808/Iconify/assets/80290008/5e47978d-e056-4896-aaa4-fb4c7dfcf4ae)
![Screenshot_20230705-180850_Camera](https://github.com/Mahmud0808/Iconify/assets/80290008/a8b38f88-8b44-4159-9c1a-ae77d41e1490)

### Device information

- Device: Poco X3 Pro
- OS: Android 12.1 - LOS19.1
- App version: v6.2.0 latest debug build

**Comment by Mahmud0808** [comment]
This is not a bug, rather an intended behavior from google. It's made such that whenever privacy chip is shown, other icons are removed from QQS panel for a few seconds. Although I could make the icon background chip disappear too, but didn't want to go through the trouble as android 14 is here so older android versions aren't a priority right now.

**Comment by Undisputed00x** [comment]
Issue gets closed
