### ISSUE TITLE
[BUG] Colors/Backround theme bugs after changes

### ISSUE THREAD

**Issue by Undisputed00x** [Mahmud0808/Iconify#207]
### Describe the bug

(1st Bug) When make a change on Xposed-depend settings (e.g backround chip theme) where either SystemUI or double toggle dark theme method is applied , both monet engine colors get broken and the pitch black backround gets dark (not black)
The fix to this is to reapply the custom colors in monet engine but it leads to 2nd bug ...

(2nd Bug) When there is a change on monet's engine colors pitch black backround gets disabled with the switch still being enabled.
The fix to this is to disable and enable again the pitch black backround setting

### Steps to reproduce

**[1st BUG]** Steps to reproduce the behavior:
1. Go to 'Backround chip setting.'
2. Click on 'Status Icon chip switch'

**[2nd BUG]** Steps to reproduce the behavior:
1. Go to 'Color Engine'
2. Click on 'Monet Engine'
3. Click on 'Change color'

### Expected behavior

[1nd BUG] After a change in Xposed depend settings , custom theme should be remain intact

[2nd BUG] After a change of Monet engine colors , pitch black backround should be reapplied (if previously enabled)

### Screenshots

[1st BUG] https://imgur.com/a/7ZWGlj5
[2nd BUG] https://imgur.com/a/66dOdEM
[Correct visuals] https://imgur.com/a/Y5PF2lc

### Device information

- Device: Poco X3 Pro
- OS: LOS 19.1 - Android 12.1
- App version: v6.2.0 latest debug build

**Comment by Mahmud0808** [comment]
Did you enable the "Disable System Monet" button? If that is not enabled, your system's default monet will replace the colors.

Edit: Found the issue with monet engine. Thanks for notifying.

**Comment by Undisputed00x** [comment]
Enabling "Disable System Monet" did bring some good results for the 1st bug but it didnt fix the colors in chip backround, now simply only by disabling/enabling monet accent can fix that (no need to change colors)
https://imgur.com/a/QFfZJIV
https://imgur.com/a/tDLLfl8
[Correct visuals] https://imgur.com/a/Y5PF2lc

The 2nd bug still persists, also another issue (should i open a new issue ?) i found out is that fixed status icons setting is quite buggy for example after SysUI restart it disappears , by disabling/enabling the button it appears but without its correct colored theme like on the 2nd screenshot and to fix that again i have to disable/enable either monet accent or change colors in monet engine

**Comment by Mahmud0808** [comment]
Fixed status icons is done by very dirty trick. Literally removing a view from one layout and moving it to another layout all in xposed. So I know it might be buggy time to time. I recommend not to use both status icons chip and fixed status icons at the same time. Then it will be less buggy.
