### ISSUE TITLE
[FEATURE] Optimise UI for tablet

### ISSUE THREAD

**Issue by DeepBlueBubble** [Mahmud0808/Iconify#209]
### Describe the feature

Hi, on tablet, the UI of iconify is, I would said, huge. It is inconvenience to use. 

### Why would it be useful to add?

optimise the UI on tablet for better use

### Example(s)

Maybe reduce the scale of the UI?
or add two column to it

**Comment by Mahmud0808** [comment]
Can you provide some screenshots please?

**Comment by DeepBlueBubble** [comment]
this how it looks like in tablet 
![Screenshot_20230709-015530_Trebuchet](https://github.com/Mahmud0808/Iconify/assets/48380097/f01d050e-8aac-4b6c-bcb8-1ca1baf08739)
![Screenshot_20230709-015522_Trebuchet](https://github.com/Mahmud0808/Iconify/assets/48380097/8552fa3e-0622-41d6-b8de-6ccbcad09723)
![Screenshot_20230709-015518_Trebuchet](https://github.com/Mahmud0808/Iconify/assets/48380097/ed08fa8f-f70f-44c0-a07a-30c63b25bf87)
![Screenshot_20230709-015206_Iconify](https://github.com/Mahmud0808/Iconify/assets/48380097/02fcda6c-ef5b-4d5e-a8be-2e0b458f645e)

**Comment by Mahmud0808** [comment]
Let me know if the latest debug improved for you or not.

**Comment by DeepBlueBubble** [comment]
Just tried the new debug build. Yes now the UI is much comfortable. Thank you.
