### ISSUE TITLE
Can't applied Qs tiles

### ISSUE THREAD

**Issue by Whyamd** [Mahmud0808/Iconify#21]
![Screenshot_20221122-075037_PowerTube](https://user-images.githubusercontent.com/118781975/203187729-24ca9bc0-d96f-487c-92d4-aaac6bdcb0f9.png)
**Can't applied Qs panel tiles **

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: _[Asus xootd]_
 - OS Name: _[ricedroid v5]_
 - Android Version: _[android 12.1]_
 - Iconify Version: _[v2.0-Beta]_

**Additional context**

**Comment by Mahmud0808** [comment]
Provide systemui.apk if possible from system/system_ext/priv-app folder. I will look into it.

**Comment by gitaccount88** [comment]
> Provide systemui.apk if possible from system/system_ext/priv-app folder. I will look into it.

I am also facing the problem (same custom rom)
Device - Realme 8i
Rom - Ricedroid 5
Android - 12.1
Iconify Version - 3.0 beta

attached systemui.apk
[SystemUI.zip](https://github.com/Mahmud0808/Iconify/files/10095734/SystemUI.zip)

![Screenshot_20221126-110527_Iconify](https://user-images.githubusercontent.com/98384804/204074280-bd1ab537-135c-414f-9953-5119770101f4.png)
![Screenshot_20221126-110530_Iconify](https://user-images.githubusercontent.com/98384804/204074281-99b4093c-98f9-49c6-a4f0-abd661f684f8.png)
