### ISSUE TITLE
[BUG] Slight cutoff of notification bar when using Custom Header Clock on landscape layout of tablet

### ISSUE THREAD

**Issue by SMOLKEYS** [Mahmud0808/Iconify#211]
### Describe the bug

Whenever I have the Custom Header Clock enabled, the highest notification in the notification panel gets cut off slightly.

Nothing critical, but is quite inconvenient.

(see screenshot)

### Steps to reproduce

1. Go to Xposed Menu
2. Go to Header Clock
3. Enable it
4. Look at the notification panel

### Expected behavior

The clock being applied normally, with no cutoff of the highest notification.

### Screenshots

With custom header clock:
![Screenshot_20230707-114154_Iconify](https://github.com/Mahmud0808/Iconify/assets/75618732/debdabae-e6ce-4f3c-86ee-620cf5b5fd3e)
 

Without custom header clock:
![Screenshot_20230707-114220_Iconify](https://github.com/Mahmud0808/Iconify/assets/75618732/07dbcbcf-06d8-4635-acc3-1b479deea26b)

### Device information

- Device: Samsung Galaxy Tab A8 | SM-X205 variant
- OS: LineageOS 20.0 (Android 13) TrebleDroid (June build, arm64 bgN variant)
- App version: v6.3.0 FDroid

**Comment by Mahmud0808** [comment]
Thank you for notifying. I think it's a side effect of removing default clock. I will see if it can be fixed somehow.
