### ISSUE TITLE
[BUG] QS landscape mode glitched

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#212]
### Describe the bug

The new option "Tablet landscape" looks very buggy and glitched on my phone when enabled.

### Steps to reproduce

1. Go to Miscellaneous
2. Click on Tablet landscape 
3. Start landscape mode on ur phone 

### Expected behavior

The QS should look like on the Pixel tablet. It's just beautiful like that on landscape mode!

### Screenshots

![Screenshot_20230707-141310](https://github.com/Mahmud0808/Iconify/assets/90862487/3ba8890f-14a7-48b0-a0bf-d862cb24e03b)

### Device information

- Device: Huawei p20 lite 
- OS: LeaOS PHH, AOSP 13 Rom with Huawei patches.
- App version: 6.3.0

**Comment by Mahmud0808** [comment]
Try not using custom Header Clock. It's not compatible with Tablet Landscape. And also enable notch bar killer as it's necessary to properly show tablet landscape.

**Comment by JesusChapman** [comment]
> Try not using custom Header Clock. It's not compatible with Tablet Landscape. And also enable notch bar killer as it's necessary to properly show tablet landscape.

It worked for me, and I find the tablet interface more comfortable that way. But he still has things to correct.

I'll be waiting when the problem has been fixed.
