### ISSUE TITLE
[BUG] Header image overlapping

### ISSUE THREAD

**Issue by Uns0lved** [Mahmud0808/Iconify#215]
### Describe the bug

Why is it that when I try to place any image, it is on top of other tiles? How can I fix it?

### Steps to reproduce

1. Open header image menu.
2. Pick up any image and enable it.
3. See error.

### Expected behavior

The image behind other tiles.

### Screenshots

![Screenshot_20230708-023729_Iconify](https://github.com/Mahmud0808/Iconify/assets/55342617/c8250384-7f04-4b4c-a571-8e08c20edb53)

### Device information

- Device: Xiaomi Mi 10T Pro(apollo)
- OS: Any AOSP 13 Android
- App version: 6.3.1, 6.3.0, 6.2.0

**Comment by Mahmud0808** [comment]
Resolved [here](https://github.com/Mahmud0808/Iconify/commit/179f3f084f3eaa2608360a213d2c739045e2a245)
