### ISSUE TITLE
[FEATURE] add Spanish language 

### ISSUE THREAD

**Issue by JesusChapman** [Mahmud0808/Iconify#216]
### Describe the feature

It would be nice if the app also had a Spanish translation, although I'll see if I learn a little more to do it myself, but I'm not committing to anything at the moment.

### Why would it be useful to add?

.

### Example(s)

.

**Comment by JesusChapman** [comment]
Oh, I think I already saw how to add the language, I'll see if I get to work later

**Comment by Mahmud0808** [comment]
> Oh, I think I already saw how to add the language, I'll see if I get to work later

Create a pull request, I will review and merge.
