### ISSUE TITLE
[FEATURE] Please, add an option to move QS brightness bar to the bottom

### ISSUE THREAD

**Issue by Username1-a** [Mahmud0808/Iconify#217]
### Describe the feature

Please, if it's possible, add an option to move QS brightness bar to the bottom and/or to Quick QS. 
The thing is while AOSP Mods has that option, it's buggy and broken ever since A12 – after some time brightness bar just changes it's position back to the top and has weird padding around it (like shown in the examples). 
Maybe Iconify solution could've been more reliable 

### Why would it be useful to add?

More accessible and faster way of changing brightness level

### Example(s)

![Screenshot_20230708-062836_Chrome~2](https://github.com/Mahmud0808/Iconify/assets/47947180/3ec53f5d-fde9-48c6-908d-7a4707a2ecd9)
[screen-20230708-063811(3).zip](https://github.com/Mahmud0808/Iconify/files/11987580/screen-20230708-063811.3.zip)

### Additional context

OS version: Android 13 QPR2, PE custom ROM
App version: 6.3.1

**Comment by tadekdudek** [comment]
On LineageOS 20.0 it works well and is stable.

**Comment by Mahmud0808** [comment]
> Maybe Iconify solution could've been more reliable

I don't know about that statement. I still heavily rely on aospmods to learn xposed hooks.

Edit: No plan to add that, use [PixelXpert](https://github.com/siavash79/PixelXpert) instead.
