### ISSUE TITLE
[FEATURE] Config import and export

### ISSUE THREAD

**Issue by mizzunet** [Mahmud0808/Iconify#218]
### Describe the feature

Add ability to import and export Iconify config.

### Why would it be useful to add?

* to share config in community
* helps debugging
* helps disabling any tweaks temporarily, so it can be enabled back at once by importing the config

### Example(s)

Something as follows,
```
icon_pack=plumpy
icon_settings=plumpy
brightness_bat=rounded_bar
```

### Additional context

Thanks

**Comment by Mahmud0808** [comment]
https://github.com/Mahmud0808/Iconify/commit/fb3849346fb0fc80ec2500e29c633c4777741c99
