### ISSUE TITLE
[BUG] Brightness slider is behind the QS header image

### ISSUE THREAD

**Issue by icewyvrn** [Mahmud0808/Iconify#221]
### Describe the bug

When qs header image is enabled, the brightness slider is hidden behind the image.

### Steps to reproduce

Enable QS Header image.

### Expected behavior

Brightness slider should be at the front of the image.

### Device information

- Device: Xiaomi Lisa
- OS: LineageOS 20
- App version: v6.3.1

**Comment by Mahmud0808** [comment]
https://github.com/Mahmud0808/Iconify/commit/179f3f084f3eaa2608360a213d2c739045e2a245

**Comment by icewyvrn** [comment]
Is that fix in the latest version?

**Comment by Mahmud0808** [comment]
> Is that fix in the latest version?

It's in debug builds for now.
