### ISSUE TITLE
Fastlane changelogs are too long

### ISSUE THREAD

**Issue by IzzySoft** [Mahmud0808/Iconify#222]
### Describe the bug

Fastlane changelogs are limited to 500 char each. Your last 2 for `en-US` exceed that. Please make sure to stay within :wink: Thanks!

### Steps to reproduce

take a look and count the chars :wink:

### Expected behavior

max 500 char

### Device information

n/a

**Comment by Mahmud0808** [comment]
Noted.

![crying](https://github.com/Mahmud0808/Iconify/assets/29881338/dad73b7b-1656-4714-b1ea-8a63561537ba)

**Comment by IzzySoft** [comment]
Happened again, @Mahmud0808: `en-US/changelogs/15.txt` has 556 chars …

**Comment by HiFIi** [comment]
:O

**Comment by Mahmud0808** [comment]
> Happened again, @Mahmud0808: `en-US/changelogs/15.txt` has 556 chars …

Can you do something like it will cut off the extra texts when it exceeds limit?

**Comment by IzzySoft** [comment]
It will be cut off mid-word. But that's the result to be avoided, hence my monthly checker reports such cases. It's Fastlane definition they should be max 500 chars, not mine. And fdroidserver sticks to that.

Looking at yours, and what could be removed:

* trailing empty lines (no content anyway)
* the "Full changelog" line (the "Changelog" link on app level already covers that)

Et voila: 499 chars on `15.txt`.

**Comment by Mahmud0808** [comment]
Pain. I'll be more careful in future lol.

**Comment by IzzySoft** [comment]
Thanks, Mahmud!

**Comment by Mahmud0808** [comment]
> Thanks, Mahmud!

Btw I have one more request. I want to add iconify on f-droid too. How do I proceed with it? Can I use fastlane structure or do f-droid need different structure? Can you please help me a little about it?

**Comment by IzzySoft** [comment]
Glad to answer that: Yes, the very same fastlane structure works there. And as for "how to…", some short hints can be found in my snippet under [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid). If you need more details, just let me know!

**Comment by Mahmud0808** [comment]
Thanks that helps.

> If you need more details, just let me know!

That would be even more helpful for me. I read the f-droid contribution to add an app but I am still a little bit confused about it.

**Comment by IzzySoft** [comment]
> I read the f-droid contribution to add an app but I am still a little bit confused about it.

Thought so, which is why I gave you that link. If it's your first time, the F-Droid documentation is easily misread as you'd have to do it all on your own, including setting up F-Droid's build server (sure that would make it easier for the F-Droid team which I'm a member of, but it's not a strict requirement). If you want more "prosa", the RFP part is also covered in [my article here](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp) (4 years old, but the basics still hold true – and the part about screenshots etc you have already covered with Fastlane).

Btw: "if you need more details" means specific questions where you e.g. got stuck, not just "tell me to talk more" :stuck_out_tongue_winking_eye: So if there are questions left after you've read that… :wink:
