### ISSUE TITLE
Window panel/notification panel transparency

### ISSUE THREAD

**Issue by jahidulll** [Mahmud0808/Iconify#225]
### Describe the feature

Notification The place where ISA is deposited should be transparent

### Why would it be useful to add?

The notification panel area is transparent and looks gorgeous.  After asking for help on this in the group, I saw many people who also wanted the notification location to be a trans point
![Screenshot_20230722-174543_Evolution X Launcher](https://github.com/Mahmud0808/Iconify/assets/120808605/fac8eed0-a3c3-4b7c-810c-0d1e9f8b53c5)
![Screenshot_20230722-174543_Evolution X Launcher~2](https://github.com/Mahmud0808/Iconify/assets/120808605/96c85e39-82ff-4067-ab0a-c640b1e78f62)

### Example(s)

![Screenshot_20230722-174543_Evolution X Launcher~2](https://github.com/Mahmud0808/Iconify/assets/120808605/84a6a8a7-85fe-4bd1-902e-148d44aad856)

### Additional context

This room runs I have a lot of fun it's much better than other rooms it's good in every aspect only this place

**Comment by Mahmud0808** [comment]
This has already been added
https://t.me/IconifyOfficial/149
https://t.me/IconifyOfficial/155
