### ISSUE TITLE
[FEATURE] Orientation depended settings

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#226]
### Describe the feature

Some tweaks, mostly these related to the statusbar and QS panel should depend on screen orientation.

### Why would it be useful to add?

Less space means the need of diffrent layout. In vertical orientation, I would prefer to have more rows of QS tiles, but in the horizontal mode (especially when the Better QS option is enabled) everyone would want less of them.

### Example(s)

![Screenshot1](https://github.com/Mahmud0808/Iconify/assets/99012892/bab9b09b-7928-4842-acb5-ab4eddfa9252)

![Screenshot2](https://github.com/Mahmud0808/Iconify/assets/99012892/45ed8ece-ae0f-4b4b-8b81-9fa6054f9ed5)

### Additional context

Currently, it is the only reason because of what I'm using AOSP Mods.

These tweaks should be depended on orientation in my opinion:
 - QS panel tiles count
 - QS panel tiles size
 - Statusbar padding
 - Notch bar killer
 - Tablet header
 - Vertical QS tiles
 - Battery icon width, height and margin
 - QS header clock settings
 - Hide carrier group
 - Hide status icons

**Comment by Mahmud0808** [comment]
Some of the features you mentioned need a systemui restart to apply effect properly. These can not be made orientation dependent. For the rest, I'll consider and check if they are possible or not.
