### ISSUE TITLE
Option to Move QS Icons up

### ISSUE THREAD

**Issue by snoweuph** [Mahmud0808/Iconify#23]
**Is your feature request related to a problem? Please describe.**
Yes, if setting qs collum to 3, the text is cutoff

**Describe the solution you'd like**
Toggle to move qs icons on top of their text

**Describe alternatives you've considered**
Aosp mods module, but only works from time to time.

**Additional context**
![Screenshot_20221123-061345_GitHub.png](https://user-images.githubusercontent.com/76737863/203473272-b9bf6769-d990-4264-b844-e91a97d107e6.png)![Screenshot_20221123-061341_GitHub.png](https://user-images.githubusercontent.com/76737863/203473283-291377e3-20e9-4311-aad3-87474303b38d.png)

**Comment by snoweuph** [comment]
Images are what it looks like if it works with aosp mods

**Comment by Mahmud0808** [comment]
I don't think it is possible without the integration of xposed module. But I will look into it.

**Comment by akmsk1999** [comment]
Statusbar and QS Transparency also requires Lsposed integration.... Posted an feature request of it...

**Comment by snoweuph** [comment]
ahh okay
