### ISSUE TITLE
[FEATURE] Lock screen depth effect 

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#230]
### Describe the feature

The lock screen clock (especially with the custom iconify designs and custom fonts) would be awesome if there was a depth feature like in iOS. A twitter user made a concept and that gave me idea... Maybe iconify can implement it.

### Why would it be useful to add?

It would look extremely good and would make iconify even better as a professional way of modifying android. It would add so much character to the phones.

### Example(s)

![20230727_120034](https://github.com/Mahmud0808/Iconify/assets/90862487/05ccb6bb-c60e-4e12-8e83-7f680e5c1272)
![20230727_120046](https://github.com/Mahmud0808/Iconify/assets/90862487/d674a2c6-81de-406c-9070-89e7f61320cb)

### Additional context

It would be awesome, but it's also hard to implement I think. A nice idea is maybe a very light in-app editor of adding 2 images (one at bottom, one over clock but under shortcuts and text). The editor is only there to move the images in the right direction.The 2 images should be created by the user tho. For example: I cut the dog out of my image and save it. Then I go to iconify and place the image of only the dog on top of the real full image. And then the dog of my image is over the clock. I hope i explained it somehow understandable.

Can this be implemented with e.h. lsposed? The best would be if it would be integrated natively somehow (I don't know if it's possible). Because it wouldn't be nice if it would be like some apps using accessibility settings and just overlapping over everything and looking buggy.

**Comment by Mahmud0808** [comment]
Will consider.

Edit: This is indeed possible and not that much hard. But it's a bit buggy in some cases like pulling down QS on lockscreen or single tapping lockscreen.

**Comment by gaussandhisgun** [comment]
Or, you can just set Iconify to no lockscreen clock, and use KLWP to do this.

**Comment by srt54558** [comment]
> Or, you can just set Iconify to no lockscreen clock, and use KLWP to do this.

Its not native. Like swiping to enter the pin will look horrible
