### ISSUE TITLE
[FEATURE] Always white option for volume panel

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#237]
### Describe the feature

An option to force volume panel icons to be white.

### Why would it be useful to add?

Sometimes volume panel nas similar issue like QS tiles (nothing is visible, dark background).

### Example(s)

![Screenshot_20230729-232646_Iconify](https://github.com/Mahmud0808/Iconify/assets/99012892/6c82a4f9-568b-438a-86fd-c12dede498ab)

**Comment by Mahmud0808** [comment]
Use the last text color fix option.
