### ISSUE TITLE
[BUG] iOS 16 battery icon issue

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#238]
### Describe the bug

The iOS 16 battery icon does not look right when QS panel is expanded.

### Steps to reproduce

1. Enable iOS 16 battery icon
2. Expand QS panel

### Expected behavior

The battery icon's value should be same as the precentage is. Look at the screenshots.

### Screenshots

![Screenshot_20230730-175400_Iconify](https://github.com/Mahmud0808/Iconify/assets/99012892/4b367e9e-0b7b-47e9-bdad-fdc9263a6b65)
![Screenshot_20230730-175349_Iconify](https://github.com/Mahmud0808/Iconify/assets/99012892/f199083b-4d0e-4f96-b743-31f937a78ee9)

### Device information

- Device: Redmi note 7
- OS: LineageOS 20.0
- App version: v6.4.0

**Comment by Mahmud0808** [comment]
This is not a bug from iconify. It's a bug from android side. Although it can be fixed I think, I will give it a try when I have enough free time.

Fixed https://github.com/Mahmud0808/Iconify/commit/ae35fd3e50353a8ddbe0984e92f3ecd486324e50
