### ISSUE TITLE
[BUG] Modifying corner radius does not work everywhere

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#239]
### Describe the bug

Like in title. In some places (for example in the camera unlock dialog) this settings isn't applied.

### Steps to reproduce

1. Change default corner radius value
2. Disable camera access
3. Launch camera app
4. The unlock camera dialog will have one button more rounded than the second one

### Expected behavior

It should apply in every place in Android

### Screenshots

![screenshot1](https://github.com/Mahmud0808/Iconify/assets/99012892/8b9087e5-7f69-4696-92d7-ac3e5f3a1434)

### Device information

- Device: Redmi Note 7
- OS: LineageOS 20.0 - Android 13
- App version: 6.4.0

**Comment by Mahmud0808** [comment]
It's hardcoded, so it doesn't change. It can be changed only by changing the whole button style.
