### ISSUE TITLE
Statusbar and QS panel Transparency and blur

### ISSUE THREAD

**Issue by akmsk1999** [Mahmud0808/Iconify#24]
Please add statusbar and qs transparency(opacity) and blur option
![Screenshot_20221125-154201_Plus](https://user-images.githubusercontent.com/16622098/203950331-94ae20d9-7684-4081-ac09-3b880d6afc8b.png)
![Screenshot_20221125-154212_Plus](https://user-images.githubusercontent.com/16622098/203950356-7f26ef72-98e2-45b7-88f5-c5d3fc8fe268.png)
![Screenshot_20221125-154236_Plus](https://user-images.githubusercontent.com/16622098/203950362-03f6490e-1a64-4e88-9741-c29d4aac45cd.png)

**Comment by akmsk1999** [comment]
https://github.com/AsyJAIZ/Notification-Shade-Transparency

Alternative solution... Though it doesnt have option for changing opacity level 
And Doesn't support QS panel

This requires lsposed integration

**Comment by Mahmud0808** [comment]
Currently there isn't any plan to integrate lsposed module. But I will look into it.
