### ISSUE TITLE
Adding color luminance/ saturation and background color brightness option for native monet colors

### ISSUE THREAD

**Issue by Fly-hunter** [Mahmud0808/Iconify#241]
### Describe the feature

I suggest adding color luminance option and background color brightness for better dynamic themes managements , such feature already exist in crdroid and evox roms , can you bring them to others bro

### Why would it be useful to add?

It will bring a better management for the dynamic colors system

### Example(s)

![images](https://github.com/Mahmud0808/Iconify/assets/135798684/fd05d440-e34d-495a-98fb-02793f10d3fd)
The brightness option and background brightness / heat degree also exist in repainter app , this will be good adding them to iconify

**Comment by Mahmud0808** [comment]
Checked commits, looks like a bit complicated to do through xposed hook. Maybe will do someday when I have enough knowledge about it.

**Comment by Mahmud0808** [comment]
Done in [ColorBlendr](https://github.com/Mahmud0808/ColorBlendr)
