### ISSUE TITLE
[BUG] Tablet Mode Enabled

### ISSUE THREAD

**Issue by jacobchins** [Mahmud0808/Iconify#245]
### Describe the bug

I selected a color palette from the default settings after disabling the system settings on Android 14 and now my phone is stuck in a tablet-like layout, even after rebooting, unlocking the system palette picked, and disabling the module. I have also changed the scaling settings in display and minimum width, neither working. 
![Screenshot_20230817-203236](https://github.com/Mahmud0808/Iconify/assets/18519494/58f9fa41-7066-4fb3-8b30-b95fe0dbef47)

### Expected behavior

Tablet Mode forced

### Device information

- Device: Pixel Fold 
- OS: Stock
- App version: Android 14

**Comment by Mahmud0808** [comment]
This doesn't seem like an issue caused by iconify as iconify in no way changes your screen dpi. Go to developer settings of your rom and lower the value of DPI/Minimum Display Width (I don't remember exactly what the option is named). That should fix your issue.

Edit: Afaik pixel fold shows tablet UI by default. I might be wrong though.

**Comment by jacobchins** [comment]
It isn't an issue directly tied to Iconify, but disabling system color palettes no longer removes the color palettes from the system settings, and wanted to make sure the developer is aware that disabling them in the system settings should be a priority as Android 14 is rolling out soon. Minimum width and screen scaling were my first two options, which did not solve the problem. I set the minimum width to being very low (zoomed in), re-enabled system palettes, disabled Iconify, rebooted, and it seems to have fixed the issue. I have since enabled Iconify & disabled system palettes again and things are back to normal. The Pixel Fold doesn't use tablet UI, it uses it's own custom internal screen DPI and scaling for apps enabled.

**Comment by Nobody9090** [comment]
I can absolutely verify these findings. I had to do the same thing. It really did come down to this app.

**Comment by Mahmud0808** [comment]
> I can absolutely verify these findings. I had to do the same thing. It really did come down to this app.

Create a new issue with clear details. OP's issue was already solved.

**Comment by HiFIi** [comment]
Why are people blaming the app for things it's quite literally unable to do? Lol

**Comment by Nobody9090** [comment]
> Why are people blaming the app for things it's quite literally unable to do? Lol

Because if I have the same exact issue, with the same resolution, then its a repeatable issue.

**Comment by Nobody9090** [comment]
> > I can absolutely verify these findings. I had to do the same thing. It really did come down to this app.
> 
> Create a new issue with clear details. OP's issue was already solved.

I take fault for not grabbing a logcat, that's on me. But to be fair, it was a bit weird. I know without a log, there's not much you can do. However, having to undo some settings then reboot and re-enable is not the greatest "solution". I can't really create a new issue as I have nothing to give you to even help you. Again that's on me. I would however possibly say "If this happens, again to anyone, please grab logs."
