### ISSUE TITLE
iconify

### ISSUE THREAD

**Issue by herkoloay** [Mahmud0808/Iconify#25]
This bug happen also with the previous version of iconify..

whenever I change Qshape Style . it was immediately got blank and when try to restart .. I got bootloop..
Sorry I cant provide u with any Screenshot/vid record because it got blank..

btw my device Poco x3 Pro ( Vayu ) 
Rom : DerpFest a12 ( latest version )

Bad english sorry :)

**Comment by Mahmud0808** [comment]
Provide logs if possible. The logs are saved in data/system/dropbox with title "system_app_crash@....". Some of them might be blank/empty file, so you will have to look for it.
