### ISSUE TITLE
[FEATURE]"ABOUT PHONE" settings icon

### ISSUE THREAD

**Issue by allday5850** [Mahmud0808/Iconify#250]
### Describe the feature

I wouldn't even call this a feature request but I also didn't want to open a new bug report because I feel like it isn't as simple as it should be to solve this. Anyways when theming the settings icons on my Pixel 6 Android 13 QPR3,  all icons are themed but one-- About Phone. It sticks out like a sore thumb. Sometimes there is also the "Tips and Support" icon isn't themed either, but it seems to have been included more recently.  Anyways I've noticed this has been an ongoing issue not just with Iconify, but also some Substratum themes. That is why I say it must not be an easy fix. But I also don't know what I'm talking about so I could be wrong.  So as far as resources go, they must not be located in any System UI overlay or Android System overlay. Nor Settings for that matter because they're regularly left unthemed. The only themes I've seen that do cover the ones I'm talking about are Iris Subs and Liv. 

### Why would it be useful to add?

Because when I see just one or two icons left unthemed, it makes me want to literally do a systemless uninstall of whatever app or service that is the culprit.  But I guess there's no way to uninstall "About Phone" , is there

### Example(s)

![Screenshot_20230822-155228](https://github.com/Mahmud0808/Iconify/assets/51069235/746de0ff-19a4-486f-8690-4a962df626fd)

**Comment by Mahmud0808** [comment]
Did you try the debug versions? https://github.com/Mahmud0808/Iconify/commit/a8c41436eaa94fe21f45c3c01def760396bb5552

**Comment by allday5850** [comment]
Oh wow, usually I do my due diligence before I open a request.  I thot I was on debug version this whole time.  But I got black screen issue from unrelated module last month and couldn't recover from it so I reset phone and somehow got back on release version. Sorry to waste your time
