### ISSUE TITLE
[FEATURE] Option to hide lock icon

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#251]
### Describe the feature

Can you add option to remove the lock icon on lockscreen?

### Why would it be useful to add?

It would be useful if someone want to move notifications on lockscreen to bottom. One unnecessary icon less means more space for notifications.

### Example(s)

![image1](https://github.com/Mahmud0808/Iconify/assets/99012892/f64580ac-3b0f-4720-9d5e-63afec6803aa)

**Comment by BTD684** [comment]
Actually how about adding selectable styles 
Lol with this thing ppl are gonna turn their Android into an iPhone

**Comment by Mahmud0808** [comment]
Added 641521302b994a0690387acdcfca4f7fa5fd32c8
