### ISSUE TITLE
[BUG] nothing is changing in oos 13.1 

### ISSUE THREAD

**Issue by VergilTG** [Mahmud0808/Iconify#252]
### Describe the bug

Just installed the apk and rebooted but nothing's changed except the dark theme

### Expected behavior

Expected to change after rebooting 

### Screenshots

![Uploading Screenshot_2023-08-23-14-56-53-30_b10a9e538c2ad0c5c866dd015b3a149f.jpg…]()

### Device information

- Device: [OnePlus 8 5g USA ]
- OS: [e.g. stock ROM Android version 13]
- App version: [e.g. v4.0-Beta]

**Comment by Mahmud0808** [comment]
Read [FAQ](https://github.com/Mahmud0808/Iconify#-faq)
Also, current latest version is v6.4.0

**Comment by VergilTG** [comment]
Does it work on only android 12 🙄 . Saw android 12+ that's y

**Comment by Mahmud0808** [comment]
> - Which devices does Iconify support?
>   - Iconify exclusively supports stock Pixel or custom AOSP ROMs. It does not support other OEMs such as MIUI, OneUI, ColorOS, NothingOS, MotoUI, etc.
> - Is Android "X" supported?
>   - Iconify officially supports Android 12 and later versions. Compatibility with earlier Android versions is not provided, and there are no plans to introduce support for those versions.

**Comment by VergilTG** [comment]
I saw oos somewhere mybe from another project my fault
