### ISSUE TITLE
[FEATURE] Pitch Black

### ISSUE THREAD

**Issue by TeaqariaWTF** [Mahmud0808/Iconify#253]
### Describe the feature

Is it possible for inactive options to have black in the gray area at the edge.

![Screenshot_20230823-131603_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/90970076/b87610f8-8888-493d-bb38-7ab7551b69ce)

### Why would it be useful to add?

A better view can be obtained

### Example(s)

I can show this as an example, but this also requires the white part to be removed.

![Screenshot_20230823-131912_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/90970076/c41a5db4-0e57-479c-b26b-47afcbd67107)

**Comment by Mahmud0808** [comment]
The style in the second picture wasn't intended. First one is more accessibility friendly. So I don't have plan to change that.
