### ISSUE TITLE
System UI still restarts after boot after disabling the customizations and uninstalling the app.

### ISSUE THREAD

**Issue by th3me** [Mahmud0808/Iconify#255]
### Describe the bug

System UI continues to restart after boot even after disabling everything and uninstalling the app. If i renable the "Restart SystemUI after boot" option it restarts twice.

### Steps to reproduce

I believe i uninstalled the app without disabling the modifications first and rebooted.

### Expected behavior

The app should have a dedicated section in the settings to clean everything up in case of malfunctioning or uninstallation.

### Screenshots

I will provide videos of rebooting with the "Restart SystemUI after boot" setting on and off if neccessary.

### Device information

- Device: OnePlus 7T
- OS: Lineage OS 20 (Android 13)
- App version: 6.4.0 Stable

**Comment by Mahmud0808** [comment]
Did you remove the module? Both Iconify and IconifyCompanion.

**Comment by th3me** [comment]
Yes, i found out about the module after i noticed the issue and removed it. No luck.

**Comment by Mahmud0808** [comment]
Iconify can't do anything if it doesn't even exist on your phone. It's a systemless module. So it's something else that's causing your issue.

**Comment by th3me** [comment]
Yeah sorry, it was actually a immersive gestures module i had without issues for a long time so i figured it would be okay.
