### ISSUE TITLE
[BUG] Changing QS panel top margin does not affect clock

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#256]
### Describe the bug

Changing QS panel top margin affects everything under brightness bar.

### Steps to reproduce

1. Change QS panel top margin, for example to 40dp
2. Expand QS
3. The clock and expanded statusbar are not moved, unlike everything under brightness bar.

### Expected behavior

It should affect everything, including the clock and expanded statusbar

### Screenshots

![Screenshot_20230825-135902_Trebuchet](https://github.com/Mahmud0808/Iconify/assets/99012892/3da186db-b9b4-4d7f-844b-9d3fadd1f6f3)

### Device information

- Device: Redmi Note 7
- OS: LineageOS 20.0
- App version: 6.4.0

### Additional context

I'm not sure if it is not a bug, but an expected behavior. If so, can you add a separate option to change the clock's top margin?

**Comment by Mahmud0808** [comment]
This is not a bug, that's why it's named `QS Top Margin` and not `Header Top Margin`.
