### ISSUE TITLE
Recents

### ISSUE THREAD

**Issue by abasheyari595** [Mahmud0808/Iconify#257]
### Describe the feature

whenever the screen turns off, iconify will execute the Clear Recent Tasks, which will send an intent to close the system dialogs and clear all recent tasks

### Why would it be useful to add?

Reducing battery consumption through recents tasks clear after screen turns off

### Example(s)

I open some apps in recents after i turns off screen automatic clear recents tasks

**Comment by Mahmud0808** [comment]
Sorry but this is not theming or customization related.
