### ISSUE TITLE
[FEATURE] Single color battery icon bypassing battery saver mode

### ISSUE THREAD

**Issue by VitorQueiroz** [Mahmud0808/Iconify#258]
### Describe the feature

The idea would be to have an option to change the style of the battery icon in the Xposed menu but with an option to "bypass" the battery saver mode. So that it doesn't get colorful when battery saver is activated. 

### Why would it be useful to add?

Although knowing that the battery saving mode is active is interesting, it is not necessary to demonstrate this on the battery icon in the status bar, because in the quick settings bar we can already see if this mode is active.

Depending on the configuration made in Iconify, the colored battery icon ends up harming the design.

### Example(s)

The concept is actually simple. It would just keep the color of the icon as if the battery saving mode was not active, but with it being active.

How it currently looks with battery saving mode active:
![IMG_20230825_152634](https://github.com/Mahmud0808/Iconify/assets/67592433/a261448c-0a4a-4dd2-b4b9-887a44c96d70)

How would it look after this feature:
![IMG_20230825_152656](https://github.com/Mahmud0808/Iconify/assets/67592433/a36c6da4-25ac-426f-9468-5e2f79fc0320)

**Comment by Mahmud0808** [comment]
You can now change the color of power saving indicator. Use Battery Style L.
