### ISSUE TITLE
QS Text Color

### ISSUE THREAD

**Issue by bugycugy** [Mahmud0808/Iconify#26]
### **Bug:**
QS text color

**Iconify / QS Panel Tiles / Icon and Label / QS Text Color:
Fix Text Color - A13**; It makes the text more invisible.

**Follow System v2 - A12**; the fix works fine, but the texts of the active icons are not readable.

**Screenshots**
![photo1669460524](https://user-images.githubusercontent.com/40837905/204085749-8320fb05-f616-4eec-bdd9-70c5699c4b25.jpeg) ![photo1669460524 (1)](https://user-images.githubusercontent.com/40837905/204085757-f25e9269-e6b0-4018-b8ba-d9df35600333.jpeg) ![photo1669460535](https://user-images.githubusercontent.com/40837905/204085776-e10ffb36-f4e3-4e7f-b37d-997f4fb0223d.jpeg) ![photo1669460535 (1)](https://user-images.githubusercontent.com/40837905/204085777-36fc3789-810c-4974-972b-8d5aa634498b.jpeg)

**Smartphone:**
 - Device: Mi Note 10 Pro (Tucana)
 - OS Name: OctaviOS
 - Android Version: Android 13
 - Iconify Version: v3.1 - Beta (HotFix)

**Additional context**
**Also the color of the sounds of other devices in the volume panel slider does not change.**

![photo1669460535 (2)](https://user-images.githubusercontent.com/40837905/204085862-3489527e-e48c-493e-8f87-a22d3847d787.jpeg)

**Comment by Mahmud0808** [comment]
**Fix Text Color - A13** was a test version. I will have to work more on it. Thanks for the report.

**Comment by bugycugy** [comment]
I thank you, I wish you could activate the channel's discussion group in Telegram and there we can easily convey these situations to you.

**Comment by bugycugy** [comment]
There is a bug that I just noticed.
Brightness Bar & QS Panel Tiles
Outline and Leafy Outline

Although the background is black, it looks white.

![photo1669463272](https://user-images.githubusercontent.com/40837905/204087247-9e728b0e-fe6d-4387-9d84-ffeb3648ee81.jpeg) ![photo1669463272 (1)](https://user-images.githubusercontent.com/40837905/204087252-b0ea3656-f482-4b26-8aff-492c6fd5d099.jpeg)

**Comment by Mahmud0808** [comment]
Use v3.1 Beta (HotFix) version to fix white tile issue in pixel variant. If it still doesn't work, then a clean install is recommended.

**Comment by bugycugy** [comment]
Thank you for your help, I look forward to the updates.
