### ISSUE TITLE
[BUG] App's buggy UI on LineageOS 20 / Motorola One vision

### ISSUE THREAD

**Issue by Darkpepito** [Mahmud0808/Iconify#260]
### Describe the bug

Hey,  
Since the last update the UI of the app looks really weird, and doesn't allow me to access every butons.

### Steps to reproduce

No idea

### Expected behavior

No buggy UI

### Screenshots

![Screenshot_20230827-185208_Iconify](https://github.com/Mahmud0808/Iconify/assets/98229948/0a7b8f65-2037-47f2-a1ab-050c1fb17bd7)

### Device information

- Device: Motorola One Vision
- OS: LineageOS 20 (kane nightly build, please consider the bug already happened on LineageOS 19.1 stable)
- App version : 6.4.0

### Additional context

Really happened recently, last or before last app update

**Comment by Mahmud0808** [comment]
Can you kindly provide a video recording of the issue? Thanks.

**Comment by Darkpepito** [comment]
Sure, here is the [link](https://drive.proton.me/urls/AB88K0W5QG#jOKSz8dJRlS0)
(The file is to big, sorry)

**Comment by Mahmud0808** [comment]
Can you tell me which version worked fine for you? So that I can compare and find out the issue as I have no such issue on my device or emulators.

**Comment by Darkpepito** [comment]
Tested it, and the 6.3.1 work just fine (but unfortunately doesn't have all the functionalities)
