### ISSUE TITLE
[BUG] QS transparency not working

### ISSUE THREAD

**Issue by xlMegaDethlx** [Mahmud0808/Iconify#265]
### Describe the bug

In the latest debug version, transparency is broken, I would like it to be fixed, or to work as before 

### Steps to reproduce

1. Go to Xposed settings
2. Click on transparency and blur
3. Enable any option
4. No change

### Expected behavior

Until version 1396 it is possible to use transparency normally, after that debug version it is no longer possible to activate transparency normally or at least I don't see how to make it work 

### Device information

- Device: [Poco F3 Global]
- OS: [SkylineUI A13]
- App version: [v 6.4.0 debug #1435]

**Comment by HiFIi** [comment]
🤔

**Comment by HiFIi** [comment]
#
![Uploading Screenshot_20230915-000029.png…]()

**Comment by Mahmud0808** [comment]
Check latest debug https://github.com/Mahmud0808/Iconify/commit/657f8fb0e5683f9e1aab91ecb36e3c938e0f95ec

**Comment by HiFIi** [comment]
You're too good man
