### ISSUE TITLE
[FEATURE] Emoji packs

### ISSUE THREAD

**Issue by gaussandhisgun** [Mahmud0808/Iconify#273]
### Describe the feature

Emoji packs are basically a quick and convenient way to change your system-wide emojis. These are quite easy to do using system overlay stuff, since we already have the magisk module. Push the emoji font ttf file into /system/fonts of the module and prompt the user to reboot.

### Why would it be useful to add?

This gives the user more freedom to express themselves. Some people just prefer the cuter blob emotes over whatever the hell new Google emote fonts are. Or, some people might want Windows emojis or Twemojis or whatever.

### Example(s)

This was [suggested on Blobmoji issue tracker](https://github.com/C1710/blobmoji/issues/132), so I would say Blobmoji as the first candidate would be nice to see.

**Comment by HiFIi** [comment]
This is a good idea

**Comment by IdkWhatToCallMe123** [comment]
You could already use Zfont for this

**Comment by Mahmud0808** [comment]
Out of iconify's objective. Use [RKBDI Emoji](https://t.me/rkbdiemoji) or [Emoji Replacer](https://t.me/EmojiReplacer)
