### ISSUE TITLE
[FEATURE] depth effect for lockscreen wallpaper 

### ISSUE THREAD

**Issue by giommifili** [Mahmud0808/Iconify#274]
### Describe the feature

It would be cool to have a depth effect for the wallpaper when using a custom Lockscreen clock. There should be a feature where it allows you to add a transparent PNG as the highlighted subject on top of both wallpaper and clock, I hope I was clear enough, if you want to contact me my telegram is @giommi

### Why would it be useful to add?

It would just look good and it would be a nice thing to have

### Example(s)

![470f3ff2a23c2a19ad4b9e684a6e2e11](https://github.com/Mahmud0808/Iconify/assets/140720537/f14b8ded-b2f9-4364-89b8-6bc2532de5e5)
![Black-and-white-wallpapers-support-Lock-Screen-Depth-Effect](https://github.com/Mahmud0808/Iconify/assets/140720537/18b365a6-ce5a-4446-9769-51c6fb3eaa58)
![depth-effect-on-ios-16-b](https://github.com/Mahmud0808/Iconify/assets/140720537/9a6150ff-16e8-4885-a9be-0557190fc4bc)

**Comment by HiFIi** [comment]
That's a neat idea.  Not sure how possible it is though

**Comment by giommifili** [comment]
Maybe you could make another overlay where you can let people load a transparent PNG on top of the lockscreen wallpaper, idk if u get what I mean

**Comment by IdkWhatToCallMe123** [comment]
In the mean time you could use something like KLWP and any photo editor to do this.
