### ISSUE TITLE
[FEATURE] Remove Lockscreen Fingerprint icon background/circle 

### ISSUE THREAD

**Issue by MoZiSaan** [Mahmud0808/Iconify#276]
### Describe the feature

Removing the circle/background in the Lockscreen Fingerprint icon and making the icon support monet 

### Why would it be useful to add?

It will make the Lockscreen look more beautiful, minimal and clean, while not using a custom icon so dotted aod icon and Lockscreen icon still look consistent 

### Example(s)

![Screenshot_20230104-104715_Smart_Launcher](https://github.com/Mahmud0808/Iconify/assets/98599186/4247ff3b-6f8e-4994-8935-6966594c794e)

![Screenshot_20230125-061602_Smart_Launcher](https://github.com/Mahmud0808/Iconify/assets/98599186/9c0aebba-7f2d-4955-b855-87dcfc3656ea)

![Screenshot_20230204-223726_Smart_Launcher](https://github.com/Mahmud0808/Iconify/assets/98599186/f0197d73-f216-4573-bfbc-e58bd423f344)

**Comment by HiFIi** [comment]
That's cool:)

**Comment by Mahmud0808** [comment]
It's available in [PixelXpert](https://github.com/siavash79/PixelXpert), so I have no plan to add that here too.

**Comment by silverwings15** [comment]
given that PixelXpert requires Lsposed and Iconify doesn't (at least for most of its features, not to mention the stuff that's happened with the official Lsposed project), would you reconsider making this feature available on Iconify?

**Comment by Mahmud0808** [comment]
It will require LSPosed as far as I can tell. And I have a side mounted fingerprint so I can't work on it. Also there is a fork of lsposed that works even on android 15.

**Comment by silverwings15** [comment]
ah, unfortunate if lsposed is a requirement (i'm on GrapheneOS and there's no compatible version of LSposed yet). tyvm!
