### ISSUE TITLE
[BUG] system service not running

### ISSUE THREAD

**Issue by ramintkml** [Mahmud0808/Iconify#279]
### Describe the bug

After I activate iconify in lsposed
Lsposed tweak in app gives me this error

### Steps to reproduce

1. Go to 'tweaks.'
2. Click on 'xposed menu'
3. See the error above the list

### Expected behavior

I have activate iconify in both lsposed and magisk, also I did the re-optimize things on lsposed menu

### Screenshots

![Screenshot_20230923-094248_Iconify](https://github.com/Mahmud0808/Iconify/assets/85295861/43deb22e-9621-4018-bdbc-65340e5f7bd5)

### Device information

- Device: POCO F3
- OS: neoteric os (android 13 QPR3) CLO
- App version: 6.5.0

**Comment by Mahmud0808** [comment]
Did you restart SystemUI after re-optimizing iconify? If you already did and still not working, follow this: disable iconify from lsposed > re-optimize > enable again > re-optimize > restart SystemUI.

**Comment by HiFIi** [comment]
This ^^^^

**Comment by ramintkml** [comment]
It worked after I did what you mentioned

Thanks
