### ISSUE TITLE
[BUG] Status icons colored chip and privacy chip conflict

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#281]
### Describe the bug

When the chip behind status icons is disabled, the privacy (microphone/location/camera) chip covers all icons (they can also be hidden, I do not know). When it's enabled, it doesn't look right. Look at the screenshots.

### Steps to reproduce

1. Enable chip behind status icons
2. Open the camera app (to show the privacy chip)
3. Expand QS panel

### Expected behavior

Status icons should be hidden or moved to not conflict with the privacy chip. Joining them into a single group of icons (of course if possible) would be also nice.

### Screenshots

Status icons chip disabled:

![Screenshot_20230923-095942_Open Camera](https://github.com/Mahmud0808/Iconify/assets/99012892/6df5bf64-f3a5-4649-903d-15f963df2ca9)

Enabled:

![Screenshot_20230923-102658_Open Camera](https://github.com/Mahmud0808/Iconify/assets/99012892/7ab1ebe3-1a96-4b99-ac81-fe1eb9d00e95)

### Device information

- Device: Redmi Note 7
- OS: LineaageOS 20.0
- App version: 6.5.0

**Comment by Mahmud0808** [comment]
It's not a major issue and can easily be ignored as privacy chip only shows up for a few seconds.
