### ISSUE TITLE
[SUGGESTION] more dp slider for statusbar on qs

### ISSUE THREAD

**Issue by NOTURFRIENDBTW** [Mahmud0808/Iconify#282]
### Describe the feature

Giving more statusbar margin on Android 12 & 12L because it can only get 48dp and make it look like image below
![Screenshot_20230923-204615_Iconify](https://github.com/Mahmud0808/Iconify/assets/79923098/497c50bf-c38f-4129-8013-5f2832362d06)

### Why would it be useful to add?

Useful for customization

### Example(s)

Image taken using Evolution X Android 13(Tiramisu)
![IMG_20230923_205732_563](https://github.com/Mahmud0808/Iconify/assets/79923098/f0090b2a-cf27-41a9-ba52-0e15d48c8bf1)

### Additional context

Would be very useful for customization on Android 12 & 12L/12.1 because it limited on 48dp

**Comment by Mahmud0808** [comment]
I am using an old method for changing status icons top margin on A12 and A12L which has been improved on A13+. With the old method, the icon disappears if you increase margin too much.

There's a saying: ___if it ain't broke, don't fix it.___ This is the reason I didn't bother to change it. If I get free time and is on A12/A12L, I'll consider. Hope you'll understand.
