### ISSUE TITLE
[FEATURE] Xperia icon request

### ISSUE THREAD

**Issue by Slimreaper02** [Mahmud0808/Iconify#283]
### Describe the feature

Please add Xperia icons for status bar (wifi and signal)

Thanks

### Why would it be useful to add?

It will be perfectly fit on iOS 16 battery 

### Example(s)

![IMG_20230924_034424_761](https://github.com/Mahmud0808/Iconify/assets/136085723/087624f2-eaa7-4223-af0e-bfb0f578abaa)

**Comment by Mahmud0808** [comment]
I only add full icon pack, and no plan to add only wifi/cellular icons.
