### ISSUE TITLE
[BUG] reset some customization after restarting system ui 

### ISSUE THREAD

**Issue by Alex1kurdin** [Mahmud0808/Iconify#288]
### Describe the bug

Hello, After each restarting system ui, some stuff reset to default value settings such as:
Ui corner rounding, amoled black theme, some icons in status bar and taskbar.
Also if I applied again my iconify's settings the ROM will be a bit slower down and laggy.

### Expected behavior

Hope to fix those bugs because it's so annoying each time set up settings again and again.

### Screenshots

![Screenshot_20230926-125923_Telegram](https://github.com/Mahmud0808/Iconify/assets/132998706/0e9c89d4-11b3-48db-af25-8373cfc6ca62)
![Screenshot_20230926-125754_Telegram](https://github.com/Mahmud0808/Iconify/assets/132998706/780fd1ef-cbca-4192-809c-b3afb6fa7d59)
![Screenshot_20230926-125109_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/132998706/a50aa8cd-439a-489e-a5a8-9c382539300f)

### Device information

- Device: [LG v30+]
- OS: [ crDroid 9.8 ROM Android version 13.0]
- App version: [e.g. v6.5-Beta#1487]

### Additional context

Thank you so much for your hard working 🙏🏼

**Comment by Alex1kurdin** [comment]
@Mahmud0808 
P.s: on #1462 version everything working fine without any bugs that I've mentioned them earlier.

**Comment by Mahmud0808** [comment]
> @Mahmud0808 P.s: on #1462 version everything working fine without any bugs that I've mentioned them earlier.

Try doing a clean installation of latest debug. If issue still persists, then narrow it down to exactly which version fixes your issue and which version breaks it. I will look into it.

**Comment by HiFIi** [comment]
> @Mahmud0808 P.s: on #1462 version everything working fine without any bugs that I've mentioned them earlier.

[Latest debug apk #1487(click me)](https://github.com/Mahmud0808/Iconify/suites/16536283646/artifacts/944548749)

**Comment by Alex1kurdin** [comment]
> > @Mahmud0808 P.s: on #1462 version everything working fine without any bugs that I've mentioned them earlier.
> 
> Try doing a clean installation of latest debug. If issue still persists, then narrow it down to exactly which version fixes your issue and which version breaks it. I will look into it.


Well, I did a clean installation of the latest debug version #1487, all issues present there.
The last version worked without any those bugs is #1462.

In #1463 I had pitch black, mount engine & roundness problem but icons worked fine.

I think after #1478 I had started icons issue.
Hope my report is useful for you.
Thanks

**Comment by Mahmud0808** [comment]
> Well, I did a clean installation of the latest debug version #1487, all issues present there. The last version worked without any those bugs is #1462.
> 
> In #1463 I had pitch black, mount engine & roundness problem but icons worked fine.

Between 1462 and 1463, only depth wallpaper has been added. Nothing else was changed. This can't cause issue for overlays.

**Comment by Alex1kurdin** [comment]
> > Well, I did a clean installation of the latest debug version #1487, all issues present there. The last version worked without any those bugs is #1462.
> > In #1463 I had pitch black, mount engine & roundness problem but icons worked fine.
> 
> Between 1462 and 1463, only depth wallpaper has been added. Nothing else was changed. This can't cause issue for overlays.

I see,
Ok I would stay at #1462, I don't use depth wallpaper btw.
One thing I have to mention it, if I don't use disable system mount, pitch black and mount engine color would be mess even at #1462 version, but with disabled that everything is ok.
I've tried this with other newer versions but wasn't successful.
Thanks for your great job🙏🏼
If it isn't be fixed so I'm out for newer versions at least for now with my current phone and ROM.

**Comment by Alex1kurdin** [comment]
By updated crDroid 9.8 to 9.9, also the latest lsposed bugs fixed.
Thanks & I'll close this report.
