### ISSUE TITLE
QS Panel Margin & Navigation Bar

### ISSUE THREAD

**Issue by princemalikxp** [Mahmud0808/Iconify#289]
### Describe the bug

I've customized my navigation bar and adjusted the Quick Settings panel to reveal the header image. However, after restarting my mobile phone, these customizations get disabled, so I have to reapply them manually.
But Enabling the 'Restart SystemUI After Boot' option makes the navigation bar apply automatically, but the Quick Settings panel margin still requires manual adjustment.

### Steps to reproduce

1. Customise navigation bar and adjust QS panel margin
2. Apply them
3. Then restart your device

### Expected behavior

QS panel margin and navigation bar disabling 

### Device information

- Device: Poco X3
- OS: PixelExperience_Plus_surya-13.0-20230818-1023-OFFICIAL
- App version: v6.5.0

**Comment by Mahmud0808** [comment]
Navbar behavior is expected. Which QS panel margin did you use? from inside xposed menu?

Edit: No further response. Hence closing.
