### ISSUE TITLE
Rounded corners of brightness slider 

### ISSUE THREAD

**Issue by ramintkml** [Mahmud0808/Iconify#29]
Rounded corners of brightness slider is not match to background of brightness slider 

![Screenshot_20221126-165937_Iconify~3](https://user-images.githubusercontent.com/85295861/204091793-87dba2b4-5470-4f28-b1df-ab69e3bd9ab7.png)

**Smartphone
 - Device: POCO F3 
 - OS Name: Pixel Experience 13+
 - Android Version: 13
 - Iconify Version: 3.1beta

**Comment by Mahmud0808** [comment]
Which brightness slider is this? It doesn't match any of the previews from iconify.

**Comment by ramintkml** [comment]
> Which brightness slider is this? It doesn't match any of the previews from iconify.

It is "inline" on pixel varient section although the "inline" on non-pixel varient gives me same result

Please check screenshot

![Screenshot_20221127-085005_Iconify](https://user-images.githubusercontent.com/85295861/204120573-16c7c3e1-14c1-4a12-a981-7dc1735a5441.png)

**Comment by Mahmud0808** [comment]
Does the roundness change if you change radius from iconify? If not, brightness bar isn't applied properly.

**Comment by ramintkml** [comment]
> Does the roundness change if you change radius from iconify? If not, brightness bar isn't applied properly.

No it doesn't

How to solve???

**Comment by Mahmud0808** [comment]
> > Does the roundness change if you change radius from iconify? If not, brightness bar isn't applied properly.
> 
> No it doesn't
> 
> How to solve???

Send systemui.apk, I will have to check.

**Comment by Mahmud0808** [comment]
Fixed in latest debug version.
