### ISSUE TITLE
LSPosed/Patch

### ISSUE THREAD

**Issue by PeterKW** [Mahmud0808/Iconify#290]
### Describe the bug

LSPatch has Iconify settings show up but doesn't do anything when clicked

https://github.com/LSPosed/LSPatch

### Expected behavior

.

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. v4.0-Beta]

**Comment by PeterKW** [comment]
![Screenshot_20230927-191222~2](https://github.com/Mahmud0808/Iconify/assets/13779157/f29353aa-9ff9-4366-a496-9e83da54d0e2)

**Comment by Mahmud0808** [comment]
> LSPatch: Rootless implementation of LSPosed framework, integrating Xposed API by inserting dex and so into the target APK.

On the other hand, iconify's readme says:

```diff
- NOTE: This app requires Magisk or KernelSU for root access. Any alternative methods won't work.
```
