### ISSUE TITLE
Will Android 13 be supported?

### ISSUE THREAD

**Issue by alexchiu100014** [Mahmud0808/Iconify#3]
Using elixir 3.2
Only Qs Row and Column worked.

**Comment by robinsrk** [comment]
For me everything is working in lineage 20. the only problem i faced is in notification styles. Changing the style messes up the whole notification design and looks weird

**Comment by Mahmud0808** [comment]
> Using elixir 3.2 Only Qs Row and Column worked.

I haven't yet got the chance to flash a13. but as most people reported that it's working on a13 on most parts, so I suppose it's a rom related issue. I will look into it once I got the rom for my device.



> For me everything is working in lineage 20. the only problem i faced is in notification styles. Changing the style messes up the whole notification design and looks weird

Are the notifications way too much rounded? If that's the case, I will soon release a fix for that.

**Comment by robinsrk** [comment]
> 
> Are the notifications way too much rounded? If that's the case, I will soon release a fix for that.

Yeah. too much rounded. hope fix will come soon

**Comment by ReyRSPlus** [comment]
Could you do it for OxigenOS 13 please

**Comment by Mahmud0808** [comment]
> Could you do it for OxigenOS 13 please

Unfortunately I don't have any OOS device or rom.

**Comment by ReyRSPlus** [comment]
And what exactly would you need? I could provide you with the files and serve as a tester, I loved the module, I tried it on my oneplus and it only changes a few things

**Comment by ReyRSPlus** [comment]
@Mahmud0808 Would it be too much trouble if you could contact me on Telegram? Or somewhere I can speak to you directly please

**Comment by Mahmud0808** [comment]
> @Mahmud0808 Would it be too much trouble if you could contact me on Telegram? Or somewhere I can speak to you directly please

Hopefully latest debug version fixes most issues.
Also https://t.me/DrDisagree
