### ISSUE TITLE
Whitish qs notification text and black active tiles

### ISSUE THREAD

**Issue by hypersoumya** [Mahmud0808/Iconify#30]
In leafy outline shpe , Text of tiles remains black while its active  ... If I turn on qs text colour always white .. then that tiles problem solves but now qs notification text becomes whitish .
In pixel rom
![markup_1688](https://user-images.githubusercontent.com/71786747/204140859-901975a2-5895-41f5-a225-3b3a98f8f09e.png)
![markup_1687](https://user-images.githubusercontent.com/71786747/204140865-51092243-6342-4a83-81b2-91f3e3a13e4d.png)
![markup_1687](https://user-images.githubusercontent.com/71786747/204140921-dc715908-34af-4f0d-97d9-34f38151e354.png)

**Comment by Mahmud0808** [comment]
Which version of Android are you using?

**Comment by erenmete** [comment]
I think it can be categorized here as well, QS Panel Tiles option messes up with the overall look here.

![Screenshot_20221129-123507_Iconify](https://user-images.githubusercontent.com/58091473/204492868-624177df-fd39-43d1-8498-8dffdb502a5d.png)

It only worked properly when i first installed it but now this is what i end up with whenever i apply a QS Panel Tile theme.

I'm on VoidUI Android 13, based on Pixel Experience.

**Comment by Mahmud0808** [comment]
Yeah android 13 is having issues with custom tiles. I am trying to fix it. Will be released as soon as I can fix it.

**Comment by Mahmud0808** [comment]
Fixed in Debug APK #250. Soon will be available in release build too. So  hereby closing the issue.
