### ISSUE TITLE
QS "Row & Column"

### ISSUE THREAD

**Issue by NiXTheDev** [Mahmud0808/Iconify#303]
### Describe the bug

When set to show 5 columns, QS(and QQS) only shows a maximum of 4 columns of tiles, however!
When you go into the "edit" mode to add more tiles for example it does show 5 columns, confusion just keeps on coming!

### Steps to reproduce

1. Go to Tweaks > Row & Column
2. Click on set columns to 5 and rows to whatever and then apply
3. Open QQS and/or QS shade

### Expected behavior

QQS and QS should show 5 columns when set to 5 in iconify

### Screenshots

![QQS and QS show 4 tiles](https://github.com/Mahmud0808/Iconify/assets/105677206/b5b281fa-afc3-4e73-9343-78e8e71a393c)
![While in the Edit mode it shows correctly 5 columns](https://github.com/Mahmud0808/Iconify/assets/105677206/1ea065a3-a577-4915-9cf7-9ed8290ca452)

### Device information

- Device: Redmi Note 11 NFC(Spesn)
- OS: Pixel experience Plus 13
- App version: 6.5.1

### Additional context

Error is seen for multiple updates, I believe I saw it first from 6.3.x or 6.4.0, don't recall exactly

**Comment by Mahmud0808** [comment]
It's not a bug. It's your rom which has a maximum limit of 4 columns. Maybe it can be overridden with xposed, but not with overlays.

**Comment by NiXTheDev** [comment]
Could you guide me as to how to do that?

**Comment by Mahmud0808** [comment]
I don't think you can do anything unless you know how to develop an xposed module. You can try AOSPMods which has xposed based row, column modifier but I doubt it has 5 columns selection.

**Comment by NiXTheDev** [comment]
~~I'll try anyway, thanks!~~
Yes, it allows at most 4 columns
(I do hope for an Xposed implementation though)
