### ISSUE TITLE
[BUG] Notification styling not working on A14 Pixel 6a

### ISSUE THREAD

**Issue by cozykitten** [Mahmud0808/Iconify#305]
### Describe the bug

Notification styling doesn't change from stock style since A14 OTA.
I'm on a Pixel 6a, rooted with Magisk, LSPosed module installed.
Android 14 (October) and App version 6.5.1 (was the same on 6.5.0).

### Steps to reproduce

1. Enable Pixel variant or not Pixel variant Notification styling.
2. Restart System UI or don't
3. Notification style is not applied

### Expected behavior

Should apply as before

### Screenshots

![image](https://github.com/Mahmud0808/Iconify/assets/116394977/5e39e004-18b0-4d2d-963e-0129d10a420d)
![image](https://github.com/Mahmud0808/Iconify/assets/116394977/a2de9171-c4e2-4095-a8f1-70209ccb66b4)

### Device information

- Device: Pixel 6a
- OS: A14 stock, Magisk root
- App version: 6.5.1

### Additional context

Might not be a bug but might mention it anyway.
When using the notification styling before when it worked on A13, stacked notifications had some "issues" with the outlines sort of connecting them but their individual outlines still being there, leading to a sort of "cat nose" tri-crossing lines look.

**Comment by Mahmud0808** [comment]
Notification styles are working, just the accent colors are not working on notification. I will look for a fix when I get time. :)

**Comment by cozykitten** [comment]
Thanks a lot!
(Idk if you wanna keep this open or if you use different tools to track ur issues so I'll just leave it as is)

**Comment by Mahmud0808** [comment]
Fixed https://github.com/Mahmud0808/Iconify/commit/af5de649e60af92ed18ced65cfcf854a77829131
