### ISSUE TITLE
[BUG] white statusbar icons on white background

### ISSUE THREAD

**Issue by ramintkml** [Mahmud0808/Iconify#306]
### Describe the bug

The statusbar icons on qs panel are white while the background is white as well
The rom it self has white qs background 

### Steps to reproduce

1. Pull down qs panel
2. Look at the top

### Expected behavior

Icons should turn to gray

### Screenshots

![Screenshot_20231013-091305_Messages~2](https://github.com/Mahmud0808/Iconify/assets/85295861/f9b2364d-1abb-44b7-806a-6795486a185b)

### Device information

- Device: [POCO F3 (Alioth)]
- OS: [Neotric OS android 13 clo]
- App version: [v6.5.1]

**Comment by Mahmud0808** [comment]
What did you enable that caused the issue? Explain more precisely.

Edit: No further response. Hence closing.
