### ISSUE TITLE
[FEATURE] custom corner size for statusbar clock pill 

### ISSUE THREAD

**Issue by rajath-2** [Mahmud0808/Iconify#307]
### Describe the feature

thank you for your great work
would be great if you added custom corner size for statusbar clock pill 

### Why would it be useful to add?

it would help with the pill looking huge at times

### Example(s)

![IMG_20231013_211748_970](https://github.com/Mahmud0808/Iconify/assets/129841509/915c2c1e-e67c-4f38-a145-e43d8abe6b97)

**Comment by Mahmud0808** [comment]
The screenshot you provided is from a closed source rom.
