### ISSUE TITLE
Option for different blur algorithm

### ISSUE THREAD

**Issue by elisenlebkuch** [Mahmud0808/Iconify#309]
### Describe the feature

Add the option to choose a blur altgorithm that can handle higher Values while keeping gaussian blur for those who like it.

### Why would it be useful to add?
#
If you don't want the "diamond effect" like the person here: #197 

### Example(s)

![Screenshot_20231014-170939_Lawnchair](https://github.com/Mahmud0808/Iconify/assets/127782512/b51368d3-f3af-4957-b9fa-54152b735333)

**Comment by Mahmud0808** [comment]
It's not possible for now, even if it is possible, it will be a huge work.
