### ISSUE TITLE
A Question 

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [Mahmud0808/Iconify#31]
`Added Volume Panel customization. (only works if your rom has thin volume panel by default)`

Was written on 4.0 update changelog, since I can't find anyplace to ask question I'm asking here, sorry in advance
So what does thin volume panel mean? the default one? Can you please add a screenshot of it if possible?
Thanks

**Comment by Mahmud0808** [comment]
![Screenshot_20221220-183723_Iconify](https://user-images.githubusercontent.com/29881338/208669293-e0b56780-cc5f-4112-aaea-2217c70dffa5.png)

The left one is the thin (default) volume panel.
You can ask questions on my telegram t.me/IconifyBot

**Comment by Black-StellarSpectrum** [comment]
> ![Screenshot_20221220-183723_Iconify](https://user-images.githubusercontent.com/29881338/208669293-e0b56780-cc5f-4112-aaea-2217c70dffa5.png)
> 
> The left one is the thin (default) volume panel. You can ask questions on my telegram t.me/IconifyBot

Thanks 🙏
Next time I'll use the bot
