### ISSUE TITLE
[BUG] Unable to change QS tile text/icon size and location.

### ISSUE THREAD

**Issue by Avellea** [Mahmud0808/Iconify#312]
### Describe the bug

Currently running A14 on my Pixel 6a, stock rom and latest version of Iconify. I've tried every combination of settings, and it doesn't seem to respect that. The icons and text never change size or location, no matter if I've pressed apply and restarted the SystemUI.

### Steps to reproduce

1. Change QS tile icon size
2. Press apply
3. (Optional) Restart SystemUI

### Expected behavior

Size and/or location changes.

### Screenshots

![Screenshot_20231014-175454](https://github.com/Mahmud0808/Iconify/assets/34009754/f6309f9b-df05-4c6a-ace1-99bf1539bd09)
![Screenshot_20231014-175558](https://github.com/Mahmud0808/Iconify/assets/34009754/5153268b-3ba9-41e9-afe8-9b2eb2d0fdb2)

### Device information

- Device: Google Pixel 6a
- OS: Stock ROM Android 14
- App version: 6.5.1

**Comment by Avellea** [comment]
Quick update, this also seems to happen with the Quick Settings options in the Xposed Menu as well. Things like transparency and blur work fine, along with the header clock.

**Comment by Mahmud0808** [comment]
Android 14 U1B2? Already known and can't fix without getting the source code.

**Comment by Avellea** [comment]
> Android 14 U1B2? Already known and can't fix without getting the source code.

UP1A :)
![Screenshot_20231015-121645.png](https://github.com/Mahmud0808/Iconify/assets/34009754/eb3a1241-6744-4f1c-967f-f1de9804aabc)
