### ISSUE TITLE
[Bug] Status bar clock pill too big

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#316]
### Describe the bug

The pill has a too large space at the right side somehow.
But its only weirdly shaped on some times like 21:xx

### Steps to reproduce

1. Enable pill
2. See issue 

### Expected behavior

The pill should be normal

### Screenshots

![Screenshot_20231017-212053](https://github.com/Mahmud0808/Iconify/assets/90862487/bbe7d76f-1fbe-4c3a-9438-f2c23cff6cdb)

### Device information

- Device: Pixel 8 pro
- OS: Stock OS Android 14
- App version: 6.5.1

**Comment by Mahmud0808** [comment]
Let me know if there is any improvement: https://github.com/Mahmud0808/Iconify/commit/40183021c47e81a3a344bc8bac07c1eb62816600

**Comment by srt54558** [comment]
> Let me know if there is any improvement: https://github.com/Mahmud0808/Iconify/commit/40183021c47e81a3a344bc8bac07c1eb62816600

Yes its definitely better

**Comment by Mahmud0808** [comment]
Feel free to re-open this issue if the bug persists again.
