### ISSUE TITLE
[Feature]  Remove custom toast frame

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#317]
### Describe the feature

It's currently not possible to remove the toast frame when selected a custom one just like e.g. custom QS tiles.

### Why would it be useful to add?

Because when I select one on my Pixel 8 pro/Android 14 then no toast frame works and the frame has no rounded corners anymore 

### Example(s)

Just a remove button

**Comment by Mahmud0808** [comment]
Fixed in https://github.com/Mahmud0808/Iconify/commit/5c6c39575fc5fa5532fb04e0c9d6ee78486af6fe
Thanks for the report.
