### ISSUE TITLE
[Bug] Bootloop when restart systemui

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#319]
### Describe the bug

Sometime when I boot I have to wait for the sim card pin icon to become white till I can enter the pin. After entering, most of the times there's still the sim card pin entering screen but with a blue sim icon. If I enter, nothing happens but if I turn the screen off and on, that blue sim card screen it's gone. It's just the normal sim card pin unlocking screen but with a blue sim card icon. Then I unlock my phone and sometimes the status bar (except battery icon) is white instead of my dynamic color. When I then go to iconify and restart systemui in iconify then it works but after like 10 seconds my phone reboots. And then my Bootloop saver turns all modules off. If I turn on iconify again, my phone reboots after 10-30 seconds.

To resolve the Bootloop, I have to remove iconify module and reinstall iconify completely.

### Steps to reproduce

1. Go to iconify
2. Click on restart systemui

### Expected behavior

The sim card screen should reload and should go away after I enter the pin.

There's shouldn't be a Bootloop after restarting systemui.

### Screenshots

Sorry but I can't provide screenshots, as I don't want a Bootloop again and can't take screenshots upon boot

### Device information

- Device: Pixel 8 Pro
- OS: Stock Android 14 (UD1A.230803.041)
- App version: 6.5.1

### Additional context

It only makes Bootloop when the status bar is with white icons on a boot. When everything is normal, I can restart systemui with iconify without Bootloop.

I hope I gave at least some help to resolve this issue.

**Comment by Mahmud0808** [comment]
Provide logs, I can't figure out exact cause of issue without logs. And also I didn't understand what you meant by sim card pin icon.

White statusbar is not a bug, iconify applies some effects after booting up and some of those effects need systemui restart to take effect.

**Comment by srt54558** [comment]
> Provide logs, I can't figure out exact cause of issue without logs. And also I didn't understand what you meant by sim card pin icon.
> 
> White statusbar is not a bug, iconify applies some effects after booting up and some of those effects need systemui restart to take effect.

If I ever get into a situation where I have a white status bar on boot again, I will provide logs... But how?

**Comment by Mahmud0808** [comment]
`adb logcat -d > logcat.txt`
