### ISSUE TITLE
Add Iconify to F-Droid Repo

### ISSUE THREAD

**Issue by Kruegerrr** [Mahmud0808/Iconify#32]
### Describe the feature

Iconify is included in [IzzyOnDroid F-Droid Repo](https://apt.izzysoft.de/fdroid/index/apk/com.drdisagree.iconify), but is not updated since the initial release v1.0-Beta. Could you please add the software to the official F-Droid Repo?

### Why would it be useful to add?

F-Droid provides an easy and centralized way for Android users to manage and update their FOSS. I hope all users of Iconify can also enjoy such convenience.

### Example(s)

N/A

**Comment by Mahmud0808** [comment]
I am currently refining the app and fixing as much things as possible. After that I will consider uploading it on F-Droid.

**Comment by Mokura** [comment]
Looks like the non debug version 5.0 just went live on Izzy!

![Screenshot_20230115-165436_Neo Store](https://user-images.githubusercontent.com/5167919/212569293-46379b31-529d-4408-8bb9-04beb0d7add0.png)

**Comment by Mahmud0808** [comment]
> Looks like the non debug version 5.0 just went live on Izzy!
> 
> ![Screenshot_20230115-165436_Neo Store](https://user-images.githubusercontent.com/5167919/212569293-46379b31-529d-4408-8bb9-04beb0d7add0.png)

Nice to see. But I hope he updates the app icon too.

**Comment by IzzySoft** [comment]
> But I hope he updates the app icon too.

Nope, never :see_no_evil: That's up to you. With more than 1k apps in my repo, I cannot check all of them manually. But maybe we can strike a deal: I open a PR here providing you the metadata set up on my end, using [Fastlane structures](https://gitlab.com/-/snippets/1895688), you merge that – and then adjust it to your liking whenever needed? Changes would then be pulled along with each release (which is checked for once per day – I was waiting for your repo to return to re-enable that, glad it did :star_struck:).

For now I've just replaced the icon manually, should show up with the next sync around 7pm UTC. Please let me know if you'd accept the PR – you'd need those Fastlane structures anyway when applying to F-Droid (disclosure: I'm also one of the maintainers there).

**Comment by Mahmud0808** [comment]
> > But I hope he updates the app icon too.
> 
> Nope, never 🙈 That's up to you. With more than 1k apps in my repo, I cannot check all of them manually. But maybe we can strike a deal: I open a PR here providing you the metadata set up on my end, using [Fastlane structures](https://gitlab.com/-/snippets/1895688), you merge that – and then adjust it to your liking whenever needed? Changes would then be pulled along with each release (which is checked for once per day – I was waiting for your repo to return to re-enable that, glad it did 🤩).
> 
> For now I've just replaced the icon manually, should show up with the next sync around 7pm UTC. Please let me know if you'd accept the PR – you'd need those Fastlane structures anyway when applying to F-Droid (disclosure: I'm also one of the maintainers there).

"Changes would then be pulled along with each release" - so it checks for new **Release** every day and grabs the apk and details itself if new release found? Or do I have to manually do something after every release to make it show up on your repo? Actually I don't want to go under much hassle.

**Comment by IzzySoft** [comment]
> so it checks for new Release every day and grabs the apk and details itself if new release found?

Yupp. A cron job using an API I wrote for that.

> Or do I have to manually do something after every release to make it show up on your repo?

Only if something goes wrong (and my updater yelled at me), which happens rather rarely. And with the metadata in your repo, you'd not even need to tell me when description or graphics changed – you'd change them here anyway (e.g. to include screenshots with your Readme), just that with the Fastlane structure the image location would be a little different. So basically it's a one-time "extra" task (merging my PR for you, creating it for me (structures are already prepared here anyway)) and everything else remains the same.

**Comment by Mahmud0808** [comment]
@IzzySoft Okay I will check your PR and merg

> > so it checks for new Release every day and grabs the apk and details itself if new release found?
> 
> Yupp. A cron job using an API I wrote for that.
> 
> > Or do I have to manually do something after every release to make it show up on your repo?
> 
> Only if something goes wrong (and my updater yelled at me), which happens rather rarely. And with the metadata in your repo, you'd not even need to tell me when description or graphics changed – you'd change them here anyway (e.g. to include screenshots with your Readme), just that with the Fastlane structure the image location would be a little different. So basically it's a one-time "extra" task (merging my PR for you, creating it for me (structures are already prepared here anyway)) and everything else remains the same.

Okay sure, go ahead with your PR. :)

**Comment by IzzySoft** [comment]
There you go :smiley:

**Comment by KotTheKitty** [comment]
It seems like 7.2.0 is the latest...

**Comment by Mahmud0808** [comment]
> It seems like 7.2.0 is the latest...

Maintaining two different versions (regular and FOSS) requires extra work, and this project currently has reproducible build issues on F-Droid (when built from Android Studio). Because of this, I'm considering moving forward with GitHub-only releases, which would reduce both workload and headaches.
