### ISSUE TITLE
[BUG] custom styles not working 

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#320]
### Describe the bug

Hello,
Custom notifications and quick settings tiles (I think) don't work. If I apply one, nothing happens.

For notification style im 100% sure it doesn't work but quick settings I'm not sure. Tested it 3 days ago

### Steps to reproduce

1. Apply custom notification style
2. See error

### Expected behavior

The styles should work as expected 

### Device information

- Device: Pixel 8 Pro
- OS: Stock Android 14 (UD1A.230803.041)
- App version: 6.5.1

**Comment by srt54558** [comment]
Navigation bar size doesn't work too

**Comment by srt54558** [comment]
Volume panel thin, thick, none doesn't work too

**Comment by talhack** [comment]
Things that doesn't work with android 14 stable (beta rom have more different issues)💀👽
1. Size and position of icon and label won't work
2. Statusbar spacing won't work.
3. Pill appearance won't work.
4. Volume slider track won't change.
5. Progress wave won't turn off
6. Quick settings qs margins won't take effect
7. Can't apply colors on notifications styles

**Comment by Mahmud0808** [comment]
Already known, android 14 blocked some of the features so I am currently looking for alternative way to fix.

Edit: Everything is fixed except QS tile styles.

**Comment by Mahmud0808** [comment]
https://github.com/Mahmud0808/Iconify/commit/23dba695788befe8248885c9125ea6d114f9a4d4

Lemme know if it fixes issue of QS tile styles.

**Comment by atomicraiden** [comment]
> Already known, android 14 blocked some of the features so I am currently looking for alternative way to fix.
> 
> Edit: Everything is fixed except QS tile styles.

Is there anything extra to capture these fixes? On the same as OP and running 6.5.1 and seeing all these still. Or have the changes just not been published yet? All good if not, will be eagerly awaiting for the great work. TY! :)

**Comment by Mahmud0808** [comment]
> Or have the changes just not been published yet? All good if not, will be eagerly awaiting for the great work. TY! :)

Every single changes are available in debug builds, which you can find in the [Actions](https://github.com/Mahmud0808/Iconify/actions) tab.

**Comment by atomicraiden** [comment]
> > Or have the changes just not been published yet? All good if not, will be eagerly awaiting for the great work. TY! :)
> 
> Every single changes are available in debug builds, which you can find in the [Actions](https://github.com/Mahmud0808/Iconify/actions) tab.

Got it, many thanks for the quick reply I will go check it out. Not the best with GitHub still, lol.

**Comment by HiFIi** [comment]
> > > Or have the changes just not been published yet? All good if not, will be eagerly awaiting for the great work. TY! :)
> > 
> > 
> > Every single changes are available in debug builds, which you can find in the [Actions](https://github.com/Mahmud0808/Iconify/actions) tab.
> 
> Got it, many thanks for the quick reply I will go check it out. Not the best with GitHub still, lol.

You're doing great :))

**Comment by Mahmud0808** [comment]
Notification styles should now be working fine with the last release version of Iconify.

**Comment by atomicraiden** [comment]
> Notification styles should now be working fine with the last release version of Iconify.

Yup yup working great now when I enable the LSPosed option. Assuming it was intended to work when that option is enabled for some devices like the P8P I'm on. 

Many thanks for the great work!
