### ISSUE TITLE
[Feature] Battery icons preview 

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#321]
### Describe the feature

Hi!
It would be quite useful to provide like a "?" Button with a page showing the look of all custom battery icons! Because applying every is very slow and takes too much time.

The same would be also very very useful for e.g. Lockscreen clock custom font or wallpaper depth effect!

### Why would it be useful to add?

Is said it in the description 

### Example(s)

![Screenshot_20231019-212208](https://github.com/Mahmud0808/Iconify/assets/90862487/9ea63915-259b-4f7c-a3c4-9941e35d262a)
Like toasts

**Comment by Mahmud0808** [comment]
You already know which font you are using, you must've downloaded the font seeing its preview first. So font preview for clock is unnecessary.

Wallpaper depth effect doesn't need multiple reboots. You just select a wallpaper and its instantly applied. There is no extra customization for depth effect that might need a live preview. You could just lock your device and see the preview from there. So this is also unnecessary imo.

I will try to add preview for battery styles. Thank you for the suggestion.

**Comment by srt54558** [comment]
> You already know which font you are using, you must've downloaded the font seeing its preview first. So font preview for clock is unnecessary.
> 
> Wallpaper depth effect doesn't need multiple reboots. You just select a wallpaper and its instantly applied. There is no extra customization for depth effect that might need a live preview. You could just lock your device and see the preview from there. So this is also unnecessary imo.
> 
> I will try to add preview for battery styles. Thank you for the suggestion.

Well some fonts look off, just like depth effect. But you're right, it can easily be viewed by locking the screen

**Comment by DHD2280** [comment]
Commit 3ce3c2c made battery styles visible in app.
