### ISSUE TITLE
After uninstalling. Trying to reinstall faults at 3 of 6 overlays built and says there is a log in docs but no logs there.

### ISSUE THREAD

**Issue by toolhas4degrees** [Mahmud0808/Iconify#325]
### Describe the bug

......... how can I fix this where is the directory these are made to? Can I delete said directory if you let me know. I don't know what else it could be.

### Expected behavior

Not able to reinstall and no logs kicked out

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. v4.0-Beta]
Pixel 8 pro a14 app ver 6.1.5

**Comment by HiFIi** [comment]
Hi there, you need to clear the app's data and also make sure you get rid of the magisk module too


I had the same issue as you and that fixed it for me

**Comment by Mahmud0808** [comment]
6.1.5 is very old version. Latest is 6.6.0
