### ISSUE TITLE
[Feature] Remove Customize Lockscreen button

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#328]
### Describe the feature

When I hold any place on the Lockscreen it shows a button to customize the clock. I always accidentally let it show. It gets so annoying.

### Why would it be useful to add?

To prevent accidental popups. You can still customize the Lockscreen in the background and styles app.

### Example(s)

![Screenshot_20231028-123308](https://github.com/Mahmud0808/Iconify/assets/90862487/b2ae480a-c2ca-4a23-9f17-e52f5cf60b2b)
![Screenshot_20231028-131007](https://github.com/Mahmud0808/Iconify/assets/90862487/fbe21887-8f5c-441c-9bed-47ec8e44bf66)

**Comment by Mahmud0808** [comment]
Added in PixelXpert https://github.com/siavash79/PixelXpert/commit/cace222d5882d7b4202b8e5fcf6668d6cdc9d11e
Use that instead.
