### ISSUE TITLE
[FEATURE] Font Style

### ISSUE THREAD

**Issue by popeye0013** [Mahmud0808/Iconify#329]
### Describe the feature

Set system font style (with custom font support)

### Why would it be useful to add?

This feature could be great for AOSP customisation because most of the AOSP custom roms don't have custom font option.

### Example(s)

Nothing ;(

### Additional context

Nothing ;(

**Comment by Mahmud0808** [comment]
[MFFM](https://t.me/MFFMMain) and [OMF](https://gitlab.com/nongthaihoang/oh_my_font/-/tree/master) are some of the good solutions for changing font system wide. I don't have any plan for this to add in iconify.
