### ISSUE TITLE
iconify on hentaiOS (android 14) pixel 7a

### ISSUE THREAD

**Issue by jocidodi** [Mahmud0808/Iconify#331]
### Describe the bug

I can install the iconify app, it asks for root privileges and access to all files, then it installes itself and it asks for reboot.
But after reboot it starts over to install itself and asks for reboot again, so i cannot use the app.

### Steps to reproduce

simply install the apk and start it.

### Expected behavior

install the app and start customization :)

### Device information

- Device: Pixel 7a
- OS: lynx-Ursamoon-ota-ud1a.230803.041-Furry.10151940
- App version: Iconify v6.5.1

**Comment by Mahmud0808** [comment]
Issue is with your root method (magisk/ksu settings). Not iconify issue. If you need help about that, join the telegram group and ask there.

Lemme give you some directions:
- Do not unmount modules (KSU/Magisk Delta)
- Magisk alpha compatibility is not guaranteed
- Do not enable core only mode in magisk (if you have the option)
- Allow iconify in SUlist (Magisk delta)
