### ISSUE TITLE
[BUG] Android 14 not applying basic/monet colors in all apps

### ISSUE THREAD

**Issue by bunnypig** [Mahmud0808/Iconify#333]
### Describe the bug

Once I've configured my basic colors and monet colors in color engine, it won't apply my colors in some parts. It won't apply it in the clock app, the "pin screen" (where you type in your pin code from lock screen) and some minor places.

I don't have many customization apps/modules installed except pixel xpert (preciously AOSP mods) or any other modules/LSPosed modules.
I'm on the latest version running android 14 on pixel 7 pro and I've given iconify root access and also given it permission for everything it requires. 

And a final note, I'm sorry if I've missed something or this behavior is to be expected, I've tried looking in issues/discussion but can't find anything other than some parts being "broken" on Android 14.
I love this app and I think you're doing a great job! 

### Steps to reproduce

1. Apply custom colors in color engine
2. Restart SystemUI
3. Open the clock app
4. Stock system colors are being used

### Expected behavior

Custom colors being applied system-wide

### Screenshots

![Screenshot_20231031-013341](https://github.com/Mahmud0808/Iconify/assets/10057285/2b02e5e6-1552-4d77-b238-52a993c69822)
![Screenshot_20231031-013333](https://github.com/Mahmud0808/Iconify/assets/10057285/32f40101-9b7f-4879-a399-3bd54a120106)
![Screenshot_20231031-013326](https://github.com/Mahmud0808/Iconify/assets/10057285/45bcb5ef-31f4-470b-846f-1c3fdfd2907f)

### Device information

- Device: Google Pixel 7 Pro
- OS: Stock Android 14 UP1A.231005.007
- App version: 6.5.1

**Comment by Mahmud0808** [comment]
Android 14 introduced some new color resources. Which aren't themed by iconify (yet, as of now).

Recently google updated their apps, google apps now create their own color palette instead of following system palette as far as I can understand. Even turning on pitch black mode doesn't have any effect on the apps. So there probably is nothing to do from my side (unless I can figure out a way to somehow bypass this behavior).

**Comment by HiFIi** [comment]
> Android 14 introduced some new color resources. Which aren't themed by iconify (yet, as of now).
> 
> Recently google updated their apps, google apps now create their own color palette instead of following system palette as far as I can understand. Even turning on pitch black mode doesn't have any effect on the apps. So there probably is nothing to do from my side (unless I can figure out a way to somehow bypass this behavior).

That's insane that they're doing that!! I wonder why they would

**Comment by bunnypig** [comment]
Appreciate the quick reply!
Doesn't that defeat the purpose of their idea of material you? It's insane that they did this.
Absolutely love the app and sorry to hear that they broke a working system. Great work none the less!

**Comment by Mahmud0808** [comment]
> Doesn't that defeat the purpose of their idea of material you?

They still match the colors and all (with their original implementation, not the custom colors). So technically it doesn't defeat the purpose.

**Comment by bunnypig** [comment]
> > Doesn't that defeat the purpose of their idea of material you?
> 
> They still match the colors and all (with their original implementation, not the custom colors). So technically it doesn't defeat the purpose.

Oh, I see. Thought they would only be using one color, thanks for answering!

**Comment by bunnypig** [comment]
> > Doesn't that defeat the purpose of their idea of material you?
> 
> They still match the colors and all (with their original implementation, not the custom colors). So technically it doesn't defeat the purpose.

Oh, I see. Thought they would only be using one color, thanks for answering!
