### ISSUE TITLE
[BUG] Brightness bar and other components in QS-panel are black although phone is set to white mode

### ISSUE THREAD

**Issue by elisenlebkuch** [Mahmud0808/Iconify#338]
### Describe the bug

 The brightness bar and VPN notification(?) in the QS-panel are black although the phone is set to white mode. They also stay black when I switch to dark mode.

### Steps to reproduce

I don't know exactly, it just appeared one day when I turned on energy saving mode for an hour or so.

### Expected behavior

I think they should be white.

### Screenshots

![Screenshot_20231105-132048_Lawnchair](https://github.com/Mahmud0808/Iconify/assets/127782512/27d15db1-dcce-43c6-bdbb-a282600d5ee7)
![Screenshot_20231105-132100_Lawnchair](https://github.com/Mahmud0808/Iconify/assets/127782512/57672ddf-6851-433b-b087-5e6959de1c6d)

### Device information

- Device: Fairphone FP3
- OS: DivestOS newest available
- App version: newest stable
- Launcher: Lawnchair v9.1 alpha 3

**Comment by Mahmud0808** [comment]
Fluid theme of iconify?

**Comment by elisenlebkuch** [comment]
Yes. Is it supposed to look like that then?

**Comment by Mahmud0808** [comment]
> Yes. Is it supposed to look like that then?

No, it's not. I'll check it out. Btw does your rom have black QS by default in light mode?

**Comment by elisenlebkuch** [comment]
No, it is a modified lineage rom, it has the default android color schemes.

**Comment by Mahmud0808** [comment]
Let me know if this https://github.com/Mahmud0808/Iconify/commit/6283e2e6efd940a1f202c9e8c0c38ae0a195a1f5 fixes your issue.

Edit: Everything should be fixed in latest debug. Hence closing this issue.
