### ISSUE TITLE
iconify on top level settings  (other version of iconify)

### ISSUE THREAD

**Issue by murdika** [Mahmud0808/Iconify#339]
### Describe the feature

Hi Dev, I really like the features in Iconify, I just want to request ,you build another version of Iconify , likely Iconify in top level settings,
thanks

### Why would it be useful to add?

just ordinary people we need other version ,

### Example(s)

thanks 

### Additional context

thanks

**Comment by HiFIi** [comment]
What?

**Comment by Mahmud0808** [comment]
Iconify is fine as an easily uninstallable app.
