### ISSUE TITLE
Decrease minimum UI Roundness

### ISSUE THREAD

**Issue by Misalf-git** [Mahmud0808/Iconify#34]
### Describe the feature

Possibility to decrease "Corner Radius" in "Extras" -> "UI Roundness" to 0dp (zero).
Current limit is 8dp.

### Why would it be useful to add?

Minimalism.

### Example(s)

![Screenshot](https://user-images.githubusercontent.com/72605561/212577184-6edcf85f-363f-4d00-9887-5c888c6ccec1.png)

### Additional context

- Android 12
- crDroid 8.8
- Samsung A20e

[SystemUI_crDroid-v8.8_Android-v12_Samsung_SM-A202F_a20e.zip](https://github.com/Mahmud0808/Iconify/files/10421701/SystemUI_crDroid-v8.8_Android-v12_Samsung_SM-A202F_a20e.zip)

**Comment by Misalf-git** [comment]
Forgot to add...

Iconify
Version Name: 5.0-Stable
Version Code: 6

**Comment by Mahmud0808** [comment]
Don't you think 0dp is way too much pointy? I thought people wouldn't like it.

**Comment by Misalf-git** [comment]
I guess taste can differ greatly. ;)

The idea is to remove "distraction" by reducing UI style to the necessary, mainly.

Back then, Substratum (or some theme) did provide settings that produced such results but it was Substratum.

**Comment by Misalf-git** [comment]
Did you just made this?

Thank you, looks pointy!

![Screenshot_pointy_1.png](https://user-images.githubusercontent.com/72605561/212673786-6b604ede-5ff7-4c06-b1ef-100344c2bab7.png)

**Comment by Mahmud0808** [comment]
Yes I made this. You are welcome.
