### ISSUE TITLE
Nothing Phone Big QS Panel Tiles not working

### ISSUE THREAD

**Issue by RafaeloxMC** [Mahmud0808/Iconify#344]
### Describe the bug

On the Nothing Phone (1), there are 2 big bubbles in the QS Panel. These are not being affected by QS Panel changes.

### Steps to reproduce

1. Scroll down to see the QS Panel (at this point everything looks perfectly fine)
![Screenshot_20231112-234337](https://github.com/Mahmud0808/Iconify/assets/53903394/a19f7882-3134-4a40-8f59-b626258e6b20)
2. Scroll down again to expand the settings
![Screenshot_20231112-234314](https://github.com/Mahmud0808/Iconify/assets/53903394/b949433e-ed44-475a-bf75-2433d8b52e8d)
As you can see, the two big bubbles dont have my selected border.

### Expected behavior

Have a border

### Screenshots

_See above_

### Device information

- Device: Nothing Phone (1) [A063]
- OS: NothingOS 2.0.4 (latest)
- App version: v6.6.0
- Magisk/KernelSU: Magisk 26.4 (26400)

**Comment by Mahmud0808** [comment]
Please read [FAQ](https://github.com/Mahmud0808/Iconify#-faq)
