### ISSUE TITLE
media controller

### ISSUE THREAD

**Issue by Turhvjbufv** [Mahmud0808/Iconify#354]
### Describe the feature

Add an option to add/remove buttons from media controller

### Why would it be useful to add?

With android 12/13 some roms removed/changed useful buttons on media controller (like close button) and I would like to have them back

### Example(s)

![Screenshot_1](https://github.com/Mahmud0808/Iconify/assets/91851160/a11f96f9-b842-4be9-8395-b0648aca8c88)
Example:Add an x(close) button where there is pink. (Or switch other button to do this)

**Comment by Mahmud0808** [comment]
Icons are now controlled by the music player itself starting from Android 13 and later. It's the music player which decides which icon to show and which icon to not show. Before android 13, it was controlled by SystemUI. So now it's up to the music player developers.
