### ISSUE TITLE
[FEATURE] Shizuku support

### ISSUE THREAD

**Issue by bropines** [Mahmud0808/Iconify#355]
### Describe the feature

Shizuku support. In fact, there is a repainter, but it is paid.

### Why would it be useful to add?

For non-rooted devices, this would be a very useful feature.

### Example(s)

https://play.google.com/store/apps/details?id=dev.kdrag0n.dyntheme

**Comment by bropines** [comment]
Yes, I read that in fact it works as a module, but is it possible to just make an add-on or a separate version for shizuku?

**Comment by Mahmud0808** [comment]
Shizuku support is not possible for iconify.
