### ISSUE TITLE
[FEATURE] homescreen grid

### ISSUE THREAD

**Issue by LostCat123** [Mahmud0808/Iconify#358]
### Describe the feature

The ability to disable grid on homescreen so icons doesn't snap in place/, or make the grid very dense but don't make the icon small 

### Why would it be useful to add?

This would be very useful for those who want their apps icons placed on various locations to match the wallpaper

This will allow us to precisely customize the homescreen

### Example(s)

There isn't any after searching for one

### Additional context

Thanks for your creations, I hope this isn't much 🥰

**Comment by Mahmud0808** [comment]
That's more like a launcher related feature. Please use any 3rd party launcher like Nova or Lawnchair.
