### ISSUE TITLE
[FEATURE] Standardize ROM spelling

### ISSUE THREAD

**Issue by TheRedCyclops** [Mahmud0808/Iconify#360]
### Describe the feature

I have noticed while using the app that ROM(s) is spelled 2-3 different ways across the app, maybe this could be standardized across the app?

### Why would it be useful to add?

in order to standardize the language across the app

### Example(s)

![Screenshot_20231127-195329_Iconify](https://github.com/Mahmud0808/Iconify/assets/76230780/700f00a6-960b-45d9-b19a-be483f9af26d)
![Screenshot_20231127-195438_Iconify](https://github.com/Mahmud0808/Iconify/assets/76230780/8ff0b08d-1458-40b8-bd62-f381a2a05932)
![Screenshot_20231127-195505_Iconify](https://github.com/Mahmud0808/Iconify/assets/76230780/19cc6d86-2878-45a2-aa44-f1df2411a9ac)
![Screenshot_20231127-195525_Iconify](https://github.com/Mahmud0808/Iconify/assets/76230780/27ffaded-0031-4806-970b-78ca08b6be62)

**Comment by Mahmud0808** [comment]
Fixed in crowdin source strings.
