### ISSUE TITLE
Remove no notification text on qs panel

### ISSUE THREAD

**Issue by eddro22** [Mahmud0808/Iconify#363]
### Describe the feature

By removing the no notification text it makes the qs panel cleaner 

### Why would it be useful to add?

By removing the no notification text it makes the qs panel cleaner with qs tiles and without 

### Example(s)

![Picsart_23-12-01_12-46-15-411](https://github.com/Mahmud0808/Iconify/assets/98064723/ce076604-88d0-4abf-88fe-fa81912ffe8f)

**Comment by Mahmud0808** [comment]
A module is already available for this [HERE](https://4pda.to/forum/index.php?showtopic=603033&view=findpost&p=68718343)
