### ISSUE TITLE
[BUG] Installation fails on Android 14 QPR2

### ISSUE THREAD

**Issue by robotfishe** [Mahmud0808/Iconify#366]
### Describe the bug

Installation crashes and puts the following in the logs:

Iconify bug report 04 Dec 2023 10:04:31
version: 6.6.0 (16)
build.brand: google
build.device: felix
build.display: AP11.231020.016.A1
build.fingerprint: google/felix_beta/felix:14/AP11.231020.016.A1/11113945:user/release-keys
build.hardware: felix
build.id: AP11.231020.016.A1
build.manufacturer: Google
build.model: Pixel Fold
build.product: felix_beta
build.type: user
version.codename: REL
version.release: 14
version.sdk_int: 34
iconify.version_name: 6.6.0
iconify.version_code: 16

error: Failed to build APK for AMAC

OnboardingCompiler - AAPT:
	/data/user/0/com.drdisagree.iconify/files/Overlays/android/AMAC/res/color/ripple_material_light.xml:3: error: No resource identifier found for attribute 'alpha' in package 'android'
	
	/data/user/0/com.drdisagree.iconify/files/Overlays/android/AMAC/res/color/ripple_material_light.xml:3: error: No resource identifier found for attribute 'color' in package 'android'
	
	/data/user/0/com.drdisagree.iconify/files/Overlays/android/AMAC/res/color/ripple_material_light.xml:3: error: Error: No resource found that matches the given name (at 'color' with value '@*android:color/holo_blue_light').
	

### Steps to reproduce

Activate module in lsposed and try to install

### Expected behavior

Installation should complete without crashing

### Device information

- Device: Pixel Fold
- OS: Android 14 QPR2 beta
- App version: 6.6
- Magisk/KernelSU: Magisk 26

**Comment by Tobapuww** [comment]
Are you trying to do an initial install before LSPosed activates it?

**Comment by Tobapuww** [comment]
> 您是否尝试在 LSPosed 激活它之前进行初始安装？

According to the developer, this program does not support Android 14 QPR2 at present.

**Comment by abun880007** [comment]
I have same issue the latest Iconify debug #1704 the installation stops at step 3 installing apk's  I wanted to give you my log files from my Pixel 7 Pro on A14 QPR2 Beta 2 with latest Magisk Delta and lsposed 7049 latest canary.


log file contents

Iconify bug report 17 Dec 2023 14:13:53
version: 6.6.0 Dev (#1704) (1704)
build.brand: google
build.device: cheetah
build.display: AP11.231117.006
build.fingerprint: google/cheetah_beta/cheetah:14/AP11.231117.006/11174680:user/release-keys
build.hardware: cheetah
build.id: AP11.231117.006
build.manufacturer: Google
build.model: Pixel 7 Pro
build.product: cheetah_beta
build.type: user
version.codename: REL
version.release: 14
version.sdk_int: 34
iconify.version_name: 6.6.0 Dev (#1704)
iconify.version_code: 1704

error: Failed to build APK for QSDT

OnboardingCompiler - AAPT:
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@*android:style/Theme.DeviceDefault'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:14: error: Error: No resource found that matches the given name: attr '*android:colorSurfaceHeader'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:5: error: Error: No resource found that matches the given name: attr 'android:alertDialogTheme'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:10: error: Error: No resource found that matches the given name: attr 'android:colorAccent'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:6: error: Error: No resource found that matches the given name: attr 'android:colorControlNormal'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:12: error: Error: No resource found that matches the given name: attr 'android:colorError'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:9: error: Error: No resource found that matches the given name: attr 'android:colorPrimaryDark'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:11: error: Error: No resource found that matches the given name: attr 'android:colorSecondary'.
	
	/data/user/0/com.drdisagree.iconify.debug/files/Overlays/android/QSDT/res/values-night/styles.xml:13: error: Error: No resource found that matches the given name: attr 'android:forceDarkAllowed'.

**Comment by bikram-agarwal** [comment]
Another data point - 

Same crash (at step 3/6) on my device - 

Pixel 7 Pro, running Android 14 QPR3 Beta 1
Iconify v6.7.0
Root permission and storage permission granted.

**Comment by Mahmud0808** [comment]
Fixed in 7eaa11f93258592a6a801aff115494c7df0705bf
