### ISSUE TITLE
Battery drain in Android 13 GSI while using statusbar clock chip

### ISSUE THREAD

**Issue by fluffball3** [Mahmud0808/Iconify#368]
### Describe the bug

Battery drains very fast when statusbar clock chip is turned on. Under battery usage system ui drains 80% of the battery while it is enabled. The device also gets hot even while idling while screen is on.

### Steps to reproduce

1. Go to Tweaks then Xposed
2. Click on Background chip
3. Turn on statusbar clock chip (status icon chip also seems to have the problem although didn't check usage)
4. See battery drain in battery usage also high device temp

### Expected behavior

No considerable battery drain 

### Device information

- Device: [Samsung M33]
- OS: [CrDroid GSI 9.10 Android 13]
- App version: [6.6.0]
- Magisk/KernelSU: [Kitsune Mask 26401]

**Comment by Mahmud0808** [comment]
Provide logs

**Comment by fluffball3** [comment]
> Provide logs

I dunno how to export logs

**Comment by fluffball3** [comment]
OK so I tried using Matlog to see what was happening. When I turn on statusbar clock chip the matlog doesn't show logs anymore and is almost static but any other option even status icon chip doesn't pose problems and matlogs floods logs as usual

**Comment by Mahmud0808** [comment]
Seems like GSI specific issue. Share LSPosed log.

**Comment by fluffball3** [comment]
[LSPosed_2023-12-06T18_19_38.188974.zip](https://github.com/Mahmud0808/Iconify/files/13583058/LSPosed_2023-12-06T18_19_38.188974.zip)
This is the modules log

**Comment by Mahmud0808** [comment]
> [LSPosed_2023-12-06T18_19_38.188974.zip](https://github.com/Mahmud0808/Iconify/files/13583058/LSPosed_2023-12-06T18_19_38.188974.zip) This is the modules log

This log contains lots of error from PixelXpert but none from Iconify.

Try disabling iconify and see if you still have battery drain issue. Then enable again and check.

**Comment by fluffball3** [comment]
Matlog still crashes even after uninstalling PixlExpert 
![Screenshot_20231206-184058_MatLog](https://github.com/Mahmud0808/Iconify/assets/132234302/4064ecdc-26b4-45c1-9d8d-11150cd2ac8e)
![Screenshot_20231206-183929_MatLog](https://github.com/Mahmud0808/Iconify/assets/132234302/7ed63a92-620b-461c-b4cc-93ef1386d397)
![Screenshot_20231206-185706_MatLog](https://github.com/Mahmud0808/Iconify/assets/132234302/cca23b00-b0bf-4365-95d3-272c2215e47a)
Can't export logs cuz matlog runs at 2 fps when the chip option is on

**Comment by Mahmud0808** [comment]
Use some other logcat reader

**Comment by fluffball3** [comment]
Got it with logfox!
[08_12-19-27-29_638.log.zip](https://github.com/Mahmud0808/Iconify/files/13614754/08_12-19-27-29_638.log.zip)

**Comment by Mahmud0808** [comment]
I might be wrong but I don't see anything wrong [Here](https://github.com/Mahmud0808/Iconify/blob/beta/app/src/main/java/com/drdisagree/iconify/xposed/modules/BackgroundChip.java#L425)

This might be a GSI specific bug, if that's the case then it's out of my hand to fix.

**Comment by fluffball3** [comment]
Oh well that's sad. Anyway thanks for ur reply! Really appreciate it!
