### ISSUE TITLE
Exclamation mark cuts off mobile icon (Status Bar icon issue)

### ISSUE THREAD

**Issue by MoritzFlyy** [Mahmud0808/Iconify#37]
### Describe the bug

Exclamation mark cuts off mobile icon. (Status Bar icon issue)

### Steps to reproduce

Displayed when the connection is established.
For example, after deactivating flight mode.

### Expected behavior

...

### Screenshots

![Screenshot_20230118-172742~3](https://user-images.githubusercontent.com/95381930/213241469-d4d54de9-41b5-423d-953a-24bdabe61636.png)
![Screenshot_20230118-172740~2](https://user-images.githubusercontent.com/95381930/213241474-5ae852ed-6fb7-4afd-ad02-7435eb7e8f5f.png)

### Device information

Device: Xperia 1 IV
OS: A13
App-Version: 5.0 - Stable

**Comment by Mahmud0808** [comment]
Are you sure it's related to iconify and not your rom issue? Cause I don't remember tweaking that exclamation mark.

**Comment by ghost** [comment]
> Are you sure it's related to iconify and not your rom issue? Cause I don't remember tweaking that exclamation mark.

I think it is rather due to Iconify. With the "Acherus" icon pack for example, the cutout section is much smaller than with "Filled".
![Screenshot_20230118-184152~3](https://user-images.githubusercontent.com/95381930/213256845-cb629265-76f8-4d03-8ea9-81e3551edbf4.png)

**Comment by Mahmud0808** [comment]
> I think it is rather due to Iconify. With the "Acherus" icon pack for example, the cutout section is much smaller than with "Filled". ![Screenshot_20230118-184152~3](https://user-images.githubusercontent.com/95381930/213256845-cb629265-76f8-4d03-8ea9-81e3551edbf4.png)

The first 4 icon packs are by me. Others are taken from custom AOSP roms. So I don't think I can do much about it except adding a new option to totally remove that exclamation mark.

**Comment by ghost** [comment]
> > I think it is rather due to Iconify. With the "Acherus" icon pack for example, the cutout section is much smaller than with "Filled". ![Screenshot_20230118-184152~3](https://user-images.githubusercontent.com/95381930/213256845-cb629265-76f8-4d03-8ea9-81e3551edbf4.png)
> 
> The first 4 icon packs are by me. Others are taken from custom AOSP roms. So I don't think I can do much about it except adding a new option to totally remove that exclamation mark.

The option to remove it would be more than sufficient. The icon itself is quite unnecessary anyway.

**Comment by Mahmud0808** [comment]
Try [this mod](https://t.me/cool_modules/114) first cause hiding it programmatically will require lsposed and kinda not easy to do.

**Comment by ghost** [comment]
> Try [this mod](https://t.me/cool_modules/114) first cause hiding it programmatically will require lsposed and kinda not easy to do.

Really? Didn’t know something like this existed, it works great!
Thanks!
