### ISSUE TITLE
[FEATURE] Disable FOD if screen is off or on the AOD

### ISSUE THREAD

**Issue by Senliast** [Mahmud0808/Iconify#371]
### Describe the feature

Stop the under-display fingerprint (or capacitive fingeprint) from listening, when the screen is off or on the Always-On-Display. Turn it on only after the display has been turned on. Make the fingerprint not wake the phone when there are no fingerprint enrolled as well.

### Why would it be useful to add?

I often accidentally hit the sensor when i just want to take the phone from table or have it in the pocket. It counts as failed unlock attempt and then the fingerprint gets disabled. Neither the stock Android nor any other module have an option to disable it - the fingerprint is always enabled when the screen is off. Therefore it would be great if you could add this feature.

### Example(s)

For example, Samsung have it: https://www.youtube.com/watch?app=desktop&v=2re9PtMGbKo

**Comment by Mahmud0808** [comment]
I suggest you to request this feature in [PixelXpert](https://github.com/siavash79/PixelXpert) instead. Iconify is for customization, Your feature request doesn't fall into any customization category.

**Comment by Senliast** [comment]
@Mahmud0808 i already did, but it was rejected: https://github.com/siavash79/PixelXpert/issues/746

**Comment by Mahmud0808** [comment]
I don't have FOD so can't help either.
