### ISSUE TITLE
[BUG] Toast Frame looks off on December OTA

### ISSUE THREAD

**Issue by cozykitten** [Mahmud0808/Iconify#376]
### Describe the bug

when setting a custom toast frame the border roundness is a bit off.
![image](https://github.com/Mahmud0808/Iconify/assets/116394977/3ac3a739-09f4-4aef-9004-2968560bf57a)

### Steps to reproduce

1. Apply custom toast frame

### Expected behavior

should look round like before

### Device information

- Device: Pixel 6a
- OS: A14 231205
- App version: 6.6.0
- Magisk/KernelSU: Magisk 26.4

**Comment by Mahmud0808** [comment]
Re-apply UI Roundness.
