### ISSUE TITLE
[BUG] keyboard height issue when using immersive option in navigation bar options (since December OTA)

### ISSUE THREAD

**Issue by cozykitten** [Mahmud0808/Iconify#377]
### Describe the bug

When using either Immersive, Immersive v2 or Immersive v3 the keyboard spacing is always minimal, the same what I'd expect only from v3 (I've never used v3 so Idk how it actually looks, always v2 and that was bigger).
If you need some sort of logs please let me know which command to use or where to find them.

### Steps to reproduce

1. Go to Navigation bar options
2. Click on Immersive or Immersive v2 or Immersive v3 and Hide Pill (I use Hide Pill but I have the same issue without)

### Expected behavior

Immersive v2 should have a bigger spacing than v3 (just like before December OTA) and Immersive likewise even bigger spacing than v2.

### Screenshots

![image](https://github.com/Mahmud0808/Iconify/assets/116394977/464d3f51-f2e2-428e-82f4-b475e806d987)

### Device information

Device: Pixel 6a
OS: A14 231205
App version: 6.6.0
Magisk/KernelSU: Magisk 26.4

**Comment by Mahmud0808** [comment]
It is linked in latest December sp. Only thing you can do now is hide the keyboard buttons.
