### ISSUE TITLE
[FEATURE] Call recording announcement for google dialer

### ISSUE THREAD

**Issue by bigjackwww** [Mahmud0808/Iconify#380]
### Describe the feature

Add option to remove call recording announcement for google dialer

### Why would it be useful to add?

Because it's annoying when you're recording the call, and even when the call ends when recording

### Example(s)

For example,App PixelXpert has this option in "Phone & Dialer"

**Comment by HiFIi** [comment]
Gappsmod already does it, GMS flags already does it, pixel xpert already does it
