### ISSUE TITLE
[BUG] QS clock is wrong colored while using "light theme"

### ISSUE THREAD

**Issue by lvyin555** [Mahmud0808/Iconify#381]
### Describe the bug

I set the background color of my "clock chip" to the lighter color of the Monet color on my mobile phone, and set the font color to dark, but the font color should have been unified in the quick settings. The original white, but they occasionally go wrong and keep the color I set.In addition, I hope that when choosing the font color in the chip to follow the theme, it is not just white, but I hope that they can also use dark fonts that combine the color of my mobile phone in dark mode to match the light-colored chip.

### Expected behavior

。

### Device information

- Device: [e.g. Redmi K40Pro]
- OS: [e.g. stock ROM Android version 13.0 QPR3]
- App version: [e.g. v6.5.1]
- Magisk/KernelSU: [e.g. Magisk Delta 26.4]

**Comment by Mahmud0808** [comment]
Can you provide some screenshots of your issue? I haven't quite understood it.

**Comment by lvyin555** [comment]
> 您能提供一些您的问题的屏幕截图吗？我还不太明白。



> Can you provide some screenshots of your issue? I haven't quite understood it.

![Screenshot_20240116-001302_Chrome](https://github.com/Mahmud0808/Iconify/assets/89643112/73f533da-d1e5-4dab-832b-f82292295753)

Sorry, I just saw your reply now. I just restarted the system ui to make this problem disappear. The above is a screenshot when there is no problem, but after the problem occurs, the clock on the picture will turn black.
By the way, I tried turning off the "clock chip" function, but it didn't work. It still caused the clock color to turn black after the phone restarted.

**Comment by Mahmud0808** [comment]
> By the way, I tried turning off the "clock chip" function, but it didn't work. It still caused the clock color to turn black after the phone restarted.

Then maybe it's not an issue of iconify?

**Comment by lvyin555** [comment]
> > By the way, I tried turning off the "clock chip" function, but it didn't work. It still caused the clock color to turn black after the phone restarted.
> 
> Then maybe it's not an issue of iconify?

In my memory, this is a problem that occurs after using iconify's "clock chip"
The picture below is a screenshot after the problem occurred. I will try to close iconify to troubleshoot the problem.

![Screenshot_20240116-115006_QQ](https://github.com/Mahmud0808/Iconify/assets/89643112/0bd6303d-bf70-4ab6-afa0-da1a93ad6ba0)

**Comment by lvyin555** [comment]
> > By the way, I tried turning off the "clock chip" function, but it didn't work. It still caused the clock color to turn black after the phone restarted.
> 
> Then maybe it's not an issue of iconify?

By the way, in addition to the "Clock Chip" feature, I only enabled the following two items, which happen to be where the problem occurred, and now I have them turned off for troubleshooting
![Screenshot_20240116-115754_Iconify](https://github.com/Mahmud0808/Iconify/assets/89643112/0bd34d4c-66ec-4730-8ae3-f81c40ac3240)

**Comment by lvyin555** [comment]
> > > By the way, I tried turning off the "clock chip" function, but it didn't work. It still caused the clock color to turn black after the phone restarted.
> > 
> > 
> > Then maybe it's not an issue of iconify?
> 
> By the way, in addition to the "Clock Chip" feature, I only enabled the following two items, which happen to be where the problem occurred, and now I have them turned off for troubleshooting ![Screenshot_20240116-115754_Iconify](https://private-user-images.githubusercontent.com/89643112/296928062-0bd34d4c-66ec-4730-8ae3-f81c40ac3240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTY5NzAsIm5iZiI6MTcwNTM5NjY3MCwicGF0aCI6Ii84OTY0MzExMi8yOTY5MjgwNjItMGJkMzRkNGMtNjZlYy00NzMwLThhZTMtZjgxYzQwYWMzMjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA5MTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MjI3ZmRlY2NlYTA0N2M3Mjc3N2M5MDFhZTE5NTE0MTlkYTIyYjY5Yzc5NTYxZDEzOTExYzNmNTU0ZDUwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MNULEf5I3CN88n8-vLFh_0T0UuYuM1qgJoCgxSlt-P8)

I turned off all features of iconify and restarted the phone. After waiting for a long time, none of the problems I described appeared. I suspect this is the problem

**Comment by Mahmud0808** [comment]
Should be fixed in https://github.com/Mahmud0808/Iconify/commit/e508fee2300b91609b5faf61d5faa7daad7f7c41 Re-open if still not fixed
