### ISSUE TITLE
[BUG] "Failed to open APK" spammed in logcat - expected?

### ISSUE THREAD

**Issue by PowerUser64** [Mahmud0808/Iconify#383]
### Describe the bug

This feels like a bug, so I am reporting it as one.

I decided to take a look at my system logs today and I noticed many repeated errors stating the following:

```
12-15 09:03:29.458 16283 16318 E gle.android.gms: Failed to open APK '/product/overlay/IconifyComponentQSNPT.apk': I/O error
12-15 09:03:29.461 16283 16318 E gle.android.gms: Failed to open APK '/product/overlay/IconifyComponentIPAS4.apk': I/O error
12-15 09:03:29.465 16283 16318 E gle.android.gms: Failed to open APK '/product/overlay/IconifyComponentAMAC.apk': I/O error
```

There are so many of these that it takes up more than 10,000 lines in my terminal. Is this normal or expected behavior?

### Steps to reproduce

1. Have an iconify config that uses AMAC, QSNPT, or IPAS4. (unsure what the last one is) ([cheatsheet](https://github.com/Mahmud0808/Iconify/blob/a1a72a01d2340dddf045cfdaf8763267cb5086ef/app/src/main/assets/Overlays/android/cheatsheet))
2. Blacklist `com.google.android.gms` in the magisk deny list
3. Check logcat

### Expected behavior

Ideally the system log would not be spammed with error messages. Mostly I just want to know if this _is_ expected.

### Screenshots

Logs provided above.

### Device information

- Device: Pixel 3a
- OS: [Unofficial Lineage OS 20](https://xdaforums.com/t/official-lineageos-20-for-the-pixel-3a.4514859/)
- App version: v6.6.0
- Magisk/KernelSU: Official Magisk 26.4 (26400)

**Comment by Mahmud0808** [comment]
It is a normal expected behavior. When an app is in the denylist, it shouldn't know about what system modifications we have done. If it knows we have modified the system, it will know we have rooted the device or the system is not secured and hence throw an error (like banking apps). This is nothing to worry about, you can ignore it.

**Comment by PowerUser64** [comment]
Alright, good to know. Thanks!
(and ty for the quick response!:)
