### ISSUE TITLE
[COMPATIBILITY] Add KernelSU flashable volume control module

### ISSUE THREAD

**Issue by areyoudeveloper** [Mahmud0808/Iconify#385]
### Describe the feature

KernelSU Modules support

### Why would it be useful to add?

Because most user moved to KernelSU

### Example(s)

Its flashable  like magisk modules

**Comment by Mahmud0808** [comment]
The volume panel moule is based on [SystemUI-Patcher](https://github.com/jairaj08/SystemUI-Patcher). It has not been updated to support KSU yet. So kindly ask in the respected support group [Cool Modules](https://t.me/cool_modules69) for KSU support or any other query about it.
