### ISSUE TITLE
Lockscreen Clock font not changing

### ISSUE THREAD

**Issue by theLabro** [Mahmud0808/Iconify#387]
### Describe the bug

The custom clock font in the Lockscreen Clock customization under the Xposed Menu is not working properly, I'm on the latest build and tried various otf/ttf fonts but it didn't work, it stays on the default font. Being a feature it should work properly for every devices running following requirements and hopefully it'll be fixed soon
![Screenshot_20231219-033649_Iconify](https://github.com/Mahmud0808/Iconify/assets/83789308/928b56c3-04df-4e68-88df-62b2063bc5e8)

### Steps to reproduce

1. Go to Tweaks
2. Scroll to the 'Xposed Menu' 
3. Click on 'Lockscreen Clock'
4. Enable Custom Lockscreen
5. Click on the 'Pick Font' button
6. See error 

### Expected behavior

Hopefully it'll be fixed in upcoming versions

### Device information

- Device: Redmj K20 Pro/Mi 9T Pro
- OS: Custom ROM Android version 14.0 QPR2
- App version: v6.6.0
- Magisk/KernelSU: KernelSU v11335

**Comment by Mahmud0808** [comment]
If custom clock is being shown on lockscreen, then font should work too. Make sure the font exists in internal storage/.iconify_files
