### ISSUE TITLE
[BUG] Android 12.1 pantalla negra luego de activar "Solo Sombra de Notificaciones Transparente".

### ISSUE THREAD

**Issue by AlvaroOctavio** [Mahmud0808/Iconify#388]
### Describe the bug

Tras activar esta opción la pantalla se pone negra, aunque reinicie el dispositivo, en un momento se pone el fondo de la pantalla pero luego se pone negra la pantalla y no me queda otra opción que borrar una carpeta de Iconify a través del nodo Recovery

### Steps to reproduce

1. Go to 'Retoques"
2. Click on 'Menú Xposed"
3. Click on "Transparencia & Desenfoque "
4. Click on  'Solo Sombra de Notificaciones Transparente"

### Expected behavior

Y bueno... La opción lo dice, hacer transparente la sección de notificaciones nomás 

### Device information

- Device: Moto G20
- OS: SQ3A.220705.004
PixelExperience_Plus_treble_arm64_bvN-12.1-20221118-0806-UNOFFICIAL
- App version: 6.6.0 
- Magisk Version : 26.4

**Comment by Mahmud0808** [comment]
Attach LSPosed logs

**Comment by AlvaroOctavio** [comment]
After spending all night reinstalling Iconify, seeing which Magisk module or application was the cause of this error, I think it was just the Launcher Lawnchair module, sorry for my clumsiness and for creating this useless space 😅😅 (Translated by Google)
