### ISSUE TITLE
Crashes Android system

### ISSUE THREAD

**Issue by TRESPSSR** [Mahmud0808/Iconify#389]
### Describe the bug

December security update somehow broke applying custom QS styles. I applied some features and it worked fine, but when I selected custom QS tiles my system crashed and it wasn't able to launch normally even in safe mode for a couple of times.

### Steps to reproduce

Pixel 6 December update
QS stiles apply

### Expected behavior

Won't be able to launch, bootloop

### Device information

- Device: [Google Pixel 6]
- OS: [stock rom 14 (UQ1A.231205.015)]
- App version: [latest]
- Magisk: [e.g. Magisk stable 26.4]

**Comment by Mahmud0808** [comment]
Duplicate of #278

**Comment by TRESPSSR** [comment]
Quick hotfix with simple notification will be nice, so people don't break their phones 😀

**Comment by Mahmud0808** [comment]
> Quick hotfix with simple notification will be nice, so people don't break their phones 😀

I don't have push notification system in Iconify. And I have been trying to fix this issue for a few months now and no luck.

**Comment by TRESPSSR** [comment]
Something like a warning message maybe
