### ISSUE TITLE
[FEATURE] APatch support

### ISSUE THREAD

**Issue by anaelle-dev** [Mahmud0808/Iconify#397]
### Describe the feature

Please add support for APatch
https://github.com/bmax121/APatch

### Why would it be useful to add?

It would allow Iconify to work on a new root solution 

### Example(s)

![Screenshot_20240106-232104](https://github.com/Mahmud0808/Iconify/assets/63869398/86ab45d6-615d-421b-99bb-95809188ad1d)
![Screenshot_20240106-232124](https://github.com/Mahmud0808/Iconify/assets/63869398/5b204831-d1b9-446a-8612-56bd7754e94c)
![Screenshot_20240106-231808](https://github.com/Mahmud0808/Iconify/assets/63869398/283dd8a8-1b44-4a97-adb5-441d6fffaf02)

**Comment by HiFIi** [comment]
This project is dead

**Comment by Mahmud0808** [comment]
Added in 21bf899fb8197d47486846024589feb464b20a15
