### ISSUE TITLE
Request User Confirmation to Set UI Corner Radius

### ISSUE THREAD

**Issue by Kruegerrr** [Mahmud0808/Iconify#4]
First, thanks for making such an awesome app!
In Extras, UI Corner Radius can be modified by a slider. However, I find it difficult to get the value I want, worse yet, the change is applied immediately without confirmation, which makes my phone sluggish. Could you please add a button to apply the change?

**Comment by Mahmud0808** [comment]
Okay I will add a confirmation button as well as a live preview.
