### ISSUE TITLE
[FEATURE] Decrease the distance between icons in statusbar

### ISSUE THREAD

**Issue by bomzhellino** [Mahmud0808/Iconify#401]
### Describe the feature

Hello. Please consider this request.
Decrease the distance between icons in statusbar like in this patch
https://github.com/eremitein/treble-patches/blob/caos/patches/personal/frameworks_base/0079-tuning-statusbar-looking.patch

### Why would it be useful to add?

This is very useful for devices with a large notch.

### Example(s)

Unable to do a screenshot because i'm on a new ROM now.
But it's obvious: the icons are spaced closer together.
Once again the link to the patch:
https://github.com/eremitein/treble-patches/blob/caos/patches/personal/frameworks_base/0079-tuning-statusbar-looking.patch

**Comment by HiFIi** [comment]
This project is dead according to the developer

**Comment by Mahmud0808** [comment]
This requires all the statusbar icons to be replaced with modified icons, which will break usage of custom icon packs.
