### ISSUE TITLE
Depth wallpaper not working on android 14

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#403]
### Describe the bug

The depth wallpaper feature does not work on android 14.

### Steps to reproduce

1. Create depth wallpaper with front and back image
2. Enable
3. Background applied, but foreground is not above clock

### Expected behavior

The foreground image should be above the Lockscreen clock

### Device information

- Device: Pixel 8 Pro
- OS: Android 14 January update 
- App version: 6.6.0
- Magisk/KernelSU: Magisk 26.4

**Comment by Viniui** [comment]
If you don't have supporting device then it doesn't work or Turn off your carousel wallpapers

**Comment by HiFIi** [comment]
This project is dead

**Comment by Mahmud0808** [comment]
You have to enable custom lock screen clock along with depth wallpaper as mentioned in-app. Otherwise it won't work.

**Comment by srt54558** [comment]
> You have to enable custom lock screen clock along with depth wallpaper as mentioned in-app. Otherwise it won't work.

Now it does indeed work. Sorry.
But why does "at a glance" get disabled tho?

And is this project really dead? 😟

**Comment by Mahmud0808** [comment]
> Now it does indeed work. Sorry. But why does "at a glance" get disabled tho?

Trade-off. It seemed easier to remove at a glance and add clock to avoid animation conflicts.

> And is this project really dead? 😟

Project is currently on hiatus. Related discussion #394
