### ISSUE TITLE
[FEATURE] Add option to hide notification buttons

### ISSUE THREAD

**Issue by harphere** [Mahmud0808/Iconify#408]
### Describe the feature

When the notification shade is pulled down, there are 2 buttons that appear: Manage and Silent. It would be nice to be able to hide/remove those buttons.  

### Why would it be useful to add?

Aesthetics mainly; for a cleaner looking notification shade. 

### Example(s)

![Marked notification shade](https://github.com/Mahmud0808/Iconify/assets/28116390/0082bae7-a91b-42d4-b2e0-6dffbfc3c7a8)

### Additional context

In A13 can be done via status_bar_notification_footer.xml for Manage button make height and width 0dp.

**Comment by HiFIi** [comment]
This app is dead

**Comment by harphere** [comment]
This is great, thank you!
