### ISSUE TITLE
Problems with Immersive spacing for the Keyboard Navigation Bar.

### ISSUE THREAD

**Issue by ukriu** [Mahmud0808/Iconify#409]
### Describe the bug

The keyboard (any), overlaps with the navbar, Causing a mess. You can see the overlap taking place in the screenshots I've provided. 
The keyboard should start a bit sooner, but it just overlaps the nav bar on these modes. You can see this clearly with the screenshots where the element borders are shown.

### Steps to reproduce

1. Be on Android 14 (AOSP, I think.)
2. Turn on any Immersive Keyboard Spacing
3. View the keyboard

Optional: Go to Developer Options > Turn on "Show Layout Bounds"

### Expected behavior

Keyboard and Navbar should not overlap.

### Screenshots

![Screenshot_20240127-213911_Nova Launcher~2](https://github.com/Mahmud0808/Iconify/assets/80760888/4b9db390-8d3a-40b3-9122-56fd9e629ef3)
![Screenshot_20240127-214221_Nova Launcher~2](https://github.com/Mahmud0808/Iconify/assets/80760888/6bb0e3fa-4fdf-4ea5-848d-d0e8a7cddc86)
![Screenshot_20240127-214246_Nova Launcher~2](https://github.com/Mahmud0808/Iconify/assets/80760888/b154b235-e9de-43e6-8cab-41193725b6b8)
![Screenshot_20240127-214313_Nova Launcher~2](https://github.com/Mahmud0808/Iconify/assets/80760888/0815bfad-e0c0-4356-9ab5-ee9a216f9e0c)

### Device information

- Device: Redmi S2/Y2 [YSL]
- OS: LineageOS 21, Android 14
- LineageOS Version: 21-20240115-UNOFFICIAL-ysl
- App version: 6.6.0
- Magisk/KernelSU: Magisk 26.4

**Comment by Mahmud0808** [comment]
This has been an issue with android 14. I suggest you to either hide keyboard buttons, or use the module from [dmgk](https://t.me/dnmgsk) instead.

**Comment by ukriu** [comment]
> This has been an issue with android 14. I suggest you to either hide keyboard buttons, or use the module from [dmgk](https://t.me/dnmgsk) instead.
@Mahmud0808 

Even if i hide the buttons, There is no spacing.
Also I can't use the dmgk module as I can't select options because my Volume Down key is broken.
I know this is kind of a personal skill issue, but I'm just putting it out there.

**Comment by Mahmud0808** [comment]
> I can't use the dmgk module as I can't select options because my Volume Down key is broken. I know this is kind of a personal skill issue, but I'm just putting it out there.

You can try modifying the module, or ask for help in dmgk group. The dev is very friendly and helpful.

**Comment by ukriu** [comment]
> You can try modifying the module, or ask for help in dmgk group. The dev is very friendly and helpful.

Fair enough, Thank you!
