### ISSUE TITLE
[BUG] UI roundness doesn't apply to QS.

### ISSUE THREAD

**Issue by nihal697** [Mahmud0808/Iconify#41]
### Describe the bug

UI roundness isnt applying to qs.

### Steps to reproduce

change ui roundness in extras option.

### Expected behavior

qs roundness should also change

### Screenshots

![Screenshot_20230127-154542_Trebuchet](https://user-images.githubusercontent.com/47318989/215063436-da7ca923-1bba-4da8-879a-6cb78133cbdc.png)
![Screenshot_20230127-154550_Trebuchet](https://user-images.githubusercontent.com/47318989/215063447-588223e2-5c9f-4ba9-8bb4-def824f524fe.png)

### Device information

- Device: [Xiaomi Redmi Note 11]
- OS: [Lineageos ROM Android version 13.0]
- App version: [5.0 Stable]

**Comment by Mahmud0808** [comment]
UI roundness only works if you are using custom QS shapes from iconify.

**Comment by nihal697** [comment]
> UI roundness only works if you are using custom QS shapes from iconify.

Oh got it, my bad, thanks.
