### ISSUE TITLE
[FEATURE] One shot auto-brightness

### ISSUE THREAD

**Issue by yunusarkan** [Mahmud0808/Iconify#413]
### Describe the feature

I am requesting for a very usefull and small feature, that named as "one shot auto-brightness". This feature triggers brightness sensor only when waking up the screen and then fixes the brightness value until turning the screen off. 

### Why would it be useful to add?

You don't experience fluctuation on brightness when using the phone but you get the advantage of brightness sensor by adjusting the brightness for one time.

### Example(s)

Here are some resources if any case its needed;

https://gerrit.aicp-rom.com/c/AICP/packages_apps_Settings/+/116959
https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/369988/2

Thanks.

**Comment by Mahmud0808** [comment]
I suggest you to request this feature on PixelXpert or somewhere else. This is out of the scope of this app's purpose.
