### ISSUE TITLE
[BUG] QS Text Not White

### ISSUE THREAD

**Issue by AngryManMLS** [Mahmud0808/Iconify#415]
### Describe the bug

The text on the QS is not white even with the options turned on for it to be white. This is especially noticable on QS themes such as "Thin Outline" where the text is unreadable. I've even adjusted around the options in the newly added Xposed options however this does not fix the issue I still have black text.

### Steps to reproduce

Install Iconify on current Android 14 on Pixel 8 Pro aka Husky.

### Expected behavior

When I select either all white text or follow system theme in Xposed options it should alter the QS text. However I still get black text. In contrast upon testing on Pixel 7 (Cheetah) also running QPR1 December it adjust these things just fine.

### Screenshots

![Screenshot_20240129-191237](https://github.com/Mahmud0808/Iconify/assets/5227592/3e2ebf45-2e0d-4013-bd44-0d58b9b47255)
![Screenshot_20240129-184916](https://github.com/Mahmud0808/Iconify/assets/5227592/20e5a2b3-98cf-44dc-ad9e-6e6b300eaca4)

### Device information

- Device: Pixel 8 Pro aka Husky
- OS: Android 14 QPR 1 January 2024 Stable UQ1A.240105.004
- App version: 6.7.0 Stable
- Magisk/KernelSU: 26.4 Stable
- LSPosed: 1.9.2 debug (7058) also tested on 1.9.2 stable (7024) to the same results.

**Comment by Mahmud0808** [comment]
I will look into it. If you can help me with testing, then contact in the telegram group (link in README.md).

Edit: Also share your systemui apk from /system/system_ext/priv-app/

**Comment by AngryManMLS** [comment]
Would SystemUIGoogle.apk work? After I sent the initial message to you I switched over to SigmaDroid on my Husky. I did pull the SystemUIGoogle.apk from the January update. If need to be I can flash the January build back on my Husky then pull it from there.

Also I would gladly jump on the Iconify Telegram in fact I used to be on there until I got banned on there under my Telegram username TheLoonyRebel (Husky Pixel 8 Pro) after I got into a spat with eleo (I think that's the name) over on the PixelXpert room a few months ago. Basically I was informing the PixelXpert room on a few minor issues that was happening on early ROM builds with their mod. I understand PixelXpert is for stock firmware but I still wanted to get that information documented for others using PixelXpert on ROMs. eleo got upset at me and was questioning why me (an non-dev) was sharing info. So I told eleo to stop bullying me which got me a quick kick out of not just the PixelXpert room but also the Iconify one.

Sorry for the long story. I never intended on starting any drama but I was trying to simply defend myself in that case. I hope one day this can be water under the bridge and I can rejoin the Iconify room so I can help contribute there.

Thanks for listening and please let me know if that SystemUIGoogle.apk is the file you need. I can easily send it to you privately on Telegram if so - again my Telegram name is TheLoonyRebel (Husky Pixel 8 Pro). I'm easily found on the various Pixel 8 Pro rooms.

**Comment by Mahmud0808** [comment]
Don't worry about it. You can keep using the rom you flashed. No need to go back. I'll find some alternative ways. You can attach the SystemUI apk in this thread too if you want.

**Comment by cozykitten** [comment]
Just adding, same issue since I updated to February OTA A14 today.
Also for some reason, when I disable QS theming it's stuck on black and white, system monet doesn't apply to it, even after completely disabling iconify.

Edit:
Figured out when I turn off the QS A14 fix in xposed settings it's not stuck on black and white any longer,... though idk why that didn't do it when I hit the "disable everything" button.

Edit 2:
The "Always white" button in xposed options seems to affect the icon, but not the text.
If turned off both text and icon will be black, if turned on, icon will be white. (on active quick tiles).
Also, quick settings theming still applies when the fix is disabled in xposed settings now, even tho it looks different.

**Comment by Mahmud0808** [comment]
> though idk why that didn't do it when I hit the "disable everything" button.

It's because disable everything resets everything back to default. And that fix is enabled by default for android 14 users.

> Edit 2: The "Always white" button in xposed options seems to affect the icon, but not the text. If turned off both text and icon will be black, if turned on, icon will be white. (on active quick tiles).

Try the latest debug build from github actions section. Let me know if that fixed your issue or not.

> Also, quick settings theming still applies when the fix is disabled in xposed settings now, even tho it looks different.

Restart SystemUI. and show screenshot.

**Comment by cozykitten** [comment]
## latest release
1. pixel variant default, xposed fix on, always white off
![image](https://github.com/Mahmud0808/Iconify/assets/116394977/614a602a-c206-484b-bea6-692ea5dfa114)

2. pixel variant default, xposed fix **off**, always white off
![image](https://github.com/Mahmud0808/Iconify/assets/116394977/5c5101b4-04e6-4a1f-b6d8-4171a8f62129)

## action build
3. same as 1st, also looks the same
4. same as 2nd, also looks the same
5. pixel variant lighty, xposed fix on, always white **on**
![image](https://github.com/Mahmud0808/Iconify/assets/116394977/268dd6fc-602e-467e-947e-b8205ae614a5)

6. qs theme disabled, xposed fix on, always white off
![image](https://github.com/Mahmud0808/Iconify/assets/116394977/82272592-c29a-4276-b841-25e9e4a3861e)


> And that fix is enabled by default for android 14 users.

When updating my phone I usually disable all magisk modules and click the disable everything button in iconify, do I need to remember disabling this setting too then?
or is it enough when lsposed is disabled so it doesn't load anyway?
Do I even need to hit the "disable everything" button before otas?

**Comment by Mahmud0808** [comment]
Looks like QS text color issue has been resolved.

You must enable xposed fix if you are using QS theming. And if you are not using QS theming, then keep the fix disabled too. It's not an issue.

When updating phone, disable modules from magisk module list. You don't have to disable everything from iconify app. The magisk module will keep everything disabled.

**Comment by Mahmud0808** [comment]
Fixed in 13cedfc34a20ade1f4b2a8673e0f06d8fcaf25f0
