### ISSUE TITLE
[BUG] Lagging while unlocking device with custom lockscreen clock

### ISSUE THREAD

**Issue by NikhilTechYT** [Mahmud0808/Iconify#416]
### Describe the bug

When using the lockscreen custom clock feature, the device stutters when unlocking, it gets stuck for a few frames. It's very noticeable in the video. I couldn't get the bug when it starts directly into the home screen where it lags for a millisecond.

### Steps to reproduce

1. Go to 'Iconify'
2. Click on 'Enable lockscreen clock'
3. 'Unlock and lock the device '

### Expected behavior

When unlocking, the device shouldn't lag, it should start into the home screen straight away. When opening the device to lockscreen, the opacity should go to 100 percent very quickly but when lockscreen is enabled it takes more time.

### Screenshots

https://github.com/Mahmud0808/Iconify/assets/91062159/9d551cef-306b-482f-a58c-ed4660405dec

### Device information

- Device: Redmi Note 9 pro max
- OS: TequilaOS Android 14 QPR1
- App version: v6.7.0
- Magisk/KernelSU: KernelSU version11458 

### Additional context

This issue is present in Android 14 and 13, kernelsu and magisk. I tried various methods to try and fix this but I couldn't. If this delay is fixed then this would be the best way to use depth wallpapers. The app is an awesome work, thank you Mohammed:)

**Comment by Mahmud0808** [comment]
You got my name wrong 😁 Anyway I'll look into it.

**Comment by NikhilTechYT** [comment]
> You got my name wrong 😁 Anyway I'll look into it.

Haha my bad. Thanks for noticing the issue. I will provide logs or any more support if you need.

**Comment by NikhilTechYT** [comment]
For the context, I am creating templates for depth wallpaper with foreground and background images.
![Screenshot_20240130-171931](https://github.com/Mahmud0808/Iconify/assets/91062159/4a5dfcf2-919b-43b0-a46e-8b8d802f407d)
![Screenshot_20240130-170854](https://github.com/Mahmud0808/Iconify/assets/91062159/bcb33efa-65d1-4d76-98ca-9b751d540db3)
![Screenshot_20240130-161827](https://github.com/Mahmud0808/Iconify/assets/91062159/4201e038-c1b8-41e2-ba79-45874b2020f1)

**Comment by NikhilTechYT** [comment]
If you want to add some samples to your app like this then I'm down to make some

**Comment by NikhilTechYT** [comment]
Got something?

**Comment by Mahmud0808** [comment]
> Got something?

No issue here. Can't reproduce unfortunately.

**Comment by dmitry-w3b** [comment]
У меня такая же проблема! На какое-то время помогает нажатие кнопка "Повторная оптимизация" в LSposed.

**Comment by andrive-one8** [comment]
I also happen to have the same bug on my phone. Had to disable it

**Comment by Mahmud0808** [comment]
Should be 70% better with latest update.
