### ISSUE TITLE
[BUG] The screenshot is not work with the new version

### ISSUE THREAD

**Issue by Fnnto** [Mahmud0808/Iconify#418]
### Describe the bug

when I use the version 6.6.0 and 6.7.0,the screenshot is not work,but the function is normal with the version 6.5.1.Afterward, I asked online and found out that it might be a conflict between the app and another app Thanox,how can these two apps coexist?

### Steps to reproduce

1. Change the settings normally
2. Screenshot
3." System ui is not responding"

### Expected behavior

Make these two apps coexist.

### Device information

- Device: [Mi 6]
- OS: [ stock ROM Android version 13.0 QPR3]
- App version: [v6.5.1]
- Magisk/KernelSU: [Kitsune Magisk 26.4]

**Comment by Fnnto** [comment]
In the new version, "iconify" must be in the background and cannot be killed. It must be directly added to the whitelist.

**Comment by Mahmud0808** [comment]
Share logs. And if you are not using android 14, then you are fine with old version of iconify. The latest versions are for making more compatibility with android 14.

Edit: Can not reproduce. Hence closing this issue.
