### ISSUE TITLE
[FEATURE] Add option to install overlays on demand

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#420]
### Describe the feature

An option to install overlays on demand (when they are in use) instead of installing them all and just enabling. I think it should be in the initial setup.

Alternative: two modes (setup and production), switching to production causes rebuild of iconify magisk module with only needed overlays, in setup mode all overlays are installed. It would be more practical, but I think it may be harder to implement.

### Why would it be useful to add?

Some older devices (especially those with 4gb ram) can't handle all those overlays without losing performance, I think decerasing amount of them should make the device usable with iconify (please correct me if it won't help).

### Example(s)

Nothing

### Additional context

Installing all overlays and only activating them when needed is a great thing when playing with all the iconify settings (reboots are not needed), but I think it also takes a lot of ram, causing the system to extremely slow down (again, if I don't think right, please correct me). It also makes a mess in apps list (very annoying for users of [App Manager](https://github.com/MuntashirAkon/AppManager)).

**Comment by Mahmud0808** [comment]
Here's a tutorial you may be looking for https://xdaforums.com/t/android-theming-use-project-themer-iconify-without-adding-100-apks-to-you-device.4548123/
