### ISSUE TITLE
[BUG] Monet crash

### ISSUE THREAD

**Issue by gaussandhisgun** [Mahmud0808/Iconify#421]
### Describe the bug

The app crashes if i open the Monet theming editor.

### Steps to reproduce

Go to second tab - color engine, open the system Monet color editor

### Expected behavior

The editor opens

### Device information

- Device: Redmi Note 9S
- OS: GhostOS based on Android 14
- App version: 6.7.0
- Magisk/KernelSU: Magisk 26.4 w/Zygisk, LSPosed 1.9.2

### Additional context

https://paste.crdroid.net/vlQhOg <- logs

**Comment by Mahmud0808** [comment]
Clear app data, and don't import old backups for now.

Edit: Should be fixed in 858225b27247f5291c27495bedb4666e50df1694
