### ISSUE TITLE
[FEATURE] Overlap header image in QQS

### ISSUE THREAD

**Issue by Bellidio** [Mahmud0808/Iconify#427]
### Describe the feature

Overlap header image could also work on the QQS panel

### Why would it be useful to add?

the resource already exists for QS, it would be great to exist in QQS as it is the most viewed and used panel, guaranteeing the same look in both

### Example(s)

![QQS](https://github.com/Mahmud0808/Iconify/assets/87273254/adb0df3c-05ae-41d1-952f-5c1eddaf80ae)

**Comment by Mahmud0808** [comment]
This is currently not possible because of the way android QS layout are laid out.
