### ISSUE TITLE
[FEATURE] Update InLine brightness bar style

### ISSUE THREAD

**Issue by Bellidio** [Mahmud0808/Iconify#428]
### Describe the feature

In this style of bar, could the auto-brightness button have the same outline with a black line like the bar to follow the same look? 🙏🏾
And the deactivated button has the same contour accent line

### Why would it be useful to add?

harmonize the style, so that it has the same complete look

### Example(s)

![302619437-44cbfa42-b659-41ec-aa39-dc1986c0484b](https://github.com/Mahmud0808/Iconify/assets/87273254/67c132e0-a592-4003-8d07-73affc8fb456)
![302619575-707057e0-bb46-472f-9412-53a6d6bb9bea](https://github.com/Mahmud0808/Iconify/assets/87273254/1de60e6a-1b50-4afa-921c-c5212cb97236)

**Comment by Mahmud0808** [comment]
It is intended to not have visibility issue in some custom roms where light accent color with light icon would make it hard to see. Fixing it for one rom will break it for others.
