### ISSUE TITLE
[BUG] Delay when pulling the QS panel when using tile text color accent

### ISSUE THREAD

**Issue by Bellidio** [Mahmud0808/Iconify#429]
### Describe the bug

Using QS tile text color white everything is normal
Using QS tile text color accent the QS panel is delayed, QQS panel is normal
Whenever the phone is restarted, the screen freezes for a few minutes, turning on and off, until it returns to normal and the phone stabilizes and can be used. Sometimes I have to wait more than 5 minutes until the screen starts working again and stops turning on and off (it stays off for 1 minute, turns on for a few seconds and turns off again)
Using text color white the entry into the system is normal

### Steps to reproduce

1. Go to Tweaks
2. Menu XPosed
3. title e subtitle text accent

### Expected behavior

tile color accent works without delays on the panel and without freezing the system at boot
work as color white which works fine

### Device information

- Device: Redmi Note 8 Pro (begonia)
- OS: CR Droid 10.1 Android 14
- App version: Debug 1738 / 1739 and 1755
- Magisk/KernelSU: Magisk 27.0]

**Comment by Mahmud0808** [comment]
Provide logs, and screen recording if possible.
