### ISSUE TITLE
[BUG] QS text color issue

### ISSUE THREAD

**Issue by xccc5** [Mahmud0808/Iconify#433]
### Describe the bug

When using QS Text Color options in Xposed menu it only changes the icon not the text in the tiles,

### Steps to reproduce

1. Go to 'Tweaks menu'
2. Click on 'Xposed menu'
3. Click on 'Quick Settings'
4. Click on 'any of the two options in QS Text colors'

### Expected behavior

in the description of the options it says it will change the color of title and subtitle but it changes only the icon

### Screenshots

![Screenshot_20240212-230128_Iconify](https://github.com/Mahmud0808/Iconify/assets/73885832/61a714e7-58d0-4bbc-b5f6-f5185acdfd43)
![Screenshot_20240212-230135_Iconify](https://github.com/Mahmud0808/Iconify/assets/73885832/523ddea1-363e-4dea-a66b-af92e4ff737b)
![Screenshot_20240212-230151_Iconify](https://github.com/Mahmud0808/Iconify/assets/73885832/0a8a09f6-cc49-40b8-85b6-a2cf98b47a81)

### Device information

- Device: [OnePlus 11]
- OS: [ Lineage OS  21-20240118-UNOFFICIAL-salami]
- App version: [v6.7.0]
- Magisk/KernelSU: [Magisk 27.0]

**Comment by Mahmud0808** [comment]
Check debug version https://github.com/Mahmud0808/Iconify/commit/13cedfc34a20ade1f4b2a8673e0f06d8fcaf25f0
