### ISSUE TITLE
[BUG] Accent color does not apply to the two digits of the time in the header clock

### ISSUE THREAD

**Issue by Bellidio** [Mahmud0808/Iconify#434]
### Describe the bug

For this style of header clock, the accent color does not work on the two digits of the hour. 24H Clock

### Steps to reproduce

1. Go to Menu Xposed
2. Click on Header clock
3. Scroll down to Second style

### Expected behavior

Two digits of the hour with accent color 

### Screenshots

![Screenshot_20240213-102155_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/87273254/eaad16b6-41e4-4ada-be7b-1ed015ef5fbe)

### Device information

- Device: Redmi Note 8 Pro
- OS: CR Droid 9 - A13
- App version: Debug 1755
- Magisk/KernelSU: Magisk 27.0

**Comment by Mahmud0808** [comment]
You didn't even show what color you selected, what color it was supposed to be, what's your default accent color.

**Comment by Bellidio** [comment]
It's in my print, my accent color is yellow, only number 1 is yellow in the print, see that the zero of number 10 is still white, and only number 1 is yellow

**Comment by Mahmud0808** [comment]
That is intended, not a bug.

**Comment by Bellidio** [comment]
See this other style of watch, the colors are correct, the number 11 is all yellow
In this other style it is normal, the first two digits are yellow

![Screenshot_20240213-112552_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/87273254/e2bd5bce-45ab-43c4-8807-2e0c96024678)

**Comment by Bellidio** [comment]
But in this style it doesn't work, only the first digit turns yellow

![Screenshot_20240213-112826_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/87273254/37511229-417a-4e2a-b41c-cb46ad52dfa2)

**Comment by Mahmud0808** [comment]
As I already said, both are intended behavior and not a bug.

**Comment by Bellidio** [comment]
My colors

![Screenshot_20240213-112950_Iconify (Debug)](https://github.com/Mahmud0808/Iconify/assets/87273254/5224911f-5002-4437-80aa-49380c8443b6)

**Comment by Mahmud0808** [comment]
It's a variation of [THIS](https://www.google.com/search?sca_esv=40ad471a4e6b196f&sca_upv=1&sxsrf=ACQVn0_huQ4G0rYcteKIx7-6BOet_KKlTQ:1707835195099&q=oos+clock&tbm=isch&source=lnms&prmd=ivnsmbz&sa=X&ved=2ahUKEwiUxY3xxaiEAxXRTGwGHbv-AVcQ0pQJegQIBxAB&biw=393&bih=719&dpr=2.75#imgrc=8a_2aAGXXZpayM)
