### ISSUE TITLE
[BUG] Custom Lock Screen Clock freezes after some times with Depth Wallpaper 

### ISSUE THREAD

**Issue by marcpinet** [Mahmud0808/Iconify#437]
### Describe the bug

After some times, the custom clock on the lockscreen freezes when depth wallpaper is enabled

### Steps to reproduce

1. Go to Iconify
2. Click on Depth Wallpaper and Custom Clock Lockscreen 
3. Enable both

### Expected behavior

The clock not freezing 

### Screenshots

![Screenshot_20240213-225312](https://github.com/Mahmud0808/Iconify/assets/52708150/14ee7c68-7458-4ff0-b653-0124b80defe6)

![Screenshot_20240213-225914](https://github.com/Mahmud0808/Iconify/assets/52708150/66083c0b-5b4f-4634-8717-57709e18e12c)

### Device information

- Device: Pixel 7
- OS: Android 14 Stock ROM (rooted) February 2024 Update
- App version: 6.7.0
- Magisk/KernelSU: Magisk 27.0

### Additional context

[magisk_log_2024-02-13T22.57.49.log](https://github.com/Mahmud0808/Iconify/files/14272660/magisk_log_2024-02-13T22.57.49.log)

**Comment by baianohak** [comment]
Yes, it happens a lot.

**Comment by marcpinet** [comment]
@Mahmud0808

**Comment by Mahmud0808** [comment]
Known issue in some roms. Try disabling double line clock from rom settings and see if that fixes it or not (as reported by some people)

**Comment by Richard38907** [comment]
For me, enabling this option crashes the UI after an unlock. (PixelExperience 13 on OnePlus Nord)

**Comment by Mahmud0808** [comment]
Does the time freezing issue still persist?

Edit: No response. Closing this issue.

**Comment by Ragnar-es** [comment]
It's still happening. 

That "double line clock" option is not present.

I almost miss my flight lol.
