### ISSUE TITLE
[BUG] Text colour on Power Menu

### ISSUE THREAD

**Issue by Laptop-Github** [Mahmud0808/Iconify#438]
### Describe the bug

The Text is not visible on Power Menu

### Steps to reproduce

1. Open Iconify.
2. Enable Pixel Black Theme form Themes in Xposed Menu.
3. Choose the Pixel Variant QS Panel Tiles, Brightness Bar & Notification.
4. Enable Always White in Icon and Label.
5. Enable Always White in Quick Settings in Xposed Menu.
6. Long press Power button to get into Power Menu.

### Expected behavior

The Text should be visible in Power Menu.

### Screenshots

![Screenshot_20240215-213536_Iconify](https://github.com/Mahmud0808/Iconify/assets/146508537/57d43bde-edae-42e0-b072-d3c7b7ad1ebe)

### Device information

- Device: Poco M6 Pro/Redmi 12 5G
- OS: CrDroid 9.12 Official
- App version: 6.7.0
- Magisk/KernelSU: Magisk 26.4

**Comment by Mahmud0808** [comment]
If your power menu follows light/dark theme, then use normal variant notification style. If your power menu is always black, then use pixel variant notification style.

**Comment by Laptop-Github** [comment]
Working great now Thank you
