### ISSUE TITLE
Lockscreen Clock in the Xposed menu

### ISSUE THREAD

**Issue by Anachrion** [Mahmud0808/Iconify#440]
### Describe the bug

On my OnePlus 9P runing on LineageOS 21 (Android 14)  the Lockscreen Clock in the Xposed menu - if activated - does not appear on the lockscreen.

### Steps to reproduce

1. Go to TWEAKS
2. Go to Menù XPosed
3. Go to Lockscreen Clock
4. Activate "Custom Lockscreen Clock" switch
5. Select a clock style
6. Nothing appears on the lockscreen

### Expected behavior

The selected lockscreen should appear.

### Device information

- Device: OnePlus 9 Pro
- OS: LineageOS 21
- App version: 6.7.0
- Magisk/KernelSU: Magisk 27.0

**Comment by Mahmud0808** [comment]
You have to tap on one of the clock previews to select it. By default it will not show any clock.

**Comment by Anachrion** [comment]
Woah, thanks @Mahmud0808, I hadn't understood it was the expected behaviour. Maybe it could be worth adding an "Apply" button.

**Comment by Yoannjap** [comment]
But another problem with the custom clock is that the default lockscreen clock regularly reappear after some time, and overlay the custom one (using lineageOS 22.1)
