### ISSUE TITLE
[FEATURE] More customization for lockscreen clock

### ISSUE THREAD

**Issue by AeliusRuivus** [Mahmud0808/Iconify#442]
### Describe the feature

Wouldit be possible to add additional features to the lockscreen clock? For instance:
* Custom vertical margins - I use 600px to mobe my clock as down as possible, but this is the max, and goes only to mid screen;
* Lateral margins - so we can have the clock off-center
* Custom colour and size for each individual component - I know it is a difficult one, but we can alter the colour of the first digit on some clocks, and two digits for the status bar clock - flexibility on this would be great!    

### Why would it be useful to add?

I'm aiming to replicate a particular clock style*, different from the stock one and from the options provided. Iconify is the ONLY app so far that had a good lockscreen clock, and I feel these customizations would make it even better.

* I'm aiming for the Windows Phone 8 lockscreen clock - yes I am weird :-)

### Example(s)

These are my configurations, making use of negative line spacing (to move the text below the numbers) and 600pts top margin (moves the clock halfway through the screen).
![WhatsApp Image 2024-02-26 at 19 35 18_cb01425e](https://github.com/Mahmud0808/Iconify/assets/46090686/102131c7-38fa-4feb-9c03-54003c7a48d4)
![WhatsApp Image 2024-02-26 at 19 35 18_325350bc](https://github.com/Mahmud0808/Iconify/assets/46090686/d970489e-55b1-4e74-acd2-3acbdb2c8f0f)

This is the custom clock I mentioned that already has two custom colour digits, I'm aiming for something like this:
![image](https://github.com/Mahmud0808/Iconify/assets/46090686/18f9f59b-af30-4c08-9ed1-e105d92836a6)

To be more precise, I'm aiming for either of these looks (one is from WP8, the other is from old Samsung custom clock options)

![image](https://github.com/Mahmud0808/Iconify/assets/46090686/68247b83-34d3-4853-9c5b-3e6d1eb26ebc)

![image](https://github.com/Mahmud0808/Iconify/assets/46090686/e76aab75-5422-4b93-bec7-d50456e1e245)

### Additional context

It goes without saying that I'm really grateful for this project, and unfortunately I'm not capable of contributing those changes myself - but since everyone installing this app is into customization, I suppose many of us will appreciate even more fine tuning options :-)

**Comment by Mahmud0808** [comment]
Added https://github.com/Mahmud0808/Iconify/commit/44f99a64953d9e3d93748e8561f06661c0c5aaf2

Well, not exactly what you wanted, but better than nothing I guess :")

**Comment by glaysonmaster** [comment]
Is it possible to have these clock styles on iconify? I'm a layman, I have it installed, I managed to make a simple deep background, but I would like these types of clocks, the two primary numbers are a font style and the secondary ones seem to be others. This vertical clock is also very cool, is there any way to do it and I still don't know?

![Image](https://github.com/user-attachments/assets/c7a17d17-4426-4032-a620-264c22c3caff)
