### ISSUE TITLE
[BUG] Notch is killed automatically when in landscape mode

### ISSUE THREAD

**Issue by endergreen12** [Mahmud0808/Iconify#443]
### Describe the bug

when using an app on the horizontal screen, the notch is automatically killed
of course, the notch killer is off

the timing at which the notch is killed varies depending on the app
for example, in the YouTube app, if you continue to watch in full screen for a few seconds, the notch will be killed

turn on and turn off the notch killer and it will return to normal

please refer to the video attached to Screenshots to see exactly what is happening

### Steps to reproduce

1. Use an app that turns the screen horizontally for a while
2. Notch is killed by itself

### Expected behavior

Notch kill does not occur when using apps on horizontal screen

### Screenshots

https://github.com/Mahmud0808/Iconify/assets/90076182/760eee30-db3d-4a71-bf1e-5591efb63311

### Device information

- Device: Google Pixel 7
- OS: stock ROM UQ1A.240205.002
- App version: 6.7.0 release
- Magisk/KernelSU: Magisk 27.0

### Additional context

No other modules are installed to customize the SystemUI

pixelxpert was previously installed but is now uninstalled

please refer to the video for other installed modules

**Comment by Mahmud0808** [comment]
Are you using tablet QS mode?

**Comment by endergreen12** [comment]
> Are you using tablet QS mode?

yes

**Comment by Mahmud0808** [comment]
That requires notch killer to avoid QS overlapping issue. So it's integrated with that in landscape mode only.

**Comment by endergreen12** [comment]
> That requires notch killer to avoid QS overlapping issue. So it's integrated with that in landscape mode only.

i understood
is it possible to make the notch return to normal when the app is closed?

**Comment by Mahmud0808** [comment]
Not possible afaik, as it requires a UI reload to enable/disable notch bar killer.

**Comment by endergreen12** [comment]
> Not possible afaik, as it requires a UI reload to enable/disable notch bar killer.

i see 
thank you for your reply
