### ISSUE TITLE
[BUG] APP IS GETTING OFF

### ISSUE THREAD

**Issue by Gorgan10** [Mahmud0808/Iconify#447]
### Describe the bug

I have a P8P A14. When I first installed the application, I gave access to the Magisk root, and the Lsposed module was activated. After opening the application and clicking on the "Let's go!" button and the application begins some loading and at the “Building Overlay for AMAC” stage, the application crashes. I rebooted the phone

### Steps to reproduce

1. Open the app
2. Grant root permission
3. Clicked the "Let's go" button
4. Application is getting off

### Expected behavior

Just work

### Screenshots

![ISSUE](https://github.com/Mahmud0808/Iconify/assets/80852516/7fa2b597-3003-4583-8b22-3a90b264cf7c)

### Device information

- Device: Google Pixel 8 Pro
- OS: stock ROM, Android 14
- App version: Latest
- Magisk/KernelSU: Magisk 77.0

**Comment by Mahmud0808** [comment]
Fixed in 7eaa11f93258592a6a801aff115494c7df0705bf
Use debug build from actions tab

**Comment by Gorgan10** [comment]
Solved! Thx👍
