### ISSUE TITLE
Navbar won't hide

### ISSUE THREAD

**Issue by TravisShepherd** [Mahmud0808/Iconify#450]
### Describe the bug

3 button and nav gestures won't hide 

### Expected behavior

Completely hidden stock navigation. (3 button/gestures)

### Device information

- Device: [e.g. Google Pixel 8pro]
- OS: [e.g. stock ROM Android version 14]
- App version: [e.g. v6.7.0]
- Magisk/KernelSU: [e.g. Magisk 27.0]

**Comment by Mahmud0808** [comment]
Please use debug version for now, 6.7.0 is compatible till January build of android 14.

**Comment by TravisShepherd** [comment]
Sorry, is that located on GitHub? If so, where? Thanks.

**Comment by Mahmud0808** [comment]
`Actions` tab
