### ISSUE TITLE
[FEATURE] add support volume panel setting in MYUI sir

### ISSUE THREAD

**Issue by Ktslovers99** [Mahmud0808/Iconify#452]
### Describe the feature

Volume style(custom magisk module) in volume panel setting

### Why would it be useful to add?

added support for MYUI rom users.

### Example(s)

![Screenshot_20240405-042847](https://github.com/Mahmud0808/Iconify/assets/97413365/01be1c8a-1f23-41c9-b8b1-b2eb72ccda67)

**Comment by tomaszk8266** [comment]
According to readme:

> Iconify exclusively supports stock Pixel or custom AOSP ROMs. It does not support other OEMs such as MIUI, OneUI, ColorOS, NothingOS, MotoUI, etc.

**Comment by tomaszk8266** [comment]
MyUI is one of these
