### ISSUE TITLE
[BUG] Some themes are not working.

### ISSUE THREAD

**Issue by offxyz9** [Mahmud0808/Iconify#453]
### Describe the bug

Icon pack is not working.

### Expected behavior

![Screenshot_20240404-185834_Iconify_(Debug)](https://github.com/Mahmud0808/Iconify/assets/120702273/4a3d575e-7a6b-4825-9310-828f38e09150)
![Screenshot_20240404-185819_Iconify_(Debug)](https://github.com/Mahmud0808/Iconify/assets/120702273/389561c7-c77a-49c7-9e63-3490a31bed6f)

### Device information

- Device: [Redimi Note 11]
- OS: [Paranoid Android Uvite Beta 1]
- App version: [6.7.0 (#1784)]
- Magisk/KernelSU: [KernelSU:11458]

**Comment by Mahmud0808** [comment]
This is not an iconify bug. Rather security implementation of KSU. Follow [this guide](https://t.me/IconifyDiscussion/1/173780).
