### ISSUE TITLE
[BUG] LSPosed not working.

### ISSUE THREAD

**Issue by TylerHaoNhot** [Mahmud0808/Iconify#456]
### Describe the bug

I can't get access to the XPosed menu after i upgrade my app version from v6.1.0 (i think) to v6.7.5

### Steps to reproduce

I tired reset my phone for hundred times, i tried to update everything, reinstall... Bla bla and it doesn't work no matter what. 

### Expected behavior

I just want to get access to there, the XPosed menu and change configs in there. 

### Screenshots

![Screenshot_20240405-121656](https://github.com/Mahmud0808/Iconify/assets/143271606/22ad0490-46d0-40f6-95fc-98965ca60bcd)
![Screenshot_20240405-122030](https://github.com/Mahmud0808/Iconify/assets/143271606/a81acf5f-4523-40a5-9c22-773ea07b7baa)

### Device information

- Device: [Google Pixel 3]
- OS: [stock ROM Android version 12]
- App version: [v6.7.5]
- Magisk/KernelSU: [Magisk v81658d45]

### Additional context

Edited: when i try to re-dowload LSPosed, now it said "Not found LSPosed" when i try to click on XPosed menu.

**Comment by huynhdanhlang** [comment]
You can copy the manager.apk from module LSposed to the /data/adb/lspd folder or restart systemUI. I hope it is useful.

**Comment by Mahmud0808** [comment]
Include lsposed logs

**Comment by linalawl** [comment]
> You can copy the manager.apk from module LSposed to the /data/adb/lspd folder or restart systemUI. I hope it is useful.

Same here. Can you give more detailed instructions please? Thanks

**Comment by TylerHaoNhot** [comment]
> You can copy the manager.apk from module LSposed to the /data/adb/lspd folder or restart systemUI. I hope it is useful.

Can you give more instructions to the file path? I can't find the /data/adb.

**Comment by TylerHaoNhot** [comment]
> Include lsposed log

[LSPosed_2024-04-05T17_04_03.967556.zip](https://github.com/Mahmud0808/Iconify/files/14883367/LSPosed_2024-04-05T17_04_03.967556.zip)
This is module log.

**Comment by TylerHaoNhot** [comment]
> You can copy the manager.apk from module LSposed to the /data/adb/lspd folder or restart systemUI. I hope it is useful.

![Screenshot_20240405-172647](https://github.com/Mahmud0808/Iconify/assets/143271606/13d691fa-5d32-435b-9da1-e9bdaf0ad38f)

Sorry, i tried but it's still keep showing that module not activate. After i copy the apk to there, and then reboot my phone and then even restart systemUI though.

**Comment by Mahmud0808** [comment]
Clear lsposed logs, try the latest debug version of iconify from the `Actions` tab, if error still there then share logs again.

**Comment by TylerHaoNhot** [comment]
> Clear lsposed logs, try the latest debug version of iconify from the `Actions` tab, if error still there then share logs again.

Logs here:
(Modules): 
[LSPosed_2024-04-05T18_09_46.416409-ModulesOnlyLog.zip](https://github.com/Mahmud0808/Iconify/files/14884043/LSPosed_2024-04-05T18_09_46.416409-ModulesOnlyLog.zip)
(All): 
[LSPosed_2024-04-05T18_09_31.276355-AllLog.zip](https://github.com/Mahmud0808/Iconify/files/14884045/LSPosed_2024-04-05T18_09_31.276355-AllLog.zip)
 (Logs are cleared before installing the new debug Iconify APK)

Implementation steps:
1: uninstall the old app. (Does not clear any UI configuration,sorry if that cause the results.)
2: install apk from github, use the lastest debug apk and install it. 
3: grand file and all files permission and let it download all resources. After that, i resart my phone. 
4: i check the results, it's does not work and keeping the same issues. 

Screenshots:
![Screenshot_20240405-180749](https://github.com/Mahmud0808/Iconify/assets/143271606/b6f16980-c801-4f12-9dfa-4131f7c278b0)
![Screenshot_20240405-180740](https://github.com/Mahmud0808/Iconify/assets/143271606/80f36954-a208-414b-a4b6-82bc3858fb91)
Under here is the apk i installed
![Screenshot_20240405-175429](https://github.com/Mahmud0808/Iconify/assets/143271606/6db39c44-3098-47b0-a8ab-fee97928e4f6)


This is my Magisk modules, idk if the bug cause by any of these. 
![Screenshot_20240405-185251](https://github.com/Mahmud0808/Iconify/assets/143271606/c6c48a37-a800-4739-a602-86b72517be22)

**Comment by Mahmud0808** [comment]
Fixed 69a6e58477585110510342ce5970d1700359d2dc
