### ISSUE TITLE
Custom clock lockscreen not the same as before (between 6.7.0 and 6.7.5)

### ISSUE THREAD

**Issue by marcpinet** [Mahmud0808/Iconify#457]
### Describe the bug

Before update :

![304559087-14ee7c68-7458-4ff0-b653-0124b80defe6](https://github.com/Mahmud0808/Iconify/assets/52708150/cd235868-490e-4b52-99bd-6de010dc2e76)

After update :

![Screenshot_20240405-074914](https://github.com/Mahmud0808/Iconify/assets/52708150/8d1c3b61-98e7-4dd5-9083-d15541709121)

### Steps to reproduce

Update from 6.7.0 to 6.7.5

### Expected behavior

The clock stays the same and we can no longer tweak it as perfectly as before

### Screenshots

see bug description 

### Device information

Device: Pixel 7
OS: Android 14 Stock ROM (rooted) February 2024 Update
App version: 6.7.5
Magisk/KernelSU: Magisk 27.0

**Comment by Richard38907** [comment]
What do you use to set the depth clock like iOS 16+?

**Comment by Mahmud0808** [comment]
Changing line height doesn't work?

**Comment by marcpinet** [comment]
> Changing line height doesn't work?

Nope, also I just saw that the date is way higher than before

**Comment by Mahmud0808** [comment]
Does it look fine when you don't change the font?

**Comment by marcpinet** [comment]
> Does it look fine when you don't change the font?

yeah, it's normal when no custom font is used

**Comment by Mahmud0808** [comment]
Send the font you are using.

**Comment by marcpinet** [comment]
[SF_Pro_-_Semibold_Rounded.zip](https://github.com/Mahmud0808/Iconify/files/14882517/SF_Pro_-_Semibold_Rounded.zip)


> Send the font you are using.

**Comment by marcpinet** [comment]
@Mahmud0808 when will the fix be deployed?

**Comment by Mahmud0808** [comment]
You can already download it from `Actions` tab of github repo.

**Comment by srt54558** [comment]
@marcpinet just curious... How did you cut out the background? With what app/tool?

Your Lockscreen looks amazing!!

**Comment by marcpinet** [comment]
> @marcpinet just curious... How did you cut out the background? With what app/tool?
> 
> Your Lockscreen looks amazing!!

haha thanks, I used the "Depth Wallpaper" which is inside Iconify > Tweaks > Xposed Menu > Depth Wallpaper

you basically just have to give a front image and back image and the clock will be set between them
(i just removed the background to extract only my cat's head and then paste it above the other layers, thanks to png's transparency support)

**Comment by marcpinet** [comment]
@Mahmud0808 and how do I install this dev/debug version over my current stable one without breaking anything?

**Comment by tomaszk8266** [comment]
To keep your current customization settings you can only export them. You can't install it as an "upgrade" because it uses diffrent signature and package name (it will be installed as another app)
