### ISSUE TITLE
[BUG] com.drdisagree.iconify.xposed.modules.HeaderClock failed to load

### ISSUE THREAD

**Issue by haha-dream** [Mahmud0808/Iconify#458]
### Describe the bug

`com.drdisagree.iconify.xposed.modules.HeaderClock` is failed to load because class `com.android.systemui.qs.QSSecurityFooterUtils` is not found

### Steps to reproduce

1. Activate Iconify xposed module
2. reboot

### Expected behavior

Iconify xposed module loaded successfully

### Device information

- Device: OnePlus 9R
- OS: RiceDroid 8.0 Android 13
- App version: 6.7.5
- Magisk/KernelSU: Magisk Alpha ecc74d45-alpha

### Additional context

[verbose_2024-04-05T12:51:54.198424.log](https://pastebin.com/cikvcpg5)

**Comment by Mahmud0808** [comment]
Will make this class optional then, or will look for alternatives

**Comment by haha-dream** [comment]
> Will make this class optional then, or will look for alternatives

I can see this setting is avaliable on my system, before 6.7.0 it was all fine, so i'm guessing there is some breaking change?
