### ISSUE TITLE
[BUG] Black background around the camera when Landscape & Better QS is activated.

### ISSUE THREAD

**Issue by SupianIDz** [Mahmud0808/Iconify#463]
### Describe the bug

Black background around the camera when Landscape & Better QS is activated.

### Steps to reproduce

1. Enable Better QS
2. Restart
3. Go to Landscape Mode
4. 
Make sure the application uses the full screen (don't cut the screen) or even when the full QS is displayed.

### Expected behavior

No black background in front Camera circle.

I couldn't take a photo because I only have one cellphone, so I edited it.

The gray circle represents the Camera circle, and the black background is the case.

### Screenshots

![Untitled design (2)](https://github.com/Mahmud0808/Iconify/assets/37969970/ee74a826-be88-45f3-bd7c-21b6928849ba)

I couldn't take a photo because I only have one cellphone, so I edited it.

The gray circle represents the Camera circle, and the black background is the case.

### Device information

- Device: Redmi Note 12 4G (topaz)
- OS: Spotted on crDroid A14, AlphaDroid A13 & A14
- App version: Spotted on v6.7.0 & v6.7.5
- Magisk/KernelSU: Kernel SU

**Comment by SupianIDz** [comment]
Sorry for pinging @Mahmud0808

**Comment by Mahmud0808** [comment]
Does this also happen when you only enable notch bar killer and not better QS?

**Comment by SupianIDz** [comment]
> Does this also happen when you only enable notch bar killer and not better QS?

this happens when the Notch Bar Killer is not activated.

When I activated it because you mentioned it, Better QS had no problems anymore.

Thank you for assisting.

**Comment by Mahmud0808** [comment]
Close the issue if your problem is fixed.
