### ISSUE TITLE
[FEATURE] Move to kotlin

### ISSUE THREAD

**Issue by Jvr2022** [Mahmud0808/Iconify#468]
### Describe the feature

The feature request is to migrate the app's codebase from its current language to Kotlin.

### Why would it be useful to add?

Moving to Kotlin offers numerous advantages such as enhanced code readability, reduced boilerplate code, improved null safety, interoperability with existing Java code, and support for modern language features. These benefits can streamline development efforts, facilitate easier debugging, and enhance overall code quality, leading to a better user experience.

### Example(s)

N/A

### Additional context

Kotlin has become increasingly popular among Android developers, with numerous apps migrating to Kotlin to take advantage of its benefits. Many well-known apps in the Play Store have already adopted Kotlin, demonstrating its effectiveness in enhancing development workflows and app performance. By joining this trend and migrating to Kotlin, our app can align itself with industry standards and leverage the growing ecosystem of Kotlin libraries and tools, ultimately improving its maintainability and competitiveness in the market. (written this with chatgpt i am not good in english)

**Comment by Jvr2022** [comment]
It should be a good idea to make a new branch and start migrating to kotlin

**Comment by Mahmud0808** [comment]
I have plan to move to kotlin but this project is so huge it just scares me lol.

**Comment by Jvr2022** [comment]
if you make a new branch I make kotlin migrate commits in that branch @Mahmud0808

**Comment by Jvr2022** [comment]
you can contact me on discord with hinkik_yt

**Comment by Mahmud0808** [comment]
Sure I'll make a new branch

**Comment by Jvr2022** [comment]
Ok @Mahmud0808 i am gonna start tomorrow and open pr`s in the nee branch

**Comment by Mahmud0808** [comment]
Done dd908e29eaa5b3514bbeff95b172ae7207421db6
