### ISSUE TITLE
[BUG] Quick Settings panel column set to 3.

### ISSUE THREAD

**Issue by TylerHaoNhot** [Mahmud0808/Iconify#469]
### Describe the bug

Uhh, i don't really know how to explain this, but when the "Panel Columns" is set to 3, and then when i swipe down to enter quick setting panel  (it's the notification place) , the second row is missing 2 quick setting icons. 

### Steps to reproduce

Nothing to reproduce here, just change the Row and Columns setting and randomly find this bug. 

### Expected behavior

Want to the quick setting zone on notifications center be more "well balanced" , top row is 3 so the second row must be 3 also. 

### Screenshots

This is normal, 2 icons I circled are the icons will disappear in the next image.
![Screenshot_20240406-015404](https://github.com/Mahmud0808/Iconify/assets/143271606/1ee05f26-1e25-4e76-9382-5bbde4e4f7be)

Missing 2 setting icons on the notification center.
![Screenshot_20240406-015348](https://github.com/Mahmud0808/Iconify/assets/143271606/6a9d6b77-0ec0-4138-bef0-f7674ef1bcdf)

My configuration. (Read the "Additional context" for more info)
![Screenshot_20240406-015613](https://github.com/Mahmud0808/Iconify/assets/143271606/4da9aac4-d0da-4cd1-bc59-f7dea51fc12a)

### Device information

- Device: [Google Pixel 3]
- OS: [stock ROM Android version 12]
- App version: [ v6.5.6 beta]
- Magisk/KernelSU: [Magisk v81658d45]

### Additional context

In my configuration about "Row and Columns", i tried to change all the other setting (the 2 top one) for some many more value and the bug is still there, so suppose, I think this is not my fault, a bug instead.
![Screenshot_20240406-015613](https://github.com/Mahmud0808/Iconify/assets/143271606/4d7f19e7-cd0a-4418-b3e6-e09816cb1e0c)

**Comment by Mahmud0808** [comment]
It is your rom which can't animate those extra tiles. Nothing to do with iconify :) Although maybe it can be fixed with xposed mod, but for now I am trying not to mix up xposed and overlays part as much as possible.

**Comment by TylerHaoNhot** [comment]
> It is your rom which can't animate those extra tiles. Nothing to do with iconify :) Although maybe it can be fixed with xposed mod, but for now I am trying not to mix up xposed and overlays part as much as possible.

Okay, i guess i have to get messed up with 4 Collums then:")
And also, the 5 columns also don't work well, idk it's my rom or your app fault, i'll just mention for you.

**Comment by Mahmud0808** [comment]
> > It is your rom which can't animate those extra tiles. Nothing to do with iconify :) Although maybe it can be fixed with xposed mod, but for now I am trying not to mix up xposed and overlays part as much as possible.
> 
> Okay, i guess i have to get messed up with 4 Collums then:") And also, the 5 columns also don't work well, idk it's my rom or your app fault, i'll just mention for you.

Rom fault, some roms just don't implement the animation part when there are tiles more than certain amount . In that case animation looks finicky.
