### ISSUE TITLE
[FEATURE] white QuickSettings theme

### ISSUE THREAD

**Issue by akmsk1999** [Mahmud0808/Iconify#47]
### Describe the feature

The title says as it is....plz add 
#QS white theme 

Pixel variants have Black QS theme... Many of us finds it annoying... Can you please add white QS theme option for that..

Please

### Why would it be useful to add?

.

### Example(s)

![208276068-7a0efd6b-439a-4984-9ce0-45af8b57ce0c](https://user-images.githubusercontent.com/16622098/215301018-6cc704d5-66c4-4527-9f6b-79467af3c835.png)

### Additional context

.

**Comment by Mahmud0808** [comment]
Try AOSPMods first. It already has that feature.
