### ISSUE TITLE
[FEATURE] Change/remove/Hide Shortcut (app icon) in launcher

### ISSUE THREAD

**Issue by VixenSugo** [Mahmud0808/Iconify#470]
### Describe the feature

can you add this feature?
icons (shortcuts) saved in this path: /data/data/... (root directory)
thanks for this project.

### Why would it be useful to add?

because i have problem with some apps in A14
after change icon (for example in X twitter Messenger modded by revanced that have a feature for change icon) in A14, duplicated icon created in launcher
i need uninstall/remove previously icon from launcher by root access or something like that

### Example(s)

![T](https://github.com/Mahmud0808/Iconify/assets/103747228/8721c7e9-18a0-4287-9750-423b10f8fe28)

**Comment by Mahmud0808** [comment]
Why would you need root access for uninstalling non-system apps?

**Comment by HiFIi** [comment]
> Why would you need root access for uninstalling non-system apps?

🤔🤔🤔🤔🤔

**Comment by VixenSugo** [comment]
> Why would you need root access for uninstalling non-system app

not uninstall app, remove or hide duplicate shortcut(icon) in launcher
it's bug in A14 for some apps those have a change icon feature
Although the feature of hiding the app icons alone does not solve this problem because this is a bug and to fix it, changes must be made in the root directory of the launcher folder
 note: Both icons open the same app and the previous shortcut, is not deleted after changing it
To solve this problem, i need an option to access the shortcuts(icons) in the launcher to delete or hide them.

**Comment by Mahmud0808** [comment]
This feature request should be in [PixelLauncherMods](https://github.com/KieronQuinn/PixelLauncherMods) or somewhere else. It's out of scope with iconify.
