### ISSUE TITLE
[FEATURE] adding feature to changing QS label text to black.

### ISSUE THREAD

**Issue by TylerHaoNhot** [Mahmud0808/Iconify#475]
### Describe the feature

Add a feature to the QS label texts to black, all black.

### Why would it be useful to add?

Im currently using transparent and blurry QS modification on XPosed, so that i can use some white QS panel titles on pixels rom without making it looks weird. But a small issues is... The background of the un-enabled button is white, but the text above it is also white! So it's hard to read them.i Just wish there is a option to force them(the text) go all black. 
![Screenshot_20240407-120855](https://github.com/Mahmud0808/Iconify/assets/143271606/c7b06403-6c5d-4d11-bf02-8a7d8dce04a4)

You can add that feature into this page, You can name it"Always Black". 
![Screenshot_20240407-120846](https://github.com/Mahmud0808/Iconify/assets/143271606/74089ac8-646d-46e8-8d1a-af84eeecd0bc)

### Example(s)

There, im using a photo editing software and used bucket tool so the text look kinda blocky btw.

![Không Có Tiêu Đề12_20240407121637](https://github.com/Mahmud0808/Iconify/assets/143271606/cb8ee9a7-78c8-4641-ab32-acfcc9bdaf76)

**Comment by TylerHaoNhot** [comment]
Anddd also the "system icon pack" on the QS titles black as well, idk if it's possible or not, but I'll be happy if you make that become a real thing to turn on.

**Comment by Mahmud0808** [comment]
What would it look like in dark mode?

**Comment by TylerHaoNhot** [comment]
> What would it look like in dark mode?

I think it's better to make it work on light mode only.Im asking adding this feature is a way to use light QS themes on pixel though.

**Comment by Mahmud0808** [comment]
> I think it's better to make it work on light mode only.Im asking adding this feature is a way to use light QS themes on pixel though.

But I need to know what color it would be in dark mode

**Comment by TylerHaoNhot** [comment]
> > I think it's better to make it work on light mode only.Im asking adding this feature is a way to use light QS themes on pixel though.
> 
> But I need to know what color it would be in dark mode

Maybe the opposite color of the background.
Example: the background is dark pink the text will be pinkish white. (Base on pink theme of materials you)

**Comment by TylerHaoNhot** [comment]
Just make sure you make it that it easier to read (colors contrast each other)

**Comment by Mahmud0808** [comment]
Can you tell me how did you make your text white on light mode? It should be black by default.

**Comment by TylerHaoNhot** [comment]
> Can you tell me how did you make your text white on light mode? It should be black by default.

Idk, maybe because i break the rule.  like i said, i use non pixel QS theme for pixel so it's not quite compatible.

**Comment by Mahmud0808** [comment]
If you want to use non pixel QS theme for pixel, you should enable `Light Theme` from Tweaks > Xposed Menu > Themes

**Comment by TylerHaoNhot** [comment]
> If you want to use non pixel QS theme for pixel, you should enable `Light Theme` from Tweaks > Xposed Menu > Themes

Okay, thanks for the fact.
