### ISSUE TITLE
[BUG] Customizations not working Stock android 14 April Update + KernelSu + Zygisk Next + LSposed Google Pixel 8 pro

### ISSUE THREAD

**Issue by Oga-net** [Mahmud0808/Iconify#478]
### Describe the bug

The customizations are not applying when choosed.
The only one working is the monet color.
Everything Related to LSposed is not working with or without Android 14 fix enabled.

It is working with magisk+LSposed but not Kernel SU & Zygisk Next + LSposed

### Steps to reproduce

1. Flash latest Android 14 
2. Flash Kernel SU & reboot
3. Install Zygisk NEXT & reboot
4. Install LSposed & reboot
5. Install Iconify & reboot
6. Re-optimise Iconify in LSposed & enable it
7. Try applying new status bar icons
8. not working
9. Reboot  & still not working

### Expected behavior

Customizations applying correctly

### Device information

- Google pixel 8 pro
- Android 14 april update
- Kernel SU latest
- Zygisk Next latest
- LSposed latest
- Iconify latest

**Comment by HiFIi** [comment]
I'm running the latest GitHub actions build of [lsposed for Android 15 even though I'm running latest 14 QPR beta](https://github.com/mywalkb/LSPosed_mod/releases), and use the latest GitHub actions of iconify. It works for me.

**Comment by Mahmud0808** [comment]
Follow installation guide written in README
