### ISSUE TITLE
AMOLED Dark Mode option broken on Android 14 UP1A

### ISSUE THREAD

**Issue by DavidCGranger** [Mahmud0808/Iconify#479]
### Describe the bug

When I updated to the latest version of Iconify on my Google Pixel 5 (redfin) running Stock November update based on UP1A, the two black themes stopped working. The same didn't happen on my Pixel 4a (sunfish) running QPR1 via a Custom ROM. 

### Steps to reproduce

1. Go to 'Optimizations -> Colours'
2. Click on one of the two black themes

### Expected behavior

The theme applying, either instantly or after a reboot

### Screenshots

![Screenshot_20240409-003959](https://github.com/Mahmud0808/Iconify/assets/96387429/c1135b63-0b89-4e15-b63f-82fa3dc0d943)

### Device information

- Device: Google Pixel 5
- OS: Stock ROM Android version 14.0 UP1A
- App version: 6.7.6
- Magisk/KernelSU: Magisk 27.0

### Additional context

[LSPosed_2024-04-09T00_43_17.152851.zip](https://github.com/Mahmud0808/Iconify/files/14911557/LSPosed_2024-04-09T00_43_17.152851.zip)

**Comment by Mahmud0808** [comment]
Use [ColorBlendr](https://github.com/Mahmud0808/ColorBlendr) for material color theming.

**Comment by DavidCGranger** [comment]
> Use [ColorBlendr](https://github.com/Mahmud0808/ColorBlendr) for material color theming.

This single option in Iconify is really all I want from theming. I really enjoy Iconify and always used this option to enable a proper dark mode.

**Comment by Mahmud0808** [comment]
Google updated material components, now each app using latest material components generates its own color based on wallpaper instead of using system color. That mean each app has to be themed individually. This is the sole reason ColorBlendr was created. Iconify can't theme each individual apps because of various limitations of how it works. So there won't be a solution. Most iconify will be able to do is theme System / Quick Settings.

**Comment by DavidCGranger** [comment]
> Google updated material components, now each app using latest material components generates its own color based on wallpaper instead of using system color. That mean each app has to be themed individually. This is the sole reason ColorBlendr was created. Iconify can't theme each individual apps because of various limitations of how it works. So there won't be a solution. Most iconify will be able to do is theme System / Quick Settings.

I know that. But that's not what I'm complaining about. Currently, the option is broken entirely on UP1A. It still works perfectly on QPR1.

**Comment by Mahmud0808** [comment]
Try the monet engine option of iconify. Set 800 and 900 of 4th and 5th row to black by tapping on the color palette. Then apply and see what happens.

**Comment by DavidCGranger** [comment]
> Try the monet engine option of iconify. Set 800 and 900 of 4th and 5th row to black by tapping on the color palette. Then apply and see what happens.

That worked, unlike the menu option. Thanks.

**Comment by Mahmud0808** [comment]
Probably those option got corrupted. You can clean install iconify again, or just keep using monet engine. I prefer monet engine because with that you have more control over colors. I am closing this issue now.
