### ISSUE TITLE
Module disabled message when lsposed module is on

### ISSUE THREAD

**Issue by TimTheDestroyer** [Mahmud0808/Iconify#481]
### Describe the bug

I turned on the iconify lsposed module. But when I go to the xposed menu, it says it says Module not activated, even though it is in lsposed.

### Steps to reproduce

1. Go to ''Iconify xposed menu"
2. See the module not enabled error
3. Check lsposed manager
4. See that it is enabled 
It just seemed to happen so I don't know what caused it
[LSPosed_2024-04-12T08_49_32.137608.zip](https://github.com/Mahmud0808/Iconify/files/14959534/LSPosed_2024-04-12T08_49_32.137608.zip)

### Expected behavior

If the module is enabled in lsposed, it should not give module not enabled error

### Screenshots

![Screenshot_20240412-084717](https://github.com/Mahmud0808/Iconify/assets/98670582/26735b2c-fd76-4677-9e36-45958adc32bf)
![Screenshot_20240412-084727](https://github.com/Mahmud0808/Iconify/assets/98670582/e2d63962-e915-4987-a9f4-2a273bc752d4)

### Device information

- Device: Pixel 7a
- OS: Stock. Android 14 QPR2 April patch
- App version:6.7.6
- Magisk/KernelSU: Magisk 27

**Comment by TimTheDestroyer** [comment]
I turned reinstalling the app. It worked for a few seconds. But then the error showed again. Other fixes that I tried did not work. Including reoptimizing and re enabling the module as well as clearing cache

**Comment by Mahmud0808** [comment]
Try with latest debug build from actions tab. Share lsposed log if still fails.

**Comment by TheUnifox** [comment]
Hey, also getting the same thing. I tried the most recent dev build but still nope. How would I get the logs? Just adb?

**Comment by TheUnifox** [comment]
And now it's working again, no idea what I did lol

**Comment by TheUnifox** [comment]
New issue now, System UI crashes when pulling down QS

**Comment by TheUnifox** [comment]
Fixable by turning on hide status icons under others in xposed menu lol. Issue with the icons in QS ig

**Comment by Mahmud0808** [comment]
lsposed logs are available inside lsposed app

**Comment by AlvaroOctavio** [comment]
Tengo el mismo error.
Pero lo logré solucionarlo, lo primero que hice fue deshabilitar el módulo de Iconify en Magisk, reiniciar el teléfono, entrar a Iconify para que este me diga que solo está funcionando en "Funcionando en modo Xposed", luego activo varias modificaciones en ese modo, para luego volver a Magisk y volver a habilitar el módulo de Iconify y reinicio el teléfono, de esa forma logré solucionar este error.
Espero que esto te ayude.

**Comment by iestynapmwg** [comment]
I'm running into the same problem.... I'm using LSPosed_mod and the latest Iconify release. I've enabled the module in LSPosed (selecting optimize first, as the instructions say), then rebooted to make sure LSPosed loads the module, but Iconify is still showing the error message in OP's screenshot. Here's my LSPosed log.
[LSPosed_2024-08-18T16_36_44.757072.zip](https://github.com/user-attachments/files/16651947/LSPosed_2024-08-18T16_36_44.757072.zip)

**Comment by Mahmud0808** [comment]
> I'm running into the same problem.... I'm using LSPosed_mod and the latest Iconify release. I've enabled the module in LSPosed (selecting optimize first, as the instructions say), then rebooted to make sure LSPosed loads the module, but Iconify is still showing the error message in OP's screenshot. Here's my LSPosed log. [LSPosed_2024-08-18T16_36_44.757072.zip](https://github.com/user-attachments/files/16651947/LSPosed_2024-08-18T16_36_44.757072.zip)

PixelXpert is crashing, iconify is detecting that crash and disabling itself to avoid any issue.

**Comment by hxka** [comment]
This also happens to me.

[LSPosed_2025-02-13T14_26_37.087914.zip](https://github.com/user-attachments/files/18783067/LSPosed_2025-02-13T14_26_37.087914.zip)

**Comment by Mahmud0808** [comment]
> This also happens to me.
> 
> [LSPosed_2025-02-13T14_26_37.087914.zip](https://github.com/user-attachments/files/18783067/LSPosed_2025-02-13T14_26_37.087914.zip)

Which lsposed version are you using? And what other modules?

**Comment by hxka** [comment]
https://github.com/mywalkb/LSPosed_mod 1.9.3

No other modules currently.

**Comment by Mahmud0808** [comment]
> https://github.com/mywalkb/LSPosed_mod 1.9.3
> 
> No other modules currently.

Use JingMatrix or ReZero's fork. With that try iconify debug build, can be found on actions tab of github repo. And also iconify has bootloop protection in xposed mods, so turning on any incompatible option will disable the module, make sure that is not the case here.

**Comment by hxka** [comment]
You mean incompatible option in Iconify? I have not enabled any XPosed options yet, because it said the module is not activated. And in the debug version I haven't enabled anything at all.

With those LSPosed forks and the latest debug build I still have the same issue.

JingMatrix v1.10.1 log:

[LSPosed_2025-02-13T15_18_05.921372.zip](https://github.com/user-attachments/files/18783835/LSPosed_2025-02-13T15_18_05.921372.zip)

ReZero 1.9.2 log:

[LSPosed_2025-02-13T15_25_37.750431.zip](https://github.com/user-attachments/files/18783847/LSPosed_2025-02-13T15_25_37.750431.zip)

**Comment by Mahmud0808** [comment]
> You mean incompatible option in Iconify? I have not enabled any XPosed options yet, because it said the module is not activated. And in the debug version I haven't enabled anything at all.
> 
> With those LSPosed forks and the latest debug build I still have the same issue.
> 
> JingMatrix v1.10.1 log:
> 
> [LSPosed_2025-02-13T15_18_05.921372.zip](https://github.com/user-attachments/files/18783835/LSPosed_2025-02-13T15_18_05.921372.zip)
> 
> ReZero 1.9.2 log:
> 
> [LSPosed_2025-02-13T15_25_37.750431.zip](https://github.com/user-attachments/files/18783847/LSPosed_2025-02-13T15_25_37.750431.zip)

There is no error in logs. I have doubt you haven't even properly enabled iconify, or you didn't read the info icon that's shown in the red module disabled error.

**Comment by hxka** [comment]
I did read it and followed the instructions. I clicked "Re-optimize" and then enabled the module and then restarted systemui. And then rebooted too just in case.

**Comment by Mahmud0808** [comment]
Let's continue in the telegram support group.

**Comment by hxka** [comment]
I figured it out. I had to disable unmounting modules for systemui and quickstep in KernelSU. Sorry for bothering you.
