### ISSUE TITLE
[FEATURE] Depth wallpaper gif/ProRes4444 support for foregound/background

### ISSUE THREAD

**Issue by Cr0vis** [Mahmud0808/Iconify#483]
### Describe the feature

transparent video plays over clock in foreground, background should also support videos

### Why would it be useful to add?

it's cool, allows lockscreen to match with live wallpaper used on home screen 

### Example(s)

![Screenshot_20240413-194415~2](https://github.com/Mahmud0808/Iconify/assets/99766020/b1433331-85ae-42a6-8577-7d174c735e4d)
Snow do the movey movey over clock

**Comment by Mahmud0808** [comment]
Where did you get transparent gif/mp4?

**Comment by Cr0vis** [comment]
Should be able to get a transparent gif from a quick search, apparently mp4s don't support an alpha channel ![giphy.gif](https://github.com/Mahmud0808/Iconify/assets/99766020/85808750-f876-4002-9646-0bec0220a860)

Currently trying to get just the snow layer from the artist that made the video I'm using as a wallpaper but probably won't get it, doesn't hurt to ask tho.
