### ISSUE TITLE
[FEATURE] QS Header Clock Line Height

### ISSUE THREAD

**Issue by drake-lol** [Mahmud0808/Iconify#486]
### Describe the feature

Add a line height option to the QS Header Clock to adjust the distance between the two lines if the option has it available

### Why would it be useful to add?

Certain fonts cause the lines to be very far apart and cause there to be a lot of wasted space.
![Screenshot_20240415-114515](https://github.com/Mahmud0808/Iconify/assets/70350894/8284cae1-3526-4aa1-aefc-76dd4fdd29c2)

### Example(s)

Simple slider similar to the one used with the lockscreen clock could be used

**Comment by Mahmud0808** [comment]
> Certain fonts cause the lines to be very far apart and cause there to be a lot of wasted space.

Can you try the latest debug build from actions tab and lemme know the result please

**Comment by drake-lol** [comment]
Yes, this appears to make the spacing a lot better. Thank you.
![Screenshot_20240416-104612](https://github.com/Mahmud0808/Iconify/assets/70350894/91496456-5272-46a2-aa62-a0b3f8b931df)
