### ISSUE TITLE
[FEATURE] Custom font picker

### ISSUE THREAD

**Issue by alejandro-alzate** [Mahmud0808/Iconify#487]
### Describe the feature

Font picker that lets you plug a otf ttf or whatever android can read

### Why would it be useful to add?

personality, and in my case readibility with a monospaced font

### Example(s)

uh didn't expected this one in the form maybe if i get time i'll put my ideas on canvas, then here.

### Additional context

I really would like to have filtering for what apps may use but that bit indont think is possible.
like firefox doesn't likes it one bit when you mess with the font so excluding it from the tweak would be nice, and i miss samsung's font picker, quite limited capabilities but at least it lets you pick between a handful

**Comment by Mahmud0808** [comment]
There are already lots of project available for this purpose. For example [MFFM](https://t.me/MFFMMain), [Scrape But Butter!](https://t.me/scrape0), [Oh My Font](https://gitlab.com/nongthaihoang/oh_my_font)

**Comment by alejandro-alzate** [comment]
what a bummer i really hoped to have everything in one place...
