### ISSUE TITLE
[BUG] Bootloop when using Pixel Xpert with Iconify Custom Clock

### ISSUE THREAD

**Issue by ghost** [Mahmud0808/Iconify#489]
### Describe the bug

When using Pixel Xpert and Iconify Custom Clock it causes the phone to be unusable (always stuck on lockscreen with no clock with no input to anything except notifications and haptics). I had to make an throwaway account to report this issue because my phone was unusable to get my 2FA codes. Even Safemode does not fix this. Please fix this issue or give a solution

### Steps to reproduce

1. Turn on Custom Clock with Pixel Xpert enabled
*System UI reboots*
3. See error

### Expected behavior

Custom clock to be on lockscreen without freezing forever

### Device information

- Device: Google Pixel 7
- OS: stock ROM Android14 April Update
- App version: 6.7.6
- Pixel Xpert: 3.3.2
- Magisk/KernelSU: Magisk Delta v26.4-kitsune-2

**Comment by ghost** [comment]
I managed to fix the freezing by flashing Stock ROM and deleting Iconify then flashing Magisk ROM. Please look into this issue to see why it is happening as I still want to use Custom Clock.

**Comment by Mahmud0808** [comment]
You shouldn't be using any fancy a14 clocks before enabling iconify clock. Enable the old boring stock clock before enabling any custom clocks and you'll be fine.
