### ISSUE TITLE
Customizing notification transpancy 

### ISSUE THREAD

**Issue by MAymanKH** [Mahmud0808/Iconify#490]
### Describe the feature

Currently we can choose between several notification styles and one of them is "semi transparent". But I want to be able to choose another style and control it's transpancy, and if possible, its blurity. Like how we can control the transpancy and blurity of QS panel background. 

### Why would it be useful to add?

It adds more variety to the customization. 

### Example(s)

For example, my notifications looks like this:
![Screenshot_20240423-170316_Brave](https://github.com/Mahmud0808/Iconify/assets/86633847/608effbc-c5ce-407e-a79f-c78c597abd61)

But I want to be able to make it looks like this:
![images](https://github.com/Mahmud0808/Iconify/assets/86633847/2b1f30b1-1385-4a37-bf08-20fae0eb0f49)

**Comment by Mahmud0808** [comment]
It won't work like that. If you notice the iconify notification style, it's made of several layers placed one top of another. Making the top layer semi-transparent will reveal all the layers behind it. Also I tried to add blur effect behind notification and it had side effects. So this is not possible for now.

Btw you can use the Fluid QS Theme from xposed menu, that will make any notification styles transparent.
