### ISSUE TITLE
header picture/clock erro

### ISSUE THREAD

**Issue by ZZZ7664** [Mahmud0808/Iconify#493]
### Describe the bug

In umi Crdroid system 6.7.6, setting the header image will prompt you to rename the file to something simpler. Setting the header clock will cause systemui to become unresponsive and it is bound to happen.

### Steps to reproduce

Adjust → Masthead Image → Select. hint . Rename the file to something simpler Adjust → Header Clock → Select → Customize Header Clock. systemui unresponsive

### Expected behavior

systemui无响应

### Screenshots

![Screenshot_20240427-194458_Iconify](https://github.com/Mahmud0808/Iconify/assets/103173090/a5d73caf-7ab0-49d9-b5d0-5c9a850f38da)

### Device information

- Device: xiaomi 10
- OS: Crdroid 10.2
- App version: v6.7.6
- Magisk/KernelSU: Magisk Alpha 26101

**Comment by Mahmud0808** [comment]
You have to provide lsposed logs
