### ISSUE TITLE
[BUG] Custom Switch Not Fully Applied

### ISSUE THREAD

**Issue by drake-lol** [Mahmud0808/Iconify#495]
### Describe the bug

When a custom switch is enabled, it is not shown on settings or in any other place. The only place that I can find that the toggles are applied are on the quick settings toggle menus.

### Steps to reproduce

1. Enable any custom switch
2. Open settings
3. No switch icons are changed.

### Expected behavior

All system switches to be changed to the custom one

### Device information

- Device: Google Pixel Fold
- OS: stock ROM Android version 14 (Build AP1A.240405.002.A1)
- App version: v6.7.6
- Magisk/KernelSU: Magisk v27.0

**Comment by drake-lol** [comment]
Forgot to add screenshots, sorry.
![Screenshot_20240429-131907](https://github.com/Mahmud0808/Iconify/assets/70350894/f872bcd6-d786-4282-a774-c19dfdd3fc03) ![Screenshot_20240429-131952](https://github.com/Mahmud0808/Iconify/assets/70350894/04eae6c6-5977-4157-999a-01aee3f72940)

**Comment by Mahmud0808** [comment]
Google started using material 3 switches which are not changeable. Only material 2 switches are changeable with overlays. I decided to hide the switch styles for android 14 users but some custom roms still use the old style switches, so I kept the option unhidden due to user requests.
