### ISSUE TITLE
[BUG] custom lockscreen clock with RTL languages

### ISSUE THREAD

**Issue by alr86** [Mahmud0808/Iconify#498]
### Describe the bug

When the language of the device is a right-to-left language and I want to use a clock of the iconify lock screen option, change some items to two digits and move the hour and minute (for example, it writes 30:12 instead of 12:30) and in some of them numbers are on top of each other

### Screenshots

![Screenshot_۲۰۲۴۰۴۲۸-۰۱۱۹۵۹_Iconify](https://github.com/Mahmud0808/Iconify/assets/65030817/ff4583b8-7ba4-4d4e-9a32-6efd10aaf34b)
![Screenshot_۲۰۲۴۰۴۲۸-۰۱۱۹۱۷_Iconify](https://github.com/Mahmud0808/Iconify/assets/65030817/649c7a10-f1e8-4c8d-abda-81dc130a3c45)

### Device information

- Device: Redmi note 9s
- OS: Android 14 - CrDroid v10.0
- App version: v6.7.6
- Magisk/KernelSU: Magisk 27.0
+++
- System language: Persian(Farsi)

**Comment by Mahmud0808** [comment]
Can you list all the clocks that has issues?

**Comment by alr86** [comment]
In styles 12 and 13, the hour and minute numbers are moved, and in styles 2 and 20, the seconds are shown on the minutes.

**Comment by alr86** [comment]
![Screenshot_۲۰۲۴۰۵۱۹-۱۸۳۵۴۳_Iconify](https://github.com/Mahmud0808/Iconify/assets/65030817/d19b1c38-b098-4470-9a26-c5965d3972c5)

And here(Style 11), second numbers is show before the hour numbers

**Comment by Mahmud0808** [comment]
so 2, 11, 12, 13, 20?

**Comment by alr86** [comment]
Yes, but it is for lock screen clocks,
In header clocks is 1, 2, 3, 5 and 7

In style 5, the seconds are displaying before the hour, and in styles 1, 2, and 3, the seconds are displaying on the minutes or hours, and in the style 7, the minutes and hours are interchangeable and on the date.
