### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Mrbelle93** [Mahmud0808/Iconify#50]
### Describe the feature

Possibility to change the position of the brightness bar in order to put it in first page of notification panel, at the top or under the quick settings tiles like on particular rom (for example pixel extended or evolution X).

### Why would it be useful to add?

It's usefull because I'm this way you can see the brightness bar with just one swipe.

### Example(s)

![Screenshot_20230130-075638_Telegram](https://user-images.githubusercontent.com/123928034/215408493-699c5a9d-eca2-4ffb-afa4-073fb58a7203.png)
![Screenshot_20230130-075626_Telegram](https://user-images.githubusercontent.com/123928034/215408515-5b7f341f-005a-47f1-bcc3-916bfaf2f61a.png)
![Screenshot_20230130-075620_Telegram](https://user-images.githubusercontent.com/123928034/215408538-8102f202-0f08-4247-ae80-a82c7d03e482.png)
![Screenshot_20230130-075606_Telegram](https://user-images.githubusercontent.com/123928034/215408570-eed55a18-0aa0-4040-b219-7f401916f53b.png)

### Additional context

Thank you for your work!!

**Comment by Mahmud0808** [comment]
This is not an easy thing to achieve through XPosed. A lot of things need to be modified to do that.

**Comment by Mrbelle93** [comment]
Dear Dev,
If you can try to check the possibility to insert this feature this should be really appreciated.
If you can't do nothing no problem ;)
