### ISSUE TITLE
[BUG] Header image 

### ISSUE THREAD

**Issue by 3zipro** [Mahmud0808/Iconify#501]
### Describe the bug

Header image option doesn't work 

### Expected behavior

I try multiple sizes headres and nothing happened I don't know if the issues on my device or not 

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 13.0 QPR3]
- App version: [e.g. v6.5.1]
- Magisk/KernelSU: [e.g. Magisk Delta 25.2]

**Comment by Mahmud0808** [comment]
1. That's not a correct title.
2. You didn't provide any logs?!
3. Why are you using such old version of iconify and reporting issues?
4. Even your magisk is out of date.

Please provide some efforts while reporting bugs.

**Comment by 3zipro** [comment]
For logs  later i will search how i can get them
and for my device information is wrong I don't know why maybe for one of
module's that i installed last night  i use galaxy s6 edge
Lineage os 20.  Magisk version 27 and latest iconify

**Comment by Mahmud0808** [comment]
Export logs from lsposed app and attach with your issue.

**Comment by 3zipro** [comment]
Sorry this is the file

https://www.mediafire.com/file/p0ndjgtu5blye6k/LSPosed_2024-05-21T19_28_43.360579.zip/file

**Comment by 3zipro** [comment]
now i supposed to remove the issues on GitHub because i made a big mistake
yes ?

**Comment by PinkSerenity** [comment]
> For logs later i will search how i can get them and for my device information is wrong I don't know why maybe for one of module's that i installed last night i use galaxy s6 edge Lineage os 20. Magisk version 27 and latest iconify

Your device information is wrong because it isn't yours. These are the default placeholder values when opening a new issue. You just didn't fill them. Your steps to reproduce are the placeholder steps as well.

**Comment by PinkSerenity** [comment]
> now i supposed to remove the issues on GitHub because i made a big mistake yes ?

I don't think you can remove it. You could close it if you want.

**Comment by 3zipro** [comment]
yes i will remove the report

**Comment by 3zipro** [comment]
Done it's closed now
