### ISSUE TITLE
[FEATURE] Filled Circle Battery Icon

### ISSUE THREAD

**Issue by harphere** [Mahmud0808/Iconify#505]
### Describe the feature

Filled Circle Battery Icon

### Why would it be useful to add?

Another type of colored battery icon to choose from. 

### Example(s)

Similar to the colored Circle and Dashed Circle battery icons, please add the Filled style also.

**Comment by Mahmud0808** [comment]
Where did you see the filled style? You provided no screenshot or link.

**Comment by harphere** [comment]
Sorry about that. It's provided in [PixelXpert](https://github.com/siavash79/PixelXpert/blob/canary/app/src/main/java/sh/siava/pixelxpert/modpacks/utils/batteryStyles/CircleFilledBatteryDrawable.java)
![Filled battery](https://github.com/Mahmud0808/Iconify/assets/28116390/dfe962fd-1f90-4541-9282-38a6e1d82f8b)

**Comment by Mahmud0808** [comment]
Why not use PixelXpert then?

**Comment by harphere** [comment]
For the same reason mentioned [here](https://github.com/Mahmud0808/Iconify/issues/82#issuecomment-1913329916).
You graciously added 2 circle icons anyways.
