### ISSUE TITLE
[BUG] Settings icons

### ISSUE THREAD

**Issue by harphere** [Mahmud0808/Iconify#506]
### Describe the bug

The Bubble v1 and Bubble v2 settings icons don't apply correctly anymore. Somewhere in the A14 updates, the settings icons got moved from the left side to the right side and since, your Bubble icons don't apply properly. 

### Steps to reproduce

1. Go to 'Iconify icon settings and select either Bubble v1 or v2'
2. Go to ROM Settings
3. The Bubbles don't apply with the different colors, instead, they have a static Accent color. 

### Expected behavior

The bubbles should appear in different colors beside the menu option

### Screenshots

![Screenshot_20240525-205604_Settings](https://github.com/Mahmud0808/Iconify/assets/28116390/696a9c36-a9cf-4b12-8d36-9a01a069c958)

### Device information

- Device: Google P8P
- OS: Matrixx ROM 10.5.0 A14
- App version: 6.7.6
- Magisk/KernelSU: Magisk 27.0

### Additional context

The settings icons used to be on the left side of the menu options but at some point in A14, they got moved to the right side like you see in the screenshot.  Might be a coincidence, but the bubbles applied just fine when the icons were on the left side.

**Comment by Mahmud0808** [comment]
> Somewhere in the A14 updates, the settings icons got moved from the left side to the right side and since, your Bubble icons don't apply properly.

It never changed in stock AOSP rom, it's your custom rom developers who changed it and applied accent color on each icons. So can't help. Reference: [HERE](https://github.com/ProjectMatrixx/android_packages_apps_Settings/commit/88fa198b1eab32661ec89b896cd4b03ce27ebbfa#diff-17a1bcd9dbffc571ce223daef7c5a933837fb2cd890a1ec812c53a6175cbbeb3R73)
