### ISSUE TITLE
Color themer on notification and qs tiles not staying after reboot

### ISSUE THREAD

**Issue by xdrc45** [Mahmud0808/Iconify#508]
### Describe the bug

Maybe I'm missing something in the settings menu that I missed. Setting the color theme for notifications and qs tiles does not stick after reboot. Lets say I change the theme colors to 
a red and blue. After any reboot it changes both colors to just red. See attached images.

### Expected behavior

Colors on notification and qs tiles should stick after reboot 

### Screenshots

![Screenshot_20240528-233028](https://github.com/Mahmud0808/Iconify/assets/171110609/8b43fd1c-2489-48c2-87e6-97125c3c4e73)
![Screenshot_20240528-231207](https://github.com/Mahmud0808/Iconify/assets/171110609/0d302698-8ee4-4da8-83cb-7c84ffb29d9e)

### Device information

- Device: [Google Pixel 8 Pro]
- OS: [Stock ROM Android version 14.0 latest 05/24]
- App version: [v6.7.6]
- Magisk[ Magisk 27.0]

**Comment by Mahmud0808** [comment]
Did you enable "Disable system monet" from tweaks > color engine?

Edit: no response from author, hence closing
