### ISSUE TITLE
Localized date format for custom lock screens 

### ISSUE THREAD

**Issue by ygorigor** [Mahmud0808/Iconify#51]
### Describe the feature

Make custom lockscreen use date format from locale. 
e.x. in romanian language it should be EEEE d MMMM. 

### Why would it be useful to add?

Date will look like on stock locscreen

### Example(s)

EEE, dd MM
EEE, d MMM
EEEE d MMMM

**Comment by Mahmud0808** [comment]
Out of curiosity, is that much of an issue though?

**Comment by ygorigor** [comment]
> Out of curiosity, is that much of an issue though?

No, but why not? 
Of course, if this is possible to implement.

**Comment by Mahmud0808** [comment]
> Of course, if this is possible to implement.

It is possible but it won't be locale. The format will be same for everyone.

**Comment by ygorigor** [comment]
> > Of course, if this is possible to implement.
> 
> It is possible but it won't be locale. The format will be same for everyone.

OK, then forget about it. 
It's not a big deal.
