### ISSUE TITLE
Brightness of Always-On Display with Depth Wallpaper

### ISSUE THREAD

**Issue by leeseth-07** [Mahmud0808/Iconify#513]
### Describe the feature

The brightness of the PNG wallpaper should be darkened more, like reducing the brightness of the sourced png when in Always-On display mode

### Why would it be useful to add?

this would help reduce battery drain due to the display not having to be so bright. when on always on display it's too bright right now

### Example(s)

![existing](https://github.com/Mahmud0808/Iconify/assets/171490112/aec31d16-5b63-44af-a101-434d0d0483fc)
![potentialnew](https://github.com/Mahmud0808/Iconify/assets/171490112/294cec47-87b0-4032-b308-0ac963f0132b)

**Comment by Mahmud0808** [comment]
Do you think a dimmed clock would be a good idea? 🤔

**Comment by leeseth-07** [comment]
probably not. the clock should be more visible than the wallpaper element,
keeping the clock easily visible while saving battery by not having to
light up the wallpaper as much.

thanks!

**Comment by Mahmud0808** [comment]
Checkout latest debug builds, hopefully this is added with new implementation of depth wallpaper for android 14.
