### ISSUE TITLE
[BUG] Volume warning causes SystemUI to crash

### ISSUE THREAD

**Issue by KrexonTX** [Mahmud0808/Iconify#514]
### Describe the bug

When Xposed module for Iconify is enabled even without touching the settings, when volume warning appear and accepted SystemUI crashes and restarts with warning still there if accepted it crashes again, but if cancelled then system works just fine. I can't volume up if I get the warning every time. But if module is not enabled in Xposed then there is no problem...

### Steps to reproduce

1. Enable Iconic in Xposed without even touching volume warning
2. Connect to Bluetooth device for the warning to appear
3. Press the volume up key until you get the warning
4. Accept the warning and then it will freeze crash and restart
Disabling the volume warning does nothing the warning is still there and still crashes

### Expected behavior

Normal android warning accept and continue to volume up

### Device information

- Device: [Nothing Phone 1]
- OS: [Stock NothingOS 2.5.5 Android 14]
- App version: [v6.8.0]
- Magisk/KernelSU: [Magisk 27.0]

**Comment by Mahmud0808** [comment]
Nothing OS is closed source and there is no support provided by iconify.

**Comment by TwinTalesXXII** [comment]
Had this problem on my Redmi Note 10 Pro, PixelOS 14.
Solved it by using the volume bar pop-up at the side of the screen to raise the volume to trigger the warning. I was able to press OK without the SystemUI restarting.

**Comment by Digitalbullits** [comment]
Happens on Motorola edge 2024 also
