### ISSUE TITLE
[BUG] Incorrect text size while using Vertical QS Tile

### ISSUE THREAD

**Issue by Malderin** [Mahmud0808/Iconify#515]
### Describe the bug

In the menu at: tweaks/xposed menu/quick settings, when option "Vertical QS Tile " is activated, the font is greatly enlarged.
Quick settings are made in 3 columns in 2 columns no problem).
In 6.7.6 version no problem.

### Steps to reproduce

1. Select quick settings in 3 columns
2. Activate the option Vertical QS Tile.

### Expected behavior

The normal font size in the qs tiles.

### Screenshots

![Screenshot_20240603-073421_Iconify](https://github.com/Mahmud0808/Iconify/assets/52313714/05c45be9-4a94-4b7e-b906-dec90bef5792)
![Screenshot_20240603-073115_Nova Launcher](https://github.com/Mahmud0808/Iconify/assets/52313714/d33ec6f8-88a3-4807-8b1b-714a587e7e2e)

### Device information

- Device: Poco X3 pro
- OS: android 14, qpr2
- App version: 6.8.0
- KernelSU 11873

**Comment by Mahmud0808** [comment]
Download the latest version again, the apk has been replaced with newer one.

**Comment by Malderin** [comment]
> Download the latest version again, the apk has been replaced with newer one.

I did, it didn't help. The problem remains.

**Comment by Mahmud0808** [comment]
Did you also try the latest debug version?

**Comment by Malderin** [comment]
> Did you also try the latest debug version?

I tried, but maybe I downloaded something wrong. can I have a direct link to the latest test version?

**Comment by Mahmud0808** [comment]
You can get it in [`Actions`](https://github.com/Mahmud0808/Iconify/actions) tab

**Comment by Malderin** [comment]
> Вы можете получить его на [`Actions`](https://github.com/Mahmud0808/Iconify/actions) вкладке

yes, I tried with this version, the problems persist.

**Comment by Mahmud0808** [comment]
[Iconify v6.8.0-release.zip](https://github.com/user-attachments/files/15531742/Iconify.v6.8.0-release.zip)

Try this, extract and install the apk. Let me know if it works or not.

**Comment by Malderin** [comment]
Yes, everything works as it should in this version. Thank you.
--
Отправлено из Mail.ru для Android понедельник, 03 июня 2024г., 12:27 +03:00 от DrDisagree  ***@***.*** :

**Comment by Malderin** [comment]
Yes, everything works as it should in this version. Thank you.


понедельник, 03 июня 2024г., 12:27 +03:00 от DrDisagree  ***@***.*** :

**Comment by ASC8384** [comment]
> You can get it in [`Actions`](https://github.com/Mahmud0808/Iconify/actions) tab

Could we get a Release version?

Thank you.

**Comment by Mahmud0808** [comment]
> > You can get it in [`Actions`](https://github.com/Mahmud0808/Iconify/actions) tab
> 
> Could we get a Release version?
> 
> Thank you.

It will be available when the next version releases

**Comment by HiFIi** [comment]
Beast
