### ISSUE TITLE
Random UI crash.

### ISSUE THREAD

**Issue by jk1526** [Mahmud0808/Iconify#516]
### Describe the bug

Keep experiencing random UI crashes either on main screen or when in any app.

### Steps to reproduce

UI can crash at random, no particular steps needed to reproduce.Crash occured 09:51hrs.
[log_2024_06_08_09_52_14.log](https://github.com/user-attachments/files/15747363/log_2024_06_08_09_52_14.log)

### Expected behavior

No crashes!

### Screenshots

Non available 

### Device information

Nothing phone 2
Stock ROM
Nothing 2 launcher 2.5.13
OS Ver.2.5.5
Android 14.
Running Arter Kernel v18 ( crashes also occuring on stock.)
Magisk 27

### Additional context

[log_2024_06_08_09_52_14.log](https://github.com/user-attachments/files/15747367/log_2024_06_08_09_52_14.log)

**Comment by HiFIi** [comment]
You sure it's this?

**Comment by jk1526** [comment]
Well it's only happened since installing Iconify. When I disabled it in Lsposed the crashes stop.

**Comment by HiFIi** [comment]
Hmmm

**Comment by Mahmud0808** [comment]
Unsupported ROM

**Comment by jk1526** [comment]
Hi,
   My bad thought Nothing OS was based on aosp?

Regards.

J Knaggs.

**Comment by Mahmud0808** [comment]
It is, but it's closed source. Kindly read https://github.com/Mahmud0808/Iconify?tab=readme-ov-file#-faq

**Comment by jk1526** [comment]
OK, thanks for the info.

Regards.

J Knaggs.
