### ISSUE TITLE
[BUG] Notification Style Partially Broken

### ISSUE THREAD

**Issue by JakeDHS07** [Mahmud0808/Iconify#522]
### Describe the bug

I have the CyberPonk v1 chosen and it was working fine until the new update. Even with the most recent dev it only has the style on half the notification now. The first half becomes glitched and see through. 

### Steps to reproduce

1. Go to notification style
2. Click on CyberPonk v1 and apply
3. Get a notification 

### Expected behavior

To see the full notification themed as before. Assuming something broke between the new June update for the phone or the new iconify update 

### Device information

- Device: [e.g. Google Pixel 7 Pro]
- OS: [e.g. stock ROM Android version 14.0 June 2024]
- App version: [e.g. v6.8.0 Dev 1911
- Magisk/KernelSU: [e.g. Magisk 27 stable]

**Comment by Mahmud0808** [comment]
Attach screenshots

**Comment by JakeDHS07** [comment]
Ok here's one I just got 
![Screenshot_20240613-062316](https://github.com/Mahmud0808/Iconify/assets/6186123/d155a1f0-80d0-4d5e-b782-66300b31122b)

**Comment by zxsleebu** [comment]
+1

**Comment by JakeDHS07** [comment]
![Screenshot_20240614-015555](https://github.com/Mahmud0808/Iconify/assets/6186123/407ac2aa-0955-4251-b6ae-7de1fd69bba4)

Not sure if this is related, but figured I would mention it just in case. When switching to default notification style, the entire notification shows as transparent instead of just half

**Comment by JakeDHS07** [comment]
A quick update. It appears I have found a solution possibly. Looking around I noticed the highlighted option in Tweaks->Xposed Menu->Themes
Turning it on didn't seem to do anything but after turning it back off a notification received after that was back to normal? Will keep checking but for right now that seems to have triggered something that fixed it. Not sure how. 
EDIT Just got another notification and yeah it seems something was reset by that toggle cause it's working normal now
![Screenshot_20240614-163616~2](https://github.com/Mahmud0808/Iconify/assets/6186123/08653971-0dd4-497b-b13e-5d4e6e29ef85)
![Screenshot_20240614-170242](https://github.com/Mahmud0808/Iconify/assets/6186123/12b8ff4a-0d44-48d5-bc5f-4a2f28fcb852)

**Comment by Mahmud0808** [comment]
> A quick update. It appears I have found a solution possibly. Looking around I noticed the highlighted option in Tweaks->Xposed Menu->Themes Turning it on didn't seem to do anything but after turning it back off a notification received after that was back to normal? Will keep checking but for right now that seems to have triggered something that fixed it. Not sure how.

You're right. That option is not required anymore after android 14 QPR3 update.
