### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by mhnugr** [Mahmud0808/Iconify#523]
### Describe the feature

Please add a feature to enlarge and reduce icons

### Why would it be useful to add?

Because I'm bored with the standard icon size

### Example(s)

I don't have an example, you know what I mean

**Comment by Mahmud0808** [comment]
What icon are you talking about?

**Comment by mhnugr** [comment]
Icon app

**Comment by Mahmud0808** [comment]
That's a launcher related feature. Use 3rd party launchers if needed.

**Comment by mhnugr** [comment]
Or maybe can you add a feature to move the location of the toggle brightness? From top to bottom for example
