### ISSUE TITLE
Iconify works perfectly fine, but after restart and first time locking the screen, the SystemUI bootloops

### ISSUE THREAD

**Issue by BLADR-ONE** [Mahmud0808/Iconify#527]
### Describe the bug

While theming with iconify systemui restarts, and desirable changes that were made show up nicely. Locking the screen and unlocking work perfectly. After a reboot with the same settings, systemui loades without problem, i can log in, do anything, but after locking the screen, when i try to unlock the SystemUI enters a bootlop that renders the phone unusable till a restart. onlyode to prevent system from bootlooping afte restarting and locking the phone is to revert all changes iconify made. I don't have very much expirence with rom theming, but i have used in the past aosp mods and that(atleast the fetures that work) works flawlessly, no crashes in the systemui. Thanks for reading my post and hope to soon hear from you! 🤝

### Steps to reproduce

1. Go to iconify 
2. Set almost any customization
3. Reboot
4. Lock phone
5. Try to unlock
6. See SystemUI bootloops 

### Expected behavior

SystemUI doesn't bootloop. 

### Device information

- Device: Nubia Red Magic 5g
- OS: LineageOS 20, march security patch, Android version 13.0 QPR2.
- App version: 6.8.0
- Magisk/KernelSU: APatch latest version, Latest LSposed with Zygisk Next

**Comment by Mahmud0808** [comment]
Are you using depth wallpaper feature or custom lockscreen clock? Try disabling these and check if issue can be reproduced.

**Comment by BLADR-ONE** [comment]
Hi, after some more experimeting(turning on then restetting every feature after thesting for the crash), I've realised that the reason that sysui is crashing is changing the system iconpack. LineageOS has a similar feature baked right in, but i figured that it being left on default wasn't gonna mess with the iconify one.
 I since turned that off and the crash seems to be gone. 
Is there a way maybe to make iconify force override the LineageOS iconpack customizer, or even to disable the LineageOS one?

**Comment by Mahmud0808** [comment]
It is possible but it requires iconify to be a system app, which I don't intend to make.

**Comment by BLADR-ONE** [comment]
> It is possible but it requires iconify to be a system app, which I don't intend to make.

So if i make it a system app (aka i move it's apk in the system app folder) would it work?

**Comment by Mahmud0808** [comment]
No, it's not that. It requires an app to be system app to change settings preferences, which I don't intend to do or implement in iconify.

**Comment by BLADR-ONE** [comment]
> No, it's not that. It requires an app to be system app to change settings preferences, which I don't intend to do or implement in iconify.

Got it, so it would need modify system settings permission, or smt like that. Thanks so much for your support have a nice day!
