### ISSUE TITLE
[FEATURE] Request to add multilingual support Chinese

### ISSUE THREAD

**Issue by zzj2039** [Mahmud0808/Iconify#53]
### Describe the feature

multilingual support

### Why would it be useful to add?

help me use this project better

### Example(s)

no

**Comment by Mahmud0808** [comment]
You can create a pull request with missing translations.

To contribute to this project,

- Fork the repo.
- Clone the forked repo to your local machine.
- Open the project.
- Make your changes.
- Create a pull request. Give a proper title and description to your PR.
