### ISSUE TITLE
[BUG] The Latest 6.8.0 crashes on installing

### ISSUE THREAD

**Issue by Ahplla** [Mahmud0808/Iconify#534]
### Describe the bug

No installer recognizes the apk as a valid package.

### Steps to reproduce

Installing

### Expected behavior

Install

### Device information

- OS: [Android 11]
- App version: [e.g. v6.8.0]

**Comment by tomaszk8266** [comment]
The installer doesn't recognize Iconify as a valid package due to too low SDK version (minimum required version is 30 - A12, your is 29 - A11)

Iconify is for AOSP-based ROMs with Android 12 and later, and support for prior versions nor OEM skins won't ve added. Read readme.

**Comment by Ahplla** [comment]
I'm im AOSP-based ROMs with Android 11, this is the first time in years, that I see an app as demanding in this aspect, that's sad

**Comment by tomaszk8266** [comment]
Android 12 made huge changes to the UI, supporting older devices would require a lot of work which is simply not worth it.

**Comment by Ahplla** [comment]
> Android 12 made huge changes to the UI, supporting older devices would require a lot of work which is simply not worth it.

Thanks for answering. Which old version of Iconify supports Android 11?

**Comment by tomaszk8266** [comment]
There is no iconify version that support A11. Since its developement has started, it was focused on A12+.
