### ISSUE TITLE
[FEATURE] No Depth wallpaper on AOD

### ISSUE THREAD

**Issue by Venokii** [Mahmud0808/Iconify#536]
### Describe the feature

Please add an option to completely hide Depth wallpaper on AOD, without waiting for it to disappear.

### Why would it be useful to add?

Would make the Depth Wallpaper better.

### Example(s)

.

**Comment by Mahmud0808** [comment]
Added for android 14 in https://github.com/Mahmud0808/Iconify/commit/320cc937557571977af932229e2553ddf2747d8d and previous android versions in https://github.com/Mahmud0808/Iconify/commit/8771ff8220ae40c9790d7f995c3f6c56a57fab8d
