### ISSUE TITLE
(REQUEST) Hide just battery percent symbol from status bar

### ISSUE THREAD

**Issue by allday5850** [Mahmud0808/Iconify#544]
### Describe the feature

I would like to remove the percent symbol from status bar but leave just the integer. 

### Why would it be useful to add?

Because everyone knows what that number represents. It's taking up valuable & limited real estate in the status bar. It just seems a bit redundant to show the percent symbol.  Just leave the Integer and no one would be stumped as to what the number with no accompanied "%" represents

### Example(s)

There is a user on XDA by username Tulsadiver who creates mods for Pixels that has accomplished this, along with many other things with a magisk module.  He's been doing it for the past few series of devices maybe even longer.  So it's very possible. Here is link to his mods page on XDA [https://xdaforums.com/t/android-15-beta-ap31-statusbar-and-misc-mods.4667173/](url)

**Comment by Mahmud0808** [comment]
Not very useful. % doesn't take a lot of space. Or you can just use a custom battery style like the iOS 16 style. It only has the text and no percentage symbol.
