### ISSUE TITLE
[BUG] wrong wallpaper showing behind open apps

### ISSUE THREAD

**Issue by eddieofny** [Mahmud0808/Iconify#548]
### Describe the bug

Forgive me if I'm not using the correct terminology here but I use Iconify to add back the blurred wallpaper behind my notifications and open apps (the thing that appears when you press the square button on nav bar where you can cycle through apps you have running currently).

I also started using Dark Mode Live Wallpaper (https://f-droid.org/en/packages/com.github.cvzi.darkmodewallpaper/) to change wallpapers when I swotch between dark and light mode.

Whenever I look at my open apps, rather than my wallpaper appearing behind them, the Dark Mode Live Wallpaper logo shows up instead.

I've attached screenshots to better explain what I mean. The first 2 show a light mode and dark mode wallpaper behaving as expected. The last one is what I see on the recent's screen, no matter what mode I'm in.

Not a huge deal, just hoping it can be fixed. Thanks!

### Steps to reproduce

Click recents button
See wrong wallpaper

### Expected behavior

To see the correct wallpaper

### Screenshots

![Screenshot_20240719-093703](https://github.com/user-attachments/assets/e706f502-89c6-4f7d-b53c-c8205af975d0)
![Screenshot_20240719-093515](https://github.com/user-attachments/assets/30ab16c0-2657-4526-a9b1-c837f45e3415)
![Screenshot_20240719-092403](https://github.com/user-attachments/assets/5fc64b14-fa1d-4c75-b9a5-f224d9183e2a)

### Device information

- Device: Motorola Moto G 5g 2023
- OS: Stock ROM, Android 14
- App version: 6.8.0
- Magisk: v27.0

**Comment by cvzi** [comment]
Hi, I am the developer of the Dark Mode Live Wallpaper. Is this still a problem? 
If yes, would you be willing to to test a modified version of Dark Mode Live Wallpaper, I could give you an apk file to test?
[Someone else has reported this problem as well](https://github.com/cvzi/darkmodewallpaper/issues/185), and the solution seems to be to make the icon transparent or maybe just remove the icon from the app.

**Comment by eddieofny** [comment]
> Hi, I am the developer of the Dark Mode Live Wallpaper. Is this still a problem? If yes, would you be willing to to test a modified version of Dark Mode Live Wallpaper, I could give you an apk file to test? [Someone else has reported this problem as well](https://github.com/cvzi/darkmodewallpaper/issues/185), and the solution seems to be to make the icon transparent or maybe just remove the icon from the app.

Yes and yes, thank you for the reply

**Comment by cvzi** [comment]
Thanks, please continue at https://github.com/cvzi/darkmodewallpaper/issues/185#issuecomment-2283898517

**Comment by Mahmud0808** [comment]
As an unrelated issue, I am closing it
