### ISSUE TITLE
[FEATURE] pls make custom scale

### ISSUE THREAD

**Issue by Hanifz99** [Mahmud0808/Iconify#549]
### Describe the feature

Make custom scale for fit the screen 

### Why would it be useful to add?

Because i try scalling lockscreen clock on 1.5x is looks small I hope there is custom scale for Change size to suit me

### Example(s)

![Screenshot_20240721-213047](https://github.com/user-attachments/assets/f117adb7-fb57-4afd-8129-bbc731798cab)
![Screenshot_20240721-213055](https://github.com/user-attachments/assets/e234fea3-ab69-4cb7-8505-c648ed32d5ab)

### Additional context

And add custom scaling text,image,deptwallpaper,and more Which is related to size

**Comment by Mahmud0808** [comment]
Is this a tablet device?

**Comment by Hanifz99** [comment]
Yes
