### ISSUE TITLE
[FEATURE] Option to hide QS in lock screen 

### ISSUE THREAD

**Issue by Yazed-Hasan** [Mahmud0808/Iconify#550]
### Describe the feature

hide the quick settings panel in lock screen 

### Why would it be useful to add?

useful for privacy in some stock roms like los no option for that is annoying that anyone can use the phone

### Example(s)

the panel can't be accessible in lock screen like in superior Rom and cr droid we can hide the Qs panel in Lock Screen 

### Additional context
No Response

**Comment by Yazed20** [comment]
No Respawn

**Comment by Yazed-Hasan** [comment]
No Response

**Comment by Mahmud0808** [comment]
> useful for privacy in some stock roms like los no option for that is annoying that anyone can use the phone

Wrong. All the sensitive tiles require you to unlock your phone to toggle.

**Comment by Yazed-Hasan** [comment]
> > useful for privacy in some stock roms like los no option for that is annoying that anyone can use the phone
> 
> Wrong. All the sensitive tiles require you to unlock your phone to toggle.

Exactly : )

you need to unlock your phone to toggle , so that not anyone can turn things on or off like wifi and blutooth or mobile data in the end you cant access the QS in lock screen

**Comment by Yazed20** [comment]
> > > useful for privacy in some stock roms like los no option for that is annoying that anyone can use the phone
> > 
> > 
> > Wrong. All the sensitive tiles require you to unlock your phone to toggle.
> 
> Exactly : )
> 
> you need to unlock your phone to toggle , so that not anyone can turn things on or off like wifi and blutooth or mobile data in the end you cant access the QS in lock screen

**Comment by Mahmud0808** [comment]
So if all sensitive tiles are already locked by default, why do you need to hide QS on lockscreen?

**Comment by Yazed20** [comment]
> So if all sensitive tiles are already locked by default, why do you need to hide QS on lockscreen?

you miss understand me look no privacy at all so bad 


https://github.com/user-attachments/assets/26d698fc-ba42-4b78-9f10-78239121ab90

**Comment by Yazed-Hasan** [comment]
> So if all sensitive tiles are already locked by default, why do you need to hide QS on lockscreen?

you really miss understand me look no privacy: )


https://github.com/user-attachments/assets/db0e5533-190a-46d9-99cd-3e3181e55602

**Comment by Alexaras94** [comment]
Hello is this feature still available?

**Comment by Mahmud0808** [comment]
> Hello is this feature still available?

Available in debug builds for android 15+ users.

**Comment by Alexaras94** [comment]
Thank you very much Love your work.
