### ISSUE TITLE
Accent colors don't stick

### ISSUE THREAD

**Issue by SkyTrax79** [Mahmud0808/Iconify#551]
### Describe the bug

when we apply a primary and secondary accent color, it works correctly and we get the real chosen colors if we deactivate Monet engine.  The problem is that the settings do not hold when you close the phone screen and reopen it, The colors of the Quick settings remain with gradients but the color of the switches returns to a color that must come from Monet because it is not  a chosen color.

Monet is disabled everywhere but still, it seems we can't get rid of it for good.

### Steps to reproduce

Choose primary and secondary colors, shut off the phone screen and wake up the phone and half the colors accent are lost.

### Expected behavior

Colors stick and also survive a reboot when you apply them.

### Device information

Pixel 6, stock ROM Android 14 with security patch July 2024

Rooted with Magisk 27

Iconify 6.8.0

**Comment by SkyTrax79** [comment]
I don't really know what exactly I did but for the first time the 2 chosen colors remained after turning the screen off and on or it was a coincidence and Monet chose a color for me  similar because the accents of some native apps like GBoard became pale gray, the rest remained the blue I had selected.   This is already a big progress.

**Comment by Mahmud0808** [comment]
Try out [ColorBlendr](https://github.com/Mahmud0808/ColorBlendr). Iconify's color engine feature has been dropped and won't get any significant update.

**Comment by silverwings15** [comment]
how do you completely disable Iconify's color engine? for example if you enable a custom brightness slider, it will use the basic colors in the engine, unless you enable Monet Gradient or Monet Accent

**Comment by SkyTrax79** [comment]
I had stopped using Colorblendr because it's worse than Iconify, it's logically impossible to choose custom colors when you're forced to choose a theme that changes all the colors.

You can choose between Neutral, Monochrome, Tonal Spot, Vibrant, Rainbow, Expressive, Fidelity, Content, Fruit Salad. There's no OFF button, all these themes will modify your selection to some extent. You choose your colors and then decide how Android will work with them. We're still limited by Android's native system, which doesn't allow us to choose colors precisely, but at least we're not limited to a palette of ten or so colors.

The accurate color selection works and sticks for the Quick Settings and the battery usage graph, but the accent for settings category titles and switches will always end up reverting to the color that had been selected in the native Wallpaper and Styles section, and by default you're forced to choose a predefined color, Iconify and Color Blendr and all the others just work on top of the native system that is always on and that's where all the weird mixes come from and override your choices.  Right now I'm typing and my accent is a kind of purple that I chose in  Wallpaper and Settles BEFORE I started setting up colors with another app.   Also the quicks settings and the battery bar graph are in a category independent of all the rest of the accents.   they have their own color scheme and tend to stay.

 Don't worry, it's not your fault, it's the way the system was designed.
________________________________
De : DrDisagree ***@***.***>
Envoyé : 25 juillet 2024 11:55
À : Mahmud0808/Iconify ***@***.***>
Cc : SkyTrax79 ***@***.***>; Author ***@***.***>
Objet : Re: [Mahmud0808/Iconify] Accent colors don't stick (Issue #551)


Try out ColorBlendr<https://github.com/Mahmud0808/ColorBlendr>. Iconify's color engine feature has been dropped and won't get any significant update.

**Comment by SkyTrax79** [comment]
You can't disable it, it acts as an extension of the native color system by adding more configuration choice In Color Blendr there is a OFF switch that and it simply make the return of the few colors available in Wallpapers and Styles that are empty when you use Iconify.  Something they will reappear with certain setting combination of Iconify, just try by yourself, set a primary and secondary color in Iconify and go to Wallpaper and Styles and you will see that the plain colors normally available are gone BUT the the king of 3 colors circles are still there and there is always one selected, the primary color on the top of the circles are the one that Android will revert to after some times, those 3 color circles of the choices of the app Neutral, gray, fruit Salad, Effective etc.  There is no all off neutral position anywhere, that's it becomes a mess really fast.  What I do is I select the least worst color of the basic Android choices I like, like dark blue gray, there is only 6 or 7, and that becomes my accents and I change the Quick Settings colors to my liking.
________________________________
De : silverwings15 ***@***.***>
Envoyé : 25 juillet 2024 21:54
À : Mahmud0808/Iconify ***@***.***>
Cc : SkyTrax79 ***@***.***>; Author ***@***.***>
Objet : Re: [Mahmud0808/Iconify] Accent colors don't stick (Issue #551)


how do you completely disable Iconify's color engine? for example if you enable a custom brightness slider, it will use the basic colors in the engine, unless you enable Monet Gradient or Monet Accent

**Comment by SkyTrax79** [comment]
Ok so with many other experiments it looks like the trick to get the exact color shade selected is in the setting Accurate Shades - Disable this to get exact chosen colors.  My 2 accents colors are corrects since yesterday, they have not reverted to something else and this setting is in the OFF position, so it seems to be the other way around what the description says.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mahmud0808** [comment]
This is how monet works. It takes one color and generates a bunch of colors with different shades to be used in different parts of the UI. So disabling accurate shade can get you the color you picked but not everywhere. Only in the places you are using custom styles from iconify like brightness bar, QS tiles, notification style etc.

**Comment by SkyTrax79** [comment]
Thanks a lot I better understand now.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
