### ISSUE TITLE
[FEATURE] How can i make lineageos Follow light/dark theme in quick settings?

### ISSUE THREAD

**Issue by Boom-Hacker** [Mahmud0808/Iconify#555]
### Describe the feature

[FEATURE] How can i make lineageos Follow light/dark theme in quick settings?

### Why would it be useful to add?

[FEATURE] How can i make lineageos Follow light/dark theme in quick settings?

### Example(s)

[FEATURE] How can i make lineageos Follow light/dark theme in quick settings?

### Additional context

[FEATURE] How can i make lineageos Follow light/dark theme in quick settings?

**Comment by Boom-Hacker** [comment]
the qs panel in lineageos is pure black even in light mode

**Comment by Mahmud0808** [comment]
Enable light theme from tweaks > xposed menu > themes. And also enable normal variant styles from styles > brightness bar, qs tiles and notifications

**Comment by Boom-Hacker** [comment]
thank it works.but the little setting botton keeps black

**Comment by Boom-Hacker** [comment]
![Screenshot_20240806-212050_Iconify](https://github.com/user-attachments/assets/a8eb7907-551b-4ea6-91f4-226a491792ab)

**Comment by Boom-Hacker** [comment]
uhhh?

**Comment by Mahmud0808** [comment]
Should be fixed in https://github.com/Mahmud0808/Iconify/commit/e508fee2300b91609b5faf61d5faa7daad7f7c41

**Comment by pvcodes** [comment]
> tweaks > xposed menu > themes

Where is this tweaks option? I'm on LOS 23

**Comment by Mahmud0808** [comment]
> > tweaks > xposed menu > themes
> 
> Where is this tweaks option? I'm on LOS 23

You won't get Home and Tweaks menu if you are using KernelSU v3+ without Metamodule
