### ISSUE TITLE
[BUG] Blur is not working

### ISSUE THREAD

**Issue by KAGEYAM4** [Mahmud0808/Iconify#560]
### Describe the bug

Blur is not working, previously it used to work.

### Steps to reproduce

1. Go to `Tweaks`
2. Click on `xposed menu`
3. Clisk on `transparency & Blur`
4. Restart Device
5. Blur dosen't apply

### Expected behavior

Blur applies.

### Device information

- Device: Realme 3 pro
- OS: Android 12, Awaken OS - 2.5 | Gaia | Vanilla
- App version: v6.8.0
- Magisk/KernelSU: v26.1(26100), Zygisk: `Yes`

### Additional context

I downgraded the app to v6.5.1 and on this version blur is working. On v6.8.0 the blur is not working. I cant say anything between  v6.5.1 and v6.8.0.

Here's the lsposed logs ->

[LSPosed_2024-08-09T21_17_25.699_iconify_v6.5.1.zip](https://github.com/user-attachments/files/16564439/LSPosed_2024-08-09T21_17_25.699_iconify_v6.5.1.zip)

[LSPosed_2024-08-09T21_30_08.169_iconify_v6.8.0_1.zip](https://github.com/user-attachments/files/16564440/LSPosed_2024-08-09T21_30_08.169_iconify_v6.8.0_1.zip)

[LSPosed_2024-08-09T21_36_08.133_iconify_v6.8.0_2.zip](https://github.com/user-attachments/files/16564443/LSPosed_2024-08-09T21_36_08.133_iconify_v6.8.0_2.zip)

`Note`:
- v6.8.0_1.zip has option `Aggressive Blur Enabler` set to off.
- v6.8.0_2.zip has option `Aggressive Blur Enabler` set to on.

**Comment by Mahmud0808** [comment]
Assisted on telegram. It was battery saver which disabled blur.

**Comment by hxka** [comment]
I've tried changing every battery saver policy and none of them affected blur disabling. Is there really no way to make battery saver not disable blur?
