### ISSUE TITLE
[BUG] Abnormal Behavior And Delay Of The QS Panel When Rotating The Screen

### ISSUE THREAD

**Issue by ThatAnnoyingVegan** [Mahmud0808/Iconify#564]
### Describe the bug

So, after V6.6.0 adjusting the value of the QQS Panel Top Margin under Xposed-QuickSettings, would increase the delay of screen rotation by 2 seconds, meaning, it takes 2 seconds (or more) for the screen to rotate whilst the QS panel is active. The same is true for version 6.8.0 Dev (#1945)

### Steps to reproduce

1. Downgrade to stable version v6.5.0 or 6.5.1 to experience the flawless screen rotation whilst the QS panel is active
2. Switch to any version thenceforward v6.6.0 or higher (stable or beta)
4. Change the value of the QQS and QS Panel Top Margin under Xposed-QuickSettings and 
5. Bring down the Qs Panel
6. Turn on auto rotation
7. Rotate the screen keeping the QS panel active
8. See error
9. Or if doesn't happen anything turn on Tablet Landscape mode 
10. See error
11. If doesn't happen anything turn on set smallest width to 600
12. This time, definitely see the error!

### Screenshots

https://github.com/user-attachments/assets/7a50eeb9-ef97-4c40-a438-03f03d4b9b8a

https://github.com/user-attachments/assets/5f17c6ae-2e82-4174-a839-5269f41d3ef3

https://github.com/user-attachments/assets/ced4bb5f-d068-4402-b7ef-ec209419fadd

### Device information

- Device: [Xiaomi Pomko Ape 1]
- OS: [Proton Plus A13.2, Aug 2023 SP]
- App version: [v6.6.0 forward...]
- Magisk/KernelSU: [Magisk Stable 27.0]
- LSP: [v1.9.2 official]

### Additional context

Nothing to remport

**Comment by Mahmud0808** [comment]
Will check if it's reproducible in my case

**Comment by Mahmud0808** [comment]
Can not reproduce this issue here. I always have a second delay no matter I enable anything or not, even with iconify disabled.

**Comment by ThatAnnoyingVegan** [comment]
As you can see in the video I'm running the Battery profile as it helps prolong the battery life obviously, as it underclocks the CPU and GPU frequencies a little without hurting the smoothness. 

With the Battery profile on I tested Iconify stable V6.5 and V6.5.1 They both did very well, especially v6.5 stable, there were no lag or animation glitches when rotating the screen with the Qs Panel active. 

But starting with version 6.6.0 this animation glitch occurs with 2 seconds or more delayed response if the battery profile is active, with Balance and Performance profile, the glitch goes away but the delay stays the same. So could you make it as it was with stable version 6.5? 

You must equate the CPU and GPU frequencies of your device to the frequencies of the Battery profile to be able to experience the glitch (the delay would be a little more obvious). ⚠️This Only Applies To Latest Iconify Builds⚠️

https://github.com/user-attachments/assets/33eb363a-f395-4e9a-ad86-ee849195cd7c

https://github.com/user-attachments/assets/27ae66ae-7aba-407d-8002-e37203aa6406

 https://github.com/user-attachments/assets/1b01aa55-cf83-4360-b08c-08e79f34dee8

**Comment by ThatAnnoyingVegan** [comment]
Let me know if part 3 is visible to you. If not I will reupload it.

**Comment by Mahmud0808** [comment]
I have looked into it an you are right. A few options cause this lag but there is no alternative. If previous versions work better for you then I would suggest you to stay on those builds. But those previous versions are broken on android 14 so I have to use newer methods to fix broken things. Also the tablet landscape only gets activated when phone is in landscape mode. So it will obviously create some delay while activating/deactivating and re-creating the quick settings panel. Unfortunately can't do much about it, it's out of my hand.
