### ISSUE TITLE
[BUG] Unresponsive Bottom QS Buttons In Tablet Landscape/Better QS

### ISSUE THREAD

**Issue by ThatAnnoyingVegan** [Mahmud0808/Iconify#565]
### Describe the bug

If the "Tablet Landscape" mode is on, after enabling Transparent QS Panel the bottom QS options like active apps, power menu, settings, etc. do not respond at all. See Video (Iconify test 6.8.0). The same is true for version 6.8.0 Dev (#1945)

### Steps to reproduce

1. Turn on Tablet Landscape or set 600 Smallest Width from Dev options
1.5. Turn on Transparent QS Panel
2. Bring down the QS panel
3. Turn on auto rotate 
4. Hold the phone horizontally 
5. Try touching the bottom QS buttons
6. See error

### Expected behavior

No such issue with V6.5.0 & V6.5.1

### Screenshots

https://github.com/user-attachments/assets/c622f6d5-0f49-4615-81a9-572c8c7bc244

### Device information

- Device: [Xiaomi Pomko Ape 1]
- OS: [Proton Plus A13.2, Aug 2023 SP]
- App version: [v6.6.0 forward...]
- Magisk/KernelSU: [Magisk Stable 27.0]
- LSP: [v1.9.2 official]

### Additional context

Nofin to remport

**Comment by ThatAnnoyingVegan** [comment]
Edited, read again plox.

**Comment by Mahmud0808** [comment]
This is android side bug. Increasing number of tiles/rows causes this issue.

**Comment by ThatAnnoyingVegan** [comment]
> This is android side bug. Increasing number of tiles/rows causes this issue.

I don't think so because, Iconify V6.7.0 stable and older versions are fine in this regard, meaning adjusting the Rows And Columns or enabling Qs Transparency doesn't affect the tangibility of the Bottom Qs Buttons of the Tablet Landscape!

With the 6.8.0 stable version, the bottom Qs options turn intangible only when the Transparent Qs is activated, increasing the Qs Tile Rows doesn't affect it. 

Whereas with 6.8.0 recent beta builds it happens even when you increase the Qs Tile Rows...

Thus, whoever tested it on your behalf was on the latest dev build which has exaggerated this issue further.


https://github.com/user-attachments/assets/c263284c-2314-455e-a047-efbf61f1f580

**Comment by ThatAnnoyingVegan** [comment]
[]()https://github.com/user-attachments/assets/58c109df-ab34-4e9b-9956-93b6ec0dfb29



[]()https://github.com/user-attachments/assets/918dea9c-a029-432b-9ade-472b19746cc2

**Comment by ThatAnnoyingVegan** [comment]
https://github.com/user-attachments/assets/4636915e-7f35-4e7f-a449-865f34fcf107

https://github.com/user-attachments/assets/624a4da2-40b9-4b7b-8dfe-762bf271e031

**Comment by Mahmud0808** [comment]
> I don't think so because, Iconify V6.7.0 stable and older versions are fine in this regard, meaning adjusting the Rows And Columns or enabling Qs Transparency doesn't affect the tangibility of the Bottom Qs Buttons of the Tablet Landscape!

You are probably wrong. This bug has been happening from a long time. Got reports even before 6.6.0 and it happens only when media player region is almost near the QS footer section. And it's fixed when media player region is moved away by removing rows or some other tricky ways.
