### ISSUE TITLE
[BUG] System UI crash after depth effect activation

### ISSUE THREAD

**Issue by Dschingan** [Mahmud0808/Iconify#569]
### Describe the bug

I am using the latest version of the Iconify and did the steps suggested for LSPosed. I am using a Corvus A12 leviathan GSI. I enabled the depth effect and selected the images, the system interface started to crash. Luckily I had the bootloop protector magisk module and I saved it. 

Is there anything I can try to solve this? 

### Steps to reproduce

1. Go to 'Depth Effect Wallpaper'
2. Click on 'Select Foreground/Background wallpaper'
3. Activate 'Depth effect wallpaper'
4. The screen goes black, comes back, goes black again, comes back... Loop

### Expected behavior

Successful operation

### Device information

- Device: [Realme C21-Y]
- OS: [Corvus Leviathan A12 (GSI)]
- App version: [6.8.0]
- Magisk/KernelSU: [Official Magisk 26.3]

**Comment by Mahmud0808** [comment]
Try debug version of iconify and let me know the result

**Comment by Dschingan** [comment]
> Try debug version of iconify and let me know the result

Where can I download the debug version? 

Edit: I found it, I need to download [this](https://github.com/Mahmud0808/Iconify/actions/runs/10441389665), right? I got confused when I saw the depth effect fix build below.

**Comment by Dschingan** [comment]
I tried [this](https://github.com/Mahmud0808/Iconify/actions/runs/10431106565) instead of what I mentioned above (If there is a difference, I will try the newest one.), but it didn't work. SystemUI crashes.

**Comment by Mahmud0808** [comment]
Provide lsposed logs

**Comment by Dschingan** [comment]
[kmsg.log](https://paste-drop.com/paste/kEUy42IqL1)
[modules_2024-08-18T15:51:39.354.log](https://paste-drop.com/paste/rMBy2Xr7ds)
[verbose_2024-08-18T15:51:39.352.log](https://paste-drop.com/paste/zoGhvNGDWG)

I couldn't export the logs with MiX. I copied and pasted the content, they are on the site.

**Comment by Mahmud0808** [comment]
You can just export the logs and send that file here. what you sent is useless

**Comment by Mahmud0808** [comment]
Your LSPosed maybe crashing. Clear logs, then reproduce the issue. And also iconify xposed mods has bootloop protection, it will disable itself if multiple crash detected under a certain time.

**Comment by Dschingan** [comment]
Problem is solved. I chose a different image that I found on Unsplash and it did not crash. I found the image that crashing on the Telegram channel. If you want, I can send that image for you to review.

**Comment by Mahmud0808** [comment]
> Problem is solved. I chose a different image that I found on Unsplash and it did not crash. I found the image that crashing on the Telegram channel. If you want, I can send that image for you to review.

If image size is very large, it can happen. Glad you figured it out.
