### ISSUE TITLE
[FEATURE] Show the actual notification icons on statusbar

### ISSUE THREAD

**Issue by sanalika** [Mahmud0808/Iconify#570]
### Describe the feature

Being able to set a transparent custom tint for statusbar, thus being able to remove the default tint effect on the notification icons. I'm not really sure if the statusbar color tint value allows RGBA inputs, but this is the closest guess i could make.

I have seen this option on crDroid 14 custom rom for Pixel 7a. But now i'm on LineageOS and my only option is to use Iconify, which doesn't have this feature.

### Why would it be useful to add?

Because i'm used to the old statusbar look from Android ICS times and now that i know it's possible, i would like to have this option on Iconify as well.

### Example(s)

My statusbar with transparent statusbar color tint on crDroid (the actual icons, as they are);
![image](https://github.com/user-attachments/assets/0947af54-f651-4379-98e1-f8d916e5d5e1)

My current statusbar with default (system) statusbar color tint on LineageOS (not the actual icons, tinted with system color tint);
![image](https://github.com/user-attachments/assets/a5f53f02-f36d-458f-b66b-43b87f333225)

The icons that i've been referring to;
![image](https://github.com/user-attachments/assets/a162f1f2-e4f2-49fb-bb8d-17a5199522d5)

**Comment by Mahmud0808** [comment]
It's not a tint. It's called colored statusbar icons on most (if not all) custom ROMs. It shows app launcher icon instead of the notification icon defined by the app to show on statusbar. I already have checked the implementation and it's very complicated to achieve through xposed hook.
