### ISSUE TITLE
Please add Advance gestures if possible.

### ISSUE THREAD

**Issue by sauravultra** [Mahmud0808/Iconify#573]
### Describe the feature

Advance gestures which allow long swipe actions to ve performed.
i.e kill aap, open apps and much more.

### Why would it be useful to add?

It will allow more control on gesture to kill aap so fast without clicking one on one exit.
![Screenshot_20240820-190914_Settings](https://github.com/user-attachments/assets/fefb9bcf-75ce-4cc0-89a3-ffce68d8a496)

### Example(s)

![Screenshot_20240820-190914_Settings](https://github.com/user-attachments/assets/7a46991b-d13f-42fb-991c-3c6532c349f6)

**Comment by Mahmud0808** [comment]
Doesn't fall under UI customization category
