### ISSUE TITLE
[FEATURE] 只保留XPosed的功能。

### ISSUE THREAD

**Issue by mofangsoft** [Mahmud0808/Iconify#582]
### Describe the feature

你们能否添加一个跳过选项，用于跳过设置向导，在我不想授予该软件root权限的情况下，只使用XPosed/Lsposed,对系统界面进行修改。在一些定制系统内，基于Magisk的功能可能会失效,但是基于XPosed的功能依然生效，所以我不想安装这个Magisk模块，只是想用基于XPosed的功能。

### Why would it be useful to add?

你们能否添加一个跳过选项，用于跳过设置向导，在我不想授予该软件root权限的情况下，只使用XPosed/Lsposed,对系统界面进行修改。在一些定制系统内，基于Magisk的功能可能会失效,但是基于XPosed的功能依然生效，所以我不想安装这个Magisk模块，只是想用基于XPosed的功能。

### Example(s)

你们能否添加一个跳过选项，用于跳过设置向导，在我不想授予该软件root权限的情况下，只使用XPosed/Lsposed,对系统界面进行修改。在一些定制系统内，基于Magisk的功能可能会失效,但是基于XPosed的功能依然生效，所以我不想安装这个Magisk模块，只是想用基于XPosed的功能。

**Comment by mofangsoft** [comment]
Could you add a skip option to bypass the setup wizard? I would like to use XPosed/Lsposed to modify the system interface without granting root permissions to the software. In some customized systems, functions based on Magisk may fail, but functions based on XPosed still work. So I don't want to install this Magisk module and just want to use the functions based on XPosed.

**Comment by Mahmud0808** [comment]
Long press on "Let's Go" button of onboarding page.

**Comment by mofangsoft** [comment]
可这并没有什么作用
