### ISSUE TITLE
[FEATURE] recent apps blur/transparency

### ISSUE THREAD

**Issue by DRA7** [Mahmud0808/Iconify#596]
### Describe the feature

A blur/transparency for recent apps or even better in like goodlock (samsung) they can change the whole recent app interface maybe that would be useful aswell

### Why would it be useful to add?

Better for lag if it was transparent and also looks nicer

### Example(s)

I don't have an example but you get the idea

**Comment by Mahmud0808** [comment]
The issue is there can be different launchers in different ROMs like pixel launcher / launcher3 / lawnchair / nothing launcher / custom ROM's own launchers. I can't manage all different launchers. It will be too much work for me.

**Comment by tomaszk8266** [comment]
On crdroid blur on recents screen is working if you enable qs blur
