### ISSUE TITLE
[BUG] when enabling blur the QS is very slow

### ISSUE THREAD

**Issue by DRA7** [Mahmud0808/Iconify#597]
### Describe the bug

I did everything from disabling the module and re-optimizing but it makes the QS really slow and the recent apps. Im on lineageos 21 galaxy s10 plus

### Steps to reproduce

When i click on re-optimize i notice it gets better for like a sec and then it gets back to laggy

### Expected behavior

Idk for it to work normally and not lag?

### Device information

- Device: [galaxy s10 plus]
- OS: [lineageOS 21]
- App version: [latest 6.8.0]
- Magisk: [27]

**Comment by Mahmud0808** [comment]
Does it only happen when enabling blur? Then it might be because of unoptimized ROM, or your device GPU isn't capable enough to handle the blur. Best you can do is reduce the blur intensity. If that doesn't work then you'll have to keep blur disabled. This is not a bug of iconify, so can't help more than that.

**Comment by DRA7** [comment]
Oh my bad! If it wasn't a bug...

But yeah only when enabling blur is s10 plus really not capable of that? Cause when i reoptimize in lsposed it works for few seconds then slows down

Does androoster effect anything?

**Comment by Mahmud0808** [comment]
No idea about that. You may provide logs, maybe it's not the blur but something else which is slowing down your device.

**Comment by DRA7** [comment]
Do you know any modules that can help improve performance by any chance im new to rooting and roms

**Comment by Mahmud0808** [comment]
Sorry can't help with that. Look into your device's xda forum or telegram group.
