### ISSUE TITLE
Hello Ui color notification icon bug ( not working)

### ISSUE THREAD

**Issue by Mrkhan28** [Mahmud0808/Iconify#602]
### Describe the bug

Colour icons is not working on motorola device. I tried to turn it on and restart the phone but it doesn't work. It is working fine on my redmi phone but not on motorola 

### Expected behavior

I tried dev version to check if colour notification icon is working or not but it is not working on Hello UI motorola device. please check and fix it if possible. 

### Device information

- Device: motorola edge 50 fusion
- OS: Hello UI, android 14
- App version: 6.8.0 dev
- Magisk/KernelSU: kernel su

**Comment by Mahmud0808** [comment]
Please read [FAQ](https://github.com/Mahmud0808/Iconify?tab=readme-ov-file#-faq)
