### ISSUE TITLE
[BUG] Add some kind of softbrick/bootloop protection

### ISSUE THREAD

**Issue by Damglador** [Mahmud0808/Iconify#614]
### Describe the bug

I tried to disabilng the "Keyboard change button" it caused SystemUI to crash and never start again, even in safe boot. I was forced to remove the app with adb from laptop.

More details:
After changing the setting "SystemUI is not responding" popped up, SystemUI crashed, black screen... That's it, rebooting didn't help, waiting causes Android to reboot automatically to recovery where it asks if I want to wipe my data (lol no, I don't), in safe mode it just infinitely "Starting phone" or something, without Android UI, only loading bar and text. And since it's not technically a bootloop, simple bootloop saver can't stop it by disabling the module (I think so, I haven't seen it in action and I hope I never will).

### Steps to reproduce

Idk if the same issue is possible to reproduce on other devices, either do I remember the stems to do it, and I don't want to install app back

### Expected behavior

Disable last modification to UI or reset everything to system default to preserve SystemUI working state.

### Device information

- Device: Ulefone Armor 14
- OS: factory ROM, Android 14
- App version: v6.8.0
- Magisk/KernelSU: KernelSU 11928

**Comment by Damglador** [comment]
Something like this thing I guess 
https://github.com/Magisk-Modules-Alt-Repo/systemui-bootloop
Tho since safe mode didn't help at all, that's not the best solution. Maybe it did help a bit by stopping the phone from turning off

**Comment by Mahmud0808** [comment]
There are lots of modules available for this specific purpose. All it does is reboot to safe mode which you can manually do too.

**Comment by Damglador** [comment]
> There are lots of modules available for this specific purpose. All it does is reboot to safe mode which you can manually do too.

All of the modules I was able to find are 2+ years old, the one in MMRL is archived and labeled as deprecated
