### ISSUE TITLE
[FEATURE] Volume percentage only 

### ISSUE THREAD

**Issue by EtiLB7** [Mahmud0808/Iconify#615]
### Describe the feature

I'm using iconify because it has volume percentage. Is it possible to give me volume percentage only module? 

### Why would it be useful to add?

My phone lags whenever I enable Xposed features, even if I only use volume percentage. Free ram—when there is no app running—goes from 2-1.9 to 1.3-1.4.

### Example(s)

Nothing

### Additional context

Nothing

**Comment by Mahmud0808** [comment]
Fork the repo, remove the modules you don't need from [HERE](https://github.com/Mahmud0808/Iconify/blob/beta/app/src/main/java/com/drdisagree/iconify/xposed/EntryList.kt), you only need `topPriorityCommonModPacks` and `VolumePanel::class.java`. Then build the APK.

**Comment by EtiLB7** [comment]
How do I build it though?

**Comment by Mahmud0808** [comment]
Android studio or github actions
