### ISSUE TITLE
[BUG] Lock screen Weather not showing after restart

### ISSUE THREAD

**Issue by sajadzare** [Mahmud0808/Iconify#616]
### Describe the bug

When i restart the phone, lock screen Weather not showing and i must disable and re enable lock screen Weather in Iconify to solve problem.
Notification and Location permission was enabled

### Expected behavior

When i restart the phone, lock screen Weather not showing and i must disable and re enable lock screen Weather in Iconify to solve problem.
Notification and Location permission was enabled

### Screenshots

Sweet Redmi note 10 pro max 

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 13.0 QPR3]
- App version: [e.g. v6.5.1]
- Magisk/KernelSU: [e.g. Magisk Delta 25.2]

**Comment by DHD2280** [comment]
Hello.
You missed the part to compile, so I will ask again:
App version? Include build number #
Android version?
ROM?

**Comment by sajadzare** [comment]
Android 14
ROM : Superior Extended fourteen 
Iconify debug version #2060

**Comment by DHD2280** [comment]
Can you provide lsposed logs?

**Comment by sajadzare** [comment]
Yes
[LSPosed_2024-09-18T11_10_19.505411.zip](https://github.com/user-attachments/files/17040345/LSPosed_2024-09-18T11_10_19.505411.zip)

**Comment by Mahmud0808** [comment]
Try enabling "Restart SystemUI after boot" from iconify settings
