### ISSUE TITLE
[BUG] Upon new update the app crashes upon trying to install the new magisk module 

### ISSUE THREAD

**Issue by UltimateSentryTurret** [Mahmud0808/Iconify#620]
### Describe the bug

Basically as soon as I open the app and get past the first 2 welcome pages, as soon as it attempts to download the new magisk module, it crashes

### Steps to reproduce

1. Go to 'Iconify Github'
2. Click on 'Releases'
3. Scroll down to 'v6.9.0'
4. Download the APK
5. Install it
6. Go to inconify
7. Get past the 2 welcome pages
8. Get to part 3 of the welcome page
9. Attempt to have the app download the module 
10. It should crash & kick you out

### Expected behavior

The app crashes & kicks you out of the app.

### Device information

- Device: [Google Pixel 7a]
- OS: [stock ROM Android 14]
- App version: [v6.8]
- Magisk/KernelSU: [Magisk 27.0}

### Additional context

This happened to me after trying to update the app from v6.8.0

**Comment by DHD2280** [comment]
Clean install the new version.
