### ISSUE TITLE
[BUG] SystemUI crash loop and reboot when trying to play a NewPipe video

### ISSUE THREAD

**Issue by tomaszk8266** [Mahmud0808/Iconify#622]
### Describe the bug

In the latest version, after a clean flash (after upgrade it has worked, but there were many other bugs), when I try to play a NewPipe video, the phone enters into a SystemUI crash loop and then reboots. It happens even if no tweaks were applied.

### Steps to reproduce

1. Clean install Iconify 6.9.0
2. Try to play a NewPipe video
3. SystemUI will start crashing, and the phone should also reboot soon to recovery with the "Data corrupted" message, but after selecting "Try again" it should work again.

### Expected behavior

It shouldn't crash

### Device information

- Device: Oneplus 6T (fajita)
- OS: LOS 21 (A14, I think it's QPR1 but I'm not sure)
- App version: 6.9.0
- Magisk/KernelSU: Magisk 27.0

**Comment by Mahmud0808** [comment]
Provide logs

**Comment by tomaszk8266** [comment]
Which logs? And how to dump them if the device reboots?

**Comment by DHD2280** [comment]
> Which logs? And how to dump them if the device reboots?

LSPosed logs.

**Comment by Mahmud0808** [comment]
No logs provided, hence closing this issue.
