### ISSUE TITLE
Crash when restoring color configs/app configs

### ISSUE THREAD

**Issue by Richard38907** [Mahmud0808/Iconify#624]
### Describe the bug

Try to restore a backup (created with 6.9.0 or earlier) and see the app crash
Logcat here:
[logcat.txt](https://github.com/user-attachments/files/17073698/logcat.txt)

### Steps to reproduce

1. Go to 'Restire backup'
2. Click on 'the backup file'
3. Confirm ok on the dialog box

### Expected behavior

Restoring config (like 6.7.0)

### Device information

- Device: [OnePlus nord]
- OS: [Pixel expérience 13 (patch September 2023)]
- App version: [e.g. v6.9.0]
- Magisk/KernelSU: [Magisk 27.0]

**Comment by Mahmud0808** [comment]
![image](https://github.com/user-attachments/assets/86c3deb9-176e-4bc8-b57a-c0a05cf6d6fc)

There is no separate configs anymore, all combined into one. So do not restore backups from old version.
