### ISSUE TITLE
[BUG] Random crash when in Landscape mode

### ISSUE THREAD

**Issue by DRA7** [Mahmud0808/Iconify#631]
### Describe the bug

Sometimes it crashes sometimes it doesn't the status bar icons disappear and shows back again and the phone slows down like the whole screen freezes

### Steps to reproduce

Idk 

### Expected behavior

To work normally ig?

### Device information

- Device: galaxy s10 plus exynos
- OS: LineageOS 21
- App version: 6.9.0
- Magisk/KernelSU: magisk  v27

### Additional context

I dont have when it happens

**Comment by DHD2280** [comment]
Are you using xposed mod?
Any additional settings?
Please include lsposed logs

**Comment by DRA7** [comment]
> Are you using xposed mod? Any additional settings? Please include lsposed logs

Yes i am 

Which one? Where do i find it?

**Comment by Mahmud0808** [comment]
Open the issue when you got LSPosed logs attached.

**Comment by DRA7** [comment]
> Open the issue when you got LSPosed logs attached.

But where do i get it from

**Comment by Mahmud0808** [comment]
Obviously in LSPosed app

**Comment by DRA7** [comment]
> Obviously in LSPosed app

[LSPosed_2024-10-14T18_14_08.055710.zip](https://github.com/user-attachments/files/17365971/LSPosed_2024-10-14T18_14_08.055710.zip)

**Comment by Mahmud0808** [comment]
Can you clear the logs, reproduce the crash and send logs again? Also use [logfox](https://github.com/F0x1d/LogFox) app this time.

**Comment by DRA7** [comment]
> Can you clear the logs, reproduce the crash and send logs again? Also use [logfox](https://github.com/F0x1d/LogFox) app this time.

I installed logcat and got the crash again but it doesn't show up in logcat idk why but what happens is when i rotate my device the systemui crashes and i see the statusbar icons disappear and return and my homescreen turns black. Is there other ways i can share logs cause it doesn't show any logs!

**Comment by Mahmud0808** [comment]
If you are using header clock or oneplus QS style, disable these and check.

**Comment by DRA7** [comment]
> If you are using header clock or oneplus QS style, disable these and check.

I was using header clock i disabled it and tried to go on youtube and use it normally the same thing happens and when i unlock the phone sometimes it does the same thing the systemui restarts

**Comment by Mahmud0808** [comment]
Disable everything from iconify settings. Enable one by one and test. I can't help if I don't know what option is causing issue.

**Comment by DRA7** [comment]
> Disable everything from iconify settings. Enable one by one and test. I can't help if I don't know what option is causing issue.

Okay thanks for help I'll try what you told me to do and if i find which one is it i will keep you updated but for now i can live with it it doesn't happen so often so ig itsnot that noticeable.

**Comment by DRA7** [comment]
> Disable everything from iconify settings. Enable one by one and test. I can't help if I don't know what option is causing issue.

Hey, lately it's been crashing alot i got a logfox error i really need help with this it just keeps restarting systemui randomly its annoying alot 

ANR in com.android.systemui
PID: 7278
Reason: Input dispatching timed out ([Gesture Monitor] edge-swipe (server) is not responding. Waited 5001ms for MotionEvent).
ErrorId: 3e687f98-739c-4df5-8955-94c1f869314f
Frozen: false
Timestamp: 2024-10-24 13:12:49.873+0300
Load: 38.27 / 22.39 / 18.87
----- Output from /proc/pressure/memory -----
some avg10=22.34 avg60=9.39 avg300=2.80 total=74161812
full avg10=3.59 avg60=1.88 avg300=0.68 total=34331693
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=64.84 avg60=37.69 avg300=21.46 total=1035692886
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=5.25 avg60=2.77 avg300=1.11 total=59111047
full avg10=0.10 avg60=0.21 avg300=0.22 total=29968627
----- End output from /proc/pressure/io -----
CPU usage from 71ms to 20123ms later (2024-10-24 13:12:50.125 to 2024-10-24 13:13:10.177):
  134% 6713/system_server: 104% user + 29% kernel / faults: 326234 minor 1539 major
  58% 7278/com.android.systemui: 49% user + 9.1% kernel / faults: 102563 minor 743 major
  54% 29621/com.f0x1d.logfox: 35% user + 18% kernel / faults: 66766 minor 37 major
  26% 1385/kswapd0: 0% user + 26% kernel
  25% 6345/netd: 23% user + 1.1% kernel / faults: 1404 minor 36 major
  19% 14142/com.google.android.apps.youtube.music: 12% user + 6.7% kernel / faults: 10879 minor 404 major
  14% 6368/android.hardware.audio.service: 13% user + 1.7% kernel / faults: 773 minor 78 major
  14% 7746/com.android.launcher3: 9% user + 5.1% kernel / faults: 32600 minor 1089 major
  14% 1709/com.google.android.apps.translate: 11% user + 2.6% kernel / faults: 67069 minor 80 major
  10% 17088/com.google.android.gms: 8.1% user + 2.5% kernel / faults: 33114 minor 356 major
67% TOTAL: 44% user + 22% kernel + 0.3% iowait + 0.7% softirq
CPU usage from 140ms to 1641ms later (2024-10-24 13:12:50.193 to 2024-10-24 13:12:51.694) with 99% awake:
  165% 6713/system_server: 108% user + 56% kernel / faults: 15853 minor 700 major
    44% 6723/Signal Catcher: 29% user + 15% kernel
    29% 7072/binder:6713_8: 26% user + 2.2% kernel
    23% 3935/AnrAuxiliaryTas: 4.4% user + 19% kernel
    11% 6854/HeapTaskDaemon: 9.7% user + 2.2% kernel
    8.2% 6905/android.fg: 5.9% user + 2.2% kernel
    5.2% 9405/binder:6713_12: 3.7% user + 1.4% kernel
    3.7% 10575/binder:6713_1C: 2.9% user + 0.7% kernel
    2.2% 6713/system_server: 1.4% user + 0.7% kernel
    2.2% 6917/ActivityManager: 1.4% user + 0.7% kernel
    2.2% 7032/binder:6713_6: 1.4% user + 0.7% kernel
    2.2% 9393/binder:6713_10: 2.2% user + 0% kernel
    1.4% 6906/android.ui: 0.7% user + 0.7% kernel
    1.4% 6909/android.anim: 0.7% user + 0.7% kernel
    1.4% 6916/android.bg: 1.4% user + 0% kernel
    1.4% 7019/SensorService: 0.7% user + 0.7% kernel
    1.4% 7125/NetworkStats: 0.7% user + 0.7% kernel
    1.4% 7947/binder:6713_B: 1.4% user + 0% kernel
    1.4% 9798/binder:6713_15: 0.7% user + 0.7% kernel
    1.4% 9806/binder:6713_17: 1.4% user + 0% kernel
    1.4% 9807/binder:6713_18: 1.4% user + 0% kernel
    1.4% 11229/binder:6713_1E: 1.4% user + 0% kernel
    0.7% 3926/AnrConsumer: 0% user + 0.7% kernel
    0.7% 6853/Jit thread pool: 0.7% user + 0% kernel
    0.7% 6908/android.display: 0.7% user + 0% kernel
    0.7% 6923/LowMemThread: 0% user + 0.7% kernel
    0.7% 6924/OomAdjuster: 0% user + 0.7% kernel
    0.7% 6930/bgres-controlle: 0.7% user + 0% kernel
    0.7% 6997/binder:6713_3: 0.7% user + 0% kernel
    0.7% 6999/binder:6713_4: 0.7% user + 0% kernel
    0.7% 7138/ConnectivitySer: 0.7% user + 0% kernel
    0.7% 7145/ranker: 0.7% user + 0% kernel
    0.7% 7159/AudioService: 0.7% user + 0% kernel
    0.7% 7183/shortcut: 0.7% user + 0% kernel
    0.7% 7209/GameManagerServ: 0.7% user + 0% kernel
    0.7% 7650/binder:6713_9: 0% user + 0.7% kernel
    0.7% 9413/binder:6713_13: 0.7% user + 0% kernel
    0.7% 9426/binder:6713_14: 0.7% user + 0% kernel
    0.7% 9819/binder:6713_19: 0.7% user + 0% kernel
    0.7% 9857/binder:6713_1B: 0.7% user + 0% kernel
    0.7% 10576/binder:6713_1D: 0% user + 0.7% kernel
    0.7% 15594/binder:6713_20: 0% user + 0.7% kernel
  41% 6345/netd: 38% user + 2.8% kernel / faults: 167 minor
  30% 1385/kswapd0: 0% user + 30% kernel
  33% 7278/com.android.systemui: 27% user + 6% kernel / faults: 3029 minor 43 major
    12% 7278/ndroid.systemui: 11% user + 0.7% kernel
    9.7% 7285/Signal Catcher: 6% user + 3.7% kernel
    9% 7473/wmshell.main: 8.2% user + 0.7% kernel
    1.5% 7745/ScreenDecoratio: 1.5% user + 0% kernel
    0.7% 7482/SysUiBg: 0.7% user + 0% kernel
    0.7% 7484/BroadcastRunnin: 0.7% user + 0% kernel
    0.7% 9107/binder:7278_E: 0.7% user + 0% kernel
  22% 1709/com.google.android.apps.translate: 19% user + 2.6% kernel / faults: 8175 minor 6 major
    10% 1910/ChromiumNet: 8.5% user + 1.9% kernel
    10% 2151/ChromiumNet: 9.8% user + 0.6% kernel
    0.6% 1709/.apps.translate: 0% user + 0.6% kernel
  25% 7746/com.android.launcher3: 17% user + 8.3% kernel / faults: 2218 minor 289 major
    12% 7773/launcher-loader: 7.5% user + 4.5% kernel
    5.3% 7746/droid.launcher3: 3.7% user + 1.5% kernel
    5.3% 9439/RenderThread: 5.3% user + 0% kernel
    2.2% 17155/mali-cmar-backe: 0.7% user + 1.5% kernel
    0.7% 11850/binder:7746_8: 0.7% user + 0% kernel
    0.7% 17149/mali-mem-purge: 0.7% user + 0% kernel
  23% 14142/com.google.android.apps.youtube.music: 13% user + 9.9% kernel / faults: 1623 minor 30 major
    6.6% 14289/ExoPlayer:Playb: 4.9% user + 1.6% kernel
    5.8% 15742/MediaCodec_loop: 2.4% user + 3.3% kernel
    3.3% 14142/s.youtube.music: 2.4% user + 0.8% kernel
    1.6% 14182/BG Thread #4: 0.8% user + 0.8% kernel
    1.6% 14610/HwBinder:14142_: 0.8% user + 0.8% kernel
    0.8% 14173/BG Thread #0: 0.8% user + 0% kernel
    0.8% 14184/BG Thread #5: 0% user + 0.8% kernel
    0.8% 14215/ChromiumNet: 0% user + 0.8% kernel
    0.8% 14218/BG Thread #7: 0.8% user + 0% kernel
  14% 2807/com.twitter.android: 11% user + 2.6% kernel / faults: 2166 minor 195 major
    9.9% 3074/longRunning-Thr: 9.3% user + 0.6% kernel
    3.3% 3066/io-core-Thread-: 1.3% user + 1.9% kernel
   +0% 3980/pool-34-thread-: 0% user + 0% kernel
   +0% 3983/pool-35-thread-: 0% user + 0% kernel
  15% 6368/android.hardware.audio.service: 14% user + 1.4% kernel / faults: 5 minor
    10% 24705/effect: 8.6% user + 1.4% kernel
    5% 17536/reader: 5% user + 0% kernel
    1.4% 24692/writer: 0% user + 1.4% kernel
  13% 6437/surfaceflinger: 6.5% user + 6.5% kernel / faults: 302 minor
    5.8% 6437/surfaceflinger: 4.3% user + 1.4% kernel
    2.1% 6462/RenderEngine: 0% user + 2.1% kernel
    1.4% 6455/binder:6437_2: 0% user + 1.4% kernel
    1.4% 6543/TimerDispatch: 0.7% user + 0.7% kernel
    0.7% 6544/app: 0% user + 0.7% kernel
    0.7% 6590/surfaceflinger: 0% user + 0.7% kernel
    0.7% 7958/binder:6437_5: 0.7% user + 0% kernel
  12% 9519/org.kustom.widget: 9.6% user + 2.4% kernel / faults: 1860 minor 3 major
    7.2% 10064/WM.task-1: 5.6% user + 1.6% kernel
    3.2% 10446/RxComputationTh: 3.2% user + 0% kernel
    0.8% 1346/binder:9519_F: 0.8% user + 0% kernel
    0.8% 9519/g.kustom.widget: 0.8% user + 0% kernel
    0.8% 10379/pool-21-thread-: 0.8% user + 0% kernel
  8.5% 2015/com.google.android.apps.walletnfcrel: 7.2% user + 1.3% kernel / faults: 1796 minor 228 major
    8.5% 2033/HeapTaskDaemon: 7.2% user + 1.3% kernel
  10% 17088/com.google.android.gms: 6.6% user + 4.1% kernel / faults: 1640 minor 3 major
    4.1% 1367/Measurement Wor: 1.6% user + 2.5% kernel
    4.1% 17088/gle.android.gms: 3.3% user + 0.8% kernel
    2.5% 23141/lowpool[11]: 1.6% user + 0.8% kernel
    0.8% 13483/binder:17088_F: 0.8% user + 0% kernel
  8.3% 3644/com.red.alert: 5.5% user + 2.7% kernel / faults: 2765 minor 76 major
    2% 3684/Jit thread pool: 2% user + 0% kernel
    0.6% 3722/Thread-2: 0% user + 0.6% kernel
   +0% 3965/MQTT Rec: 0ba2b: 0% user + 0% kernel
   +0% 3968/MQTT Snd: 0ba2b: 0% user + 0% kernel
   +0% 3969/MQTT Call: 0ba2: 0% user + 0% kernel
  32% 29621/com.f0x1d.logfox: 27% user + 5.4% kernel / faults: 418 minor
    8.1% 29621/om.f0x1d.logfox: 5.4% user + 2.7% kernel
    5.4% 29653/DefaultDispatch: 5.4% user + 0% kernel
    5.4% 29658/DefaultDispatch: 2.7% user + 2.7% kernel
    2.7% 29652/DefaultDispatch: 2.7% user + 0% kernel
    2.7% 29654/DefaultDispatch: 2.7% user + 0% kernel
    2.7% 29655/DefaultDispatch: 2.7% user + 0% kernel
    2.7% 29661/DefaultDispatch: 2.7% user + 0% kernel
    2.7% 30408/DefaultDispatch: 2.7% user + 0% kernel
  7.4% 6542/media.swcodec: 5.1% user + 2.2% kernel / faults: 89 minor
    3.7% 15743/oid.aac.decoder: 3.7% user + 0% kernel
    0.7% 7293/HwBinder:6542_3: 0% user + 0.7% kernel
  6.5% 10227/com.google.android.googlequicksearchbox:trusted_disable_art_image_:com.google.android.apps.gsa.hot: 4.9% user + 1.6% kernel / faults: 330 minor 1 major
    3.2% 10328/soda_process: 2.4% user + 0.8% kernel
    1.6% 10227/word_detector_0: 0.8% user + 0.8% kernel
    1.6% 10361/pool-2-thread-1: 0.8% user + 0.8% kernel
    1.6% 10368/soda-background: 0.8% user + 0.8% kernel
    0.8% 10329/Thread-2: 0.8% user + 0% kernel
  19% 22330/io.github.muntashirakon.AppManager: 2.4% user + 16% kernel / faults: 190 minor
    12% 22341/HeapTaskDaemon: 0% user + 12% kernel
    4.8% 22343/FinalizerDaemon: 2.4% user + 2.4% kernel
    2.4% 3362/PackageChangeRe: 0% user + 2.4% kernel
    2.4% 22330/akon.AppManager: 2.4% user + 0% kernel
  5% 6431/audioserver: 3.6% user + 1.4% kernel / faults: 68 minor 2 major
    3.6% 6835/AudioOut_15: 3.6% user + 0% kernel
    0.7% 17524/AudioIn_7E: 0% user + 0.7% kernel
  4.3% 6402/android.hardware.composer.hwc3-service.slsi: 0% user + 4.3% kernel / faults: 71 minor
    5% 6530/binder:6402_4: 0.7% user + 4.3% kernel
  3.5% 5731/logd: 2.1% user + 1.4% kernel / faults: 371 minor
    1.4% 5744/logd.klogd: 0.7% user + 0.7% kernel
    0.7% 5740/logd.writer: 0.7% user + 0% kernel
    0.7% 6322/logd.reader.per: 0% user + 0.7% kernel
    0.7% 29690/logd.reader.per: 0% user + 0.7% kernel
  3.8% 8023/com.google.android.gms.persistent: 2.2% user + 1.5% kernel / faults: 1114 minor 11 major
    2.2% 8023/.gms.persistent: 2.2% user + 0% kernel
  2.6% 2355/com.android.permissioncontroller: 1.3% user + 1.3% kernel / faults: 392 minor
    1.9% 3352/RoleControllerS: 0.6% user + 1.3% kernel
  2.8% 5732/lmkd: 0.7% user + 2.1% kernel
    2.8% 5732/lmkd: 0% user + 2.8% kernel
  2.1% 4023/ueventd: 2.1% user + 0% kernel / faults: 14 minor
  1.3% 62/ksoftirqd/7: 0% user + 1.3% kernel
  1.3% 1156/irq/318-max7770: 0% user + 1.3% kernel
  1.3% 1257/ion_system_heap: 0% user + 1.3% kernel
  1.3% 2375/android.process.acore: 0.6% user + 0.6% kernel / faults: 409 minor
    1.3% 2375/d.process.acore: 0.6% user + 0.6% kernel
  1.3% 2566/com.google.android.gm: 0.6% user + 0.6% kernel / faults: 292 minor
  1.3% 2764/com.tsng.hidemyapplist: 0.6% user + 0.6% kernel / faults: 533 minor 2 major
    1.3% 2764/g.hidemyapplist: 0.6% user + 0.6% kernel
  1.3% 3141/com.google.android.gms.unstable: 1.3% user + 0% kernel / faults: 616 minor
    1.3% 3141/id.gms.unstable: 1.3% user + 0% kernel
  1.4% 3680/kworker/3:0: 0% user + 1.4% kernel
  1.4% 6385/android.hardware.graphics.allocator@2.0-service: 0% user + 1.4% kernel / faults: 42 minor
    1.4% 11247/HwBinder:6385_3: 0% user + 1.4% kernel
  1.4% 6577/busybox: 0% user + 1.4% kernel / faults: 364 minor
  1.5% 7427/com.android.networkstack.process: 0% user + 1.5% kernel / faults: 828 minor
    1.5% 7427/rkstack.process: 0.7% user + 0.7% kernel
  1.6% 10542/org.futo.inputmethod.latin.playstore: 1.6% user + 0% kernel / faults: 640 minor 3 major
    1.6% 10542/latin.playstore: 1.6% user + 0% kernel
  1.6% 13485/com.digibites.accubattery: 0.8% user + 0.8% kernel / faults: 787 minor 4 major
    0.8% 13485/tes.accubattery: 0.8% user + 0% kernel
    0.8% 13570/ScreenStateWatc: 0.8% user + 0% kernel
  5.1% 25744/kworker/7:0: 0% user + 5.1% kernel
  0.6% 9/rcu_sched: 0% user + 0.6% kernel
  0.6% 11/migration/0: 0% user + 0.6% kernel
  0.6% 34/ksoftirqd/3: 0% user + 0.6% kernel
  0.6% 41/ksoftirqd/4: 0% user + 0.6% kernel
  0.6% 805/kworker/0:2H: 0% user + 0.6% kernel
  0.6% 829/kworker/u16:3: 0% user + 0.6% kernel
  0.6% 1411/com.whatsapp: 0.6% user + 0% kernel / faults: 534 minor
  0.6% 1862/irq/425-sec-nfc: 0% user + 0.6% kernel
  0.6% 2175/sugov:4: 0% user + 0.6% kernel
  0.6% 3197/decon0: 0% user + 0.6% kernel
  0.7% 6272/lspd: 0.7% user + 0% kernel / faults: 707 minor 2 major
    0.7% 7119/pool-1-thread-1: 0.7% user + 0% kernel
  0.7% 6389/android.hardware.sensors-service.samsung-multihal: 0% user + 0.7% kernel / faults: 3 minor
    0.7% 7015/HubConnection: 0% user + 0.7% kernel
  0.7% 6394/android.hardware.usb-service.samsung: 0% user + 0.7% kernel / faults: 6 minor
  0.7% 7297/com.drdisagree.iconify: 0.7% user + 0% kernel / faults: 556 minor
  0.7% 7551/com.android.phone: 0.7% user + 0% kernel / faults: 377 minor
    0.7% 7551/m.android.phone: 0.7% user + 0% kernel
  0.7% 7676/com.android.smspush: 0.7% user + 0% kernel / faults: 266 minor
  0.7% 8327/com.drdisagree.colorblendr: 0.7% user + 0% kernel / faults: 250 minor
    0.7% 8327/ree.colorblendr: 0.7% user + 0% kernel
    0.7% 8354/binder:8327_3: 0% user + 0.7% kernel
  0.7% 8676/sh: 0% user + 0.7% kernel / faults: 407 minor
  0.7% 9263/com.google.android.googlequicksearchbox:interactor: 0.7% user + 0% kernel / faults: 310 minor
    0.7% 9263/hbox:interactor: 0.7% user + 0% kernel
  0.7% 9301/org.lineageos.settings.doze: 0.7% user + 0% kernel / faults: 346 minor 2 major
  0.7% 9401/com.arlosoft.macrodroid: 0.7% user + 0% kernel / faults: 289 minor 2 major
    0.7% 9401/soft.macrodroid: 0.7% user + 0% kernel
  0.7% 9438/com.tombayley.volumepanel: 0.7% user + 0% kernel / faults: 747 minor 2 major
    0.7% 9155/RenderThread: 0% user + 0.7% kernel
    0.7% 9438/ley.volumepanel: 0.7% user + 0% kernel
  0.7% 9482/com.xiaomi.wearable:device: 0% user + 0.7% kernel / faults: 192 minor
    0.7% 9482/wearable:device: 0.7% user + 0% kernel
  0.8% 9827/com.android.vending: 0.8% user + 0% kernel / faults: 356 minor
    1.6% 9827/android.vending: 1.6% user + 0% kernel
    0.8% 10849/binder:9827_4: 0.8% user + 0% kernel
  0.8% 10675/com.wstxda.viper4android: 0.8% user + 0% kernel / faults: 322 minor 1 major
    0.8% 10675/a.viper4android: 0.8% user + 0% kernel
  0.8% 16773/flar2.exkernelmanager: 0.8% user + 0% kernel / faults: 529 minor 4 major
  2.4% 24198/com.google.android.googlequicksearchbox:search: 0% user + 2.4% kernel / faults: 107 minor
  2.5% 24266/com.iherb: 2.5% user + 0% kernel / faults: 149 minor 11 major
    2.5% 24266/com.iherb: 2.5% user + 0% kernel
  2.8% 30797/com.openai.chatgpt: 0% user + 2.8% kernel / faults: 41 minor
    2.8% 30809/FinalizerDaemon: 0% user + 2.8% kernel
  2.9% 31908/kworker/u18:2: 0% user + 2.9% kernel
 +0% 3995/sleep: 0% user + 0% kernel
80% TOTAL: 50% user + 28% kernel + 0.2% iowait + 1.2% softirq

**Comment by Mahmud0808** [comment]
I don't think this is because of iconify. Be sure first. Do what I said before. And keep other modules disabled while testing.

**Comment by DRA7** [comment]
I've tried that and still kept doing that only when i disabled iconify from lsposed it was okay. And no crashes at all so i tried to disable other modules in lsposed still the same so after a while of trying random stuff i ended up switching from lsposed_mod to the new lsposed fork by jing... And its working fine! I think this module works best with the new lsposed father than lsposed_mod. Ty for help!

**Comment by DRA7** [comment]
This one i think you should link it in the readme

https://github.com/xteamlyer/LSPosed-JingMatrix

**Comment by Mahmud0808** [comment]
You can join the telegram support group. There are like 3 different working forks saved in the group notes.
