### ISSUE TITLE
[FEATURE] Tap Clock in Status Bar to Open Clock App

### ISSUE THREAD

**Issue by FlazeIGuess** [Mahmud0808/Iconify#635]
### Describe the feature

The feature would allow users to tap on the clock in the status bar to directly open the Clock app. This would streamline access to alarms, timers, and other time-related functionalities within the app. The interaction would be seamless and intuitive for users.

### Why would it be useful to add?

This feature would save time and effort by allowing users to quickly access the Clock app with a single tap on the status bar, improving the user experience. It’s particularly useful for those who frequently set alarms or timers and want faster access to these tools.

### Example(s)

An example would be when a user wants to set a quick alarm or timer. Instead of navigating through the app drawer or using a widget, they could simply tap the clock in the status bar and go directly to the Clock app.

### Additional context

This feature is a small but significant quality-of-life improvement that aligns with the app’s goal of enhancing user convenience. It could be implemented as an optional setting, so users who prefer different behavior for the status bar clock can keep their current setup.

**Comment by DHD2280** [comment]
You can swipe down and tap on QS clock to open Alarm fast

**Comment by Mahmud0808** [comment]
You can do that from QS and you only need to swipe once to get QS. Not too much of a hassle.
