### ISSUE TITLE
Recording the screen causes the System UI to restart

### ISSUE THREAD

**Issue by alfa005pro** [Mahmud0808/Iconify#637]
### Describe the bug

When recording the screen, the quick settings swipe will become very stuck

### Steps to reproduce

I screen record, it stutters, I end, it crashes

### Expected behavior

Crash

### Device information

- Device: Mi9
- OS: Arrow os A12.1
- App version: 6.9
- Magisk/KernelSU: Kitsune Mask 27001

**Comment by DHD2280** [comment]
Are you sure that this weird behaviour is due to Iconify?
Send LSposed logs.

**Comment by alfa005pro** [comment]
This hasn't happened before, I'll check the logs next time

**Comment by Mahmud0808** [comment]
Open the issue when you got proper logs.
