### ISSUE TITLE
About RootProviderProxy

### ISSUE THREAD

**Issue by Typhonling** [Mahmud0808/Iconify#639]
### Describe the bug

It may not be a bug, but why is RootProviderProxy constantly running in the background?Even when no changes are applied?

### Steps to reproduce

It may not be a bug.

### Expected behavior

It should not be running constantly in the background, and if this is indeed necessary, please advise why.

### Device information

.

**Comment by Mahmud0808** [comment]
RootProviderProxy isn’t something that the Iconify app uses directly; it’s actually part of some LSPosed mods that go along with Iconify. These LSPosed mods, especially the ones that tweak the System UI, tend to run all the time in the background. So, it makes sense that RootProviderProxy is running too. That’s just how these mods work—they need to keep an eye on system events to function properly. If you are wondering where it's being used, it's in Depth Wallpaper mod and Lockscreen Widgets mod.

**Comment by Typhonling** [comment]
Yes, according to the changelog it was added in 6.9.0 and might have something to do with the newly added lock screen widget.
But I think it should only run when necessary, now it's running in the background even when there are no modifications to the program.

**Comment by DHD2280** [comment]
> Yes, according to the changelog it was added in 6.9.0 and might have something to do with the newly added lock screen widget. But I think it should only run when necessary, now it's running in the background even when there are no modifications to the program.

It simply doesn't do anything if no mods are enabled, so what makes you worry?

**Comment by Typhonling** [comment]
> > Yes, according to the changelog it was added in 6.9.0 and might have something to do with the newly added lock screen widget. But I think it should only run when necessary, now it's running in the background even when there are no modifications to the program.
> 
> It simply doesn't do anything if no mods are enabled, so what makes you worry?

If it's resident in memory even when it's not doing anything, it seems like that's not very logical?
I just don't like to see too much stuff resident in the background, not to mention it takes up 200mb+ of memory sometimes. Not really worried about anything else.
