### ISSUE TITLE
[BUG] glitch with 3 columns

### ISSUE THREAD

**Issue by nihal697** [Mahmud0808/Iconify#64]
### Describe the bug

if media player is visible in the notification panel and phone is on landscape mode + 3 columns are selected for qs, there is a glitch that you can see in the attached screenshot. Is there any way to bypass it?

### Steps to reproduce

Enable settings as per this sacreenshot
![Screenshot_20230206-225057_Trebuchet](https://user-images.githubusercontent.com/47318989/217041740-e04ca953-b28b-4cf1-a413-57ed7441f9c4.png)

### Expected behavior

Should look normal

### Screenshots

![Screenshot_20230206-225037_Spotify](https://user-images.githubusercontent.com/47318989/217041300-0687a076-af69-4ebf-9825-c3b6e6dae1cc.png)

### Device information

- Device: [e.g. Xiaomi Redmi Note 11]
- OS: [e.g. Lineageos Android version 13.0]
- App version: [e.g. v6.0.0 Dev #360]

**Comment by Mahmud0808** [comment]
You can use AOSPMods for changing row column. It probably has different settings for portrait and landscape mode.

**Comment by nihal697** [comment]
> You can use AOSPMods for changing row column. It probably has different settings for portrait and landscape mode.

yeah it does, although i prefer your app more. Will try it , thanks.

**Comment by MBQ-** [comment]
This needs closing 🙂
