### ISSUE TITLE
[BUG] SystemUI doesn't work anymore

### ISSUE THREAD

**Issue by FERFAIL-TXZ** [Mahmud0808/Iconify#640]
### Describe the bug

I was adjusting the QS tiles. I can't remember exactly, but I added more columns. The Iconify frooze, and me tapping in the screen and noticed that everything frooze too, and then the "SystemUI stopped working" message popped up, but I accidentaly tapped "Close app". Now, I only see the lock screen, and the phone screen turning on and off randomly. No clock, only the "swipe to unlock" message but touching anything doesn't work.

I can only hold the power button to power off, reboot and lock screen, but I can't even choose one of these options, it's like the screen is broken.

I can access to TWRP, but there are some stuff that I can't do:
- **Accessing /data/ folder**. It just doesn't show up anything, is empty. So I can't access the Magisk modules folder to at least delete the Iconify module.
- **Mounting data**. When tapping the checkbox of data, the phone just vibrates, plus it doesn't do anything, the checkmark doesn't appear.
- **Using ADB commands / SDK Platform tools.** Device isn't listed. Or at least accessing on ADB Sideload, but isn't listed when phone is booted on System either.
- **Reinstalling Iconify.** I don't know if this is the right way to do this, but I found a Github thread where it explains when sideloading the same magisk module, it will reinstall it...? I renamed the Iconify.apk to a zip file. Installing failed.

### Expected behavior

Expected the columns being increased. but SystemUI crash message appears.

Also expected when closing the SystemUI app would just reboot. It didn't (again, I pressed the "close app" button by accident)

### Device information

- Device: Samsung Galaxy S9 (starqltech)
- OS: CrDroid 8.11 (Android 12)
- App version: 6.9.0
- Magisk: I forgot. Around v27

**Comment by Mahmud0808** [comment]
Boot into safe mode. Google if you don't know how to.

**Comment by FERFAIL-TXZ** [comment]
> Boot into safe mode. Google if you don't know how to.

Hi, I realized how to boot into safe mode, but after that, I don't exactly know what to do next. I enabled the USB debugging and ADB still doesn't recognize my phone (I have Samsung drivers installed). Also wanted to look into the file explorer if I could see the data folder but in the preinstalled file manager I can't do much like going to root directory, and Safe mode doesn't let me open other non system apps.

What should I do next?

**Comment by Mahmud0808** [comment]
Just reboot your phone again and it will boot into normal mode. This time all modules will be disabled by default.

**Comment by FERFAIL-TXZ** [comment]
> Just reboot your phone again and it will boot into normal mode. This time all modules will be disabled by default.

Oh, I didn't know that. I rebooted normally and yeah, phone is back again. Thanks man, for one sec I thought I had to wipe data.
