### ISSUE TITLE
[BUG] Small hair like curved line appear below the QQS

### ISSUE THREAD

**Issue by two1212** [Mahmud0808/Iconify#642]
### Describe the bug

With Xposed > Transparency & Blur > Transparent QS Panel Enabled.
Small hair like curved line appear below the QQS "Flashlight" and "Mic access" buttons on the corner highlighted by two arrows in the screenshot.

It is more noticeable with Pitch Black (Amoled) Dark Theme enabled (with which screenshot was taken).

### Steps to reproduce

1. Go to Xposed > Transparency & Blur
2. Enable Transparent QS Panel 
3. Swipe down QQS Panel
4. Small hair like curved line appears

### Expected behavior

They shouldn't exist

### Screenshots

![Screenshot_20241009-233439](https://github.com/user-attachments/assets/910f0a5e-7ae3-47fb-9efe-a5983c49a46b)

### Device information

- Device: Google Pixel 6a
- OS: Stock ROM Android version 14.0 QPR3
- App version: v6.9.0
- Magisk Canary (27008)

### Additional context

That curved line seems to go into the bottom Settings and Power bar when switched from QQS to QS Panel,
Also, is that bottom bar supposed to be black or that's a bug too?

**Comment by Mahmud0808** [comment]
The top part is the QS scrim, and the bottom part is the Notification scrim. Google overlaps the corners by 1px to hide a tiny gap. Removing the 1px overlap shows the gap, which isn't a fix either. It's a Google bug, so there's nothing I can do.

**Comment by two1212** [comment]
I understand, it's not that noticeable either since it took me a few weeks to realize it was even there. 

Anyways, thanks for the explanation.

**Comment by ItsRogueRen** [comment]
When the UI roundness is set to 0, the black marks become almost impossible to see. Would there be a way to set the corners of only the notification shade to 0 to minimize the effect if it cannot be fixed by Iconify?

![Screenshot_20241208-011323.png](https://github.com/user-attachments/assets/9c16fc36-1a43-4010-8f7d-2ec8e4182fd6)

**Comment by Mahmud0808** [comment]
I can add an option to change that curve radius to 0 but then if you don't use 100% transparent QS panel, you will notice that background colors aren't curved where they match.

**Comment by ItsRogueRen** [comment]
> I can add an option to change that curve radius to 0 but then if you don't use 100% transparent QS panel, you will notice that background colors aren't curved where they match.

As long as there's a note about it acting unusual without full transparency I think that wouldn't be an issue. Either that or enabling the full transparency also sets that corner radius to 0
