### ISSUE TITLE
[BUG] Your title here

### ISSUE THREAD

**Issue by Mgfgfg** [Mahmud0808/Iconify#644]
### Describe the bug

Iconify bug report 13 10月 2024 11:10:49
version: 6.8.0 (20)
build.brand: meizu
build.device: meizu21Pro
build.display: Flyme 11.1.0.0A
build.fingerprint: meizu/meizu_21Pro_CN/meizu21Pro:14/UKQ1.230917.001/1721203997:user/release-keys
build.hardware: qcom
build.id: UKQ1.230917.001
build.manufacturer: meizu
build.model: MEIZU 21 Pro
build.product: meizu_21Pro_CN
build.type: user
version.codename: REL
version.release: 14
version.sdk_int: 34
iconify.version_name: 6.8.0
iconify.version_code: 20

error: Failed to build APK for QSST

zv - AAPT:
	/storage/emulated/0/.iconify/overlays/unsigned_unaligned/QSST-unsigned-unaligned.apk: error: No such file or directory.
	error: failed to create archive.

### Steps to reproduce

aaa

### Expected behavior

erro

### Screenshots

![S41013-11221800_com drdisagree iconify](https://github.com/user-attachments/assets/d7273683-910f-405b-bd30-ffe4b53f87e7)

### Device information

- Device: [e.g. meizu 21 pro]
- OS: [e.g. stock ROM Android version 13.0 QPR3]
- App version: [e.g. v6.8]
- Magisk/KernelSU: [e.g. Magisk Delta 27.0]

**Comment by Mahmud0808** [comment]
ROM not supported https://github.com/Mahmud0808/Iconify?tab=readme-ov-file#-faq

**Comment by tomaszk8266** [comment]
Wait, what? A meizu with unlocked BL and rooted? How did you do that?
