### ISSUE TITLE
[BUG] OnePlus Qs header Bluetooth setting cause ui crash

### ISSUE THREAD

**Issue by Phaze-l** [Mahmud0808/Iconify#645]
### Describe the bug

When clicking Bluetooth icon UI crashes

### Steps to reproduce

1. Open iconify
2. Activate OnePlus Qs header
3. Open Qs panel
4. Click on Bluetooth 
5. See UI crash
[LSPosed_2024-10-16T20_19_49.900551.zip](https://github.com/user-attachments/files/17400400/LSPosed_2024-10-16T20_19_49.900551.zip)

### Expected behavior

Bluetooth activating/deactivating

### Device information

- Device: Miatoll Curtana (Redmi note 9s)
- OS: cAOSP android 15
- App version: 6.9
- KernelSU: 1.0.1 (11872)

**Comment by DHD2280** [comment]
Hello.
Please point us to the source of your ROM.

**Comment by Phaze-l** [comment]
https://t.me/cosmic_oox

**Comment by DHD2280** [comment]
> https://t.me/cosmic_oox

we  need github source code.

**Comment by tomaszk8266** [comment]
The bug is also present on lineage 21 (fajita)

**Comment by Mahmud0808** [comment]
> The bug is also present on lineage 21 (fajita)

Send SystemUI.apk from /system/system_ext/priv-app/SystemUI

**Comment by Mahmud0808** [comment]
Fixed in https://github.com/Mahmud0808/Iconify/commit/1c36cae059d4ff76c645e2a38ad48cd497a8428f
