### ISSUE TITLE
[BUG] Enabling "Status Icons Chip" option in Xposed section causes SystemUI bootloop in LineageOS 20

### ISSUE THREAD

**Issue by w0nd3r365** [Mahmud0808/Iconify#647]
### Describe the bug

Enabling `Iconify` > `Xposed` > `Background Chip` > `Status Icons Chip` causes SystemUI to bootloop, thus Iconify Xposed config does not load. The other configs load properly though. After disabling the `Status Icons Chip`, SystemUI does not bootloop and Iconify Xposed configs load just fine.

### Steps to reproduce

Let me explain the timestamps In the LSPosed verbose log attached. I reboot my phone and all Iconify configs loaded properly. LSPosed logs of starting up all modules end at `2024-10-19T00:01:32.047`. So I enabled the `Status Icons Chip` option in Iconify and then restart SystemUI at `2024-10-19T00:07:08.704`. SystemUI bootloops and Iconify notices this and doesn't load the Xposed configs. Then I proceeded to disable `Status Icons Chip` option and restarted SystemUI at `2024-10-19T00:08:06.349`. SystemUI restarts without any issue.

In the attached files there's a zip file containing my Iconify configs that work well and that bootloops SystemUI. The only difference between the configs is the activation state of `Status Icons Chip`.

### Expected behavior

SystemUI should not bootloop after enabling `Status Icons Chip`.

### Device information

- Device: `Samsung Galaxy Tab A7 SM-T500`
- OS: `Lineage OS 20 (Android 13)`
- App version: `v6.9.0`
- Magisk (stable): `v27.0 (27000)`
- LSPosed: `v1.9.2 (7024)`
- Zygisk enabled

### Additional context

[LSPosed_Verbose_Log--Status_Icons_Chip_Bug.log](https://github.com/user-attachments/files/17441148/LSPosed_Verbose_Log--Status_Icons_Chip_Bug.log)
[2-Iconify-Configs_good-and-errored.zip](https://github.com/user-attachments/files/17441164/2-Iconify-Configs_good-and-errored.zip)

**Comment by Mahmud0808** [comment]
Status Icons Chip hasn't been maintained for some time and has been removed from android 14+ as it has became too much buggy and a mess to maintain. So I suggest you not to enable it.

**Comment by w0nd3r365** [comment]
Okay, I understand. Thanks for Iconify.
