### ISSUE TITLE
[BUG] QS Tile label size get applied to other UI components with dark theme

### ISSUE THREAD

**Issue by ssscharnhorst** [Mahmud0808/Iconify#65]
### Describe the bug

When a custom qs tile label size is set, battery percentage, network traffic indicator, footer text, and active apps text on QS is also affected.

This doesn't happen with the Light system theme on.

### Steps to reproduce

1. Go to Iconify > QS Panel Tiles > Icon and label
2. Set any custom text size (11sp when I encountered this)
3. Just open qs (With dark theme)

### Expected behavior

The QS Tile label size must only apply to QS tile label with dark theme on, as in the case with the Light theme.

### Screenshots

![Screenshot_20230208-183938_Amr's_Launcher](https://user-images.githubusercontent.com/123294684/217508501-17bc2d26-01d0-4967-bb6e-0bc6c52a041b.png)
With Dark theme

![Screenshot_20230208-184000_Via](https://user-images.githubusercontent.com/123294684/217508620-33479310-460e-489a-98b6-1fe840211ed4.png)
With Light theme

### Device information

- Device: [Google Pixel 5]
- OS: [EvolutionX ROM Android 13 v.7.5]
- App version: [v.6.0.0 Debug #366]

**Comment by Mahmud0808** [comment]
This isn't a bug actually. Android linked all of the QS texts to one size. So changing one size will affect the others. Though this can be fixed by using xposed, I think most people won't prefer xposed one over the current implementation.

**Comment by ssscharnhorst** [comment]
Ohh. I didn't know that. Thanks for the explanations

And I'm still wondering, why does it works perfectly on the light theme, though?

Are they implemented differently or something?

**Comment by Mahmud0808** [comment]
Afaik it should happen in both light and dark theme.

**Comment by ssscharnhorst** [comment]
See the screenshots above.
It doesn't occur in the light theme (The bottom one)

Again, i don't know if this is an intended behaviour or it's just happening only for me.

**Comment by Mahmud0808** [comment]
Well, now I tested and it seems like mine only changes QS Label size and doesn't affect anything else. But on previous rom I tested, it was changing whole QS. My guess is some roms may have unlinked them.

**Comment by ssscharnhorst** [comment]
Ah i see then.

So what can be done about it if so?

or should i just close this issue?

**Comment by Mahmud0808** [comment]
Sadly I can't think of a solution right now except xposed method.

**Comment by ssscharnhorst** [comment]
Ohh...

You said you prefer the current right?

So you don't plan on changing the implementation anytime soon then?

**Comment by Mahmud0808** [comment]
Yes you are right

**Comment by ssscharnhorst** [comment]
Ok then. Thank you for the explanations and responses

I will close this issue as not planned.

edit: completed may not fit for now, so not planned.
