### ISSUE TITLE
[BUG] No Settings Window

### ISSUE THREAD

**Issue by SPACED0UBT** [Mahmud0808/Iconify#650]
### Describe the bug

The settings window is blank. I can't access any items in it. I can use the rearch tab for know nitems but they cannot be seleted.

### Steps to reproduce

1. Go to 'Iconify'
2. Click on 'Settings'
3. Scroll down to 'nothingness'

### Expected behavior

There should be a list of items that woulb be under Settings, i.e. restart SystemUI after reboot

### Screenshots

![Screenshot_20241020-183350_Iconify](https://github.com/user-attachments/assets/28dbfd30-1b5c-4723-b510-89e192bd3254)

### Device information

- Device: [Sony Xperia 5 III]
- OS: [LineageOS 21]
- App version: [e.g. v6.9.0]
- Magisk/KernelSU: [e.g. Magisk 27]

**Comment by Mahmud0808** [comment]
Clear data of iconify app. It was mentioned in changelog that you must clean install v6.9.0 as it has too many conflicting changes.
