### ISSUE TITLE
Statusbar Clock Chip resets size after restart of UI

### ISSUE THREAD

**Issue by FlazeIGuess** [Mahmud0808/Iconify#652]
### Describe the bug

When the System UI is restarted or the device is rebooted, the size of the Background Chip Clock resets to its default size, instead of retaining the customized size settings.``

### Steps to reproduce

Steps to Reproduce:

1. Customize the size of the Background Clock Chip.

2. Restart the System UI (e.g., via Developer Options or the in-app restart) or reboot the device.

3. Check the size of the Background Clock Chip after the system restarts.

### Expected behavior

The Background Chip Clock should retain the customized size after a System UI restart or device reboot.

### Screenshots

![Screenshot_20241023-134128](https://github.com/user-attachments/assets/e6597538-292a-490d-856a-11ee9f951860)
![Screenshot_20241023-134113](https://github.com/user-attachments/assets/41773198-62d5-4c75-8f1d-6ed3a9798f35)

### Device information

- Device: [e.g. Google Pixel 8 Pro]
- OS: [e.g. stock ROM Android version 14]
- App version: [e.g. v6.9.0]
- Magisk/KernelSU: [Magisk 070719db-alpha (28001)]

**Comment by frijheid** [comment]
I am also experiencing this bug on Xperia 5 IV. The user must reactivate the background chip toggle in order the shape returns to normal. This bug will happen again and user has to manually fix it and it's tedious, I hope the bug can be fixed, thanks devs.
