### ISSUE TITLE
[BUG] Crash in LSPosed 1.9.2 (7233) Official Latest Internal Testing

### ISSUE THREAD

**Issue by likkai** [Mahmud0808/Iconify#661]
### Describe the bug

Iconify will crash during initialisation (Step 1/6: Creating module shell) when LSPosed 1.9.2 (7233) Official Internal Testing is installed. The changes previously made is still there, but the app just crash. I am unable to provide the lsposed zip file because there is a restriction and it is linked to my github unfortunately. The message to apply for lsposed internal team is here https://t.me/LSPosedDiscussion/1736052. 

### Steps to reproduce

1. Open Iconify
2. Click skip
3. Click let's go
4. Crashed

### Expected behavior

App starts initialising

### Device information

- Device: Xiaomi 11 Lite 5G NE
- OS: PixelOS A15 October security update AP2A
- App version: 6.9.0
- Magisk/KernelSU: KernelSU 0.9.5 (11872)

### Additional context

`iconify_logs.txt` is obtained by executing `logcat > .` in termux
[LSPosed_2024-10-27T18_47_24.200715.zip](https://github.com/user-attachments/files/17533573/LSPosed_2024-10-27T18_47_24.200715.zip)
[iconify_logs.txt](https://github.com/user-attachments/files/17533574/iconify_logs.txt)

**Comment by Mahmud0808** [comment]
If you are updating from old version, you must clear data of iconify as v6.9.0 has too many conflicting changes.

**Comment by likkai** [comment]
That fixes the issue. Thank you very much
