### ISSUE TITLE
Resetting specific options 

### ISSUE THREAD

**Issue by Inderix** [Mahmud0808/Iconify#674]
### Describe the feature

An option in the drop-down menu when looking at a page of settings to set everything in that specific page of options back to their defaults, automatically restarting the SystemUI or offering the user the option to reboot

### Why would it be useful to add?

Iconify has a lot of options, and for me at least I'm very forgetful of what the default is (especially for certain padding settings in the QS) leading me to reset everything when something comes about and I can't be assed to fix it "correctly".
The ability to reset specific options back to the default would make troubleshooting much easier as well (ex. A user can reset one set of options to figure out if anything there fixes any breakage they're experiencing)

### Example(s)

![Untitled70_20241114011817](https://github.com/user-attachments/assets/93e9557c-2cab-44df-9b23-166e1ac9c2f7)

### Additional context

I just had to reset all my iconify settings to troubleshoot a padding issue and I'm a little salty because everything else was perfect 🫠

**Comment by Mahmud0808** [comment]
These options lack a reset button because each device/ROM has its own default value for those specific things. Instead, I added a switch/button to disable the option, with a placeholder value showing in app which doesn't reflect the original (default) value.
