### ISSUE TITLE
[BUG] Not working with Kernelsu root solution 

### ISSUE THREAD

**Issue by lsander** [Mahmud0808/Iconify#68]
### Describe the bug

It basically doesn't work as it say root you system with magisk. I got kernelsu

### Expected behavior

Should work normally

### Device information

Poco X3 pro
Paranoid 13
Kernelsu

**Comment by Mahmud0808** [comment]
Iconify is partially based on magisk module, but kernelsu doesn't have module support yet (if I am not wrong). If kernelsu gets more popular than magisk, then I will look for an alternative way.

**Comment by lsander** [comment]
Kernelsu actually has magisk modules working now. Not all of them but most are working including zygisk and lsposed(zygisk).
Anyway no problem just taught it use only root. If it need some magisk stuff also then no problem, didn't know.

**Comment by Mahmud0808** [comment]
KernelSU support has been added. Thanks to #102
