### ISSUE TITLE
[BUG] Blur flickers with transparent qs or notification panels

### ISSUE THREAD

**Issue by Kicshikxo** [Mahmud0808/Iconify#692]
### Describe the bug

With transparent QS or notification panels, the blur flickers after opening the QS panel. It appears only if there are no notifications, if there are notifications, everything looks fine. This only appears when the QS panel is opened, if you only open the notification panel, there is no flicker.

### Steps to reproduce

1. Open notification panel
2. Open QS panel
3. Close QS panel
4. After you start closing the notification panel, the blur will disappear for a few frames

### Expected behavior

The blur should not disappear when you close the notification panel

### Screenshots

Here is a slow motion recording of the blur disappearing. I had to slow it down so much, because at higher video speeds the editors miss the blur disappearance frames. The blur disappears at 25 seconds.

https://github.com/user-attachments/assets/92941451-1c3c-407b-8ee5-56e9b74ee321

### Device information

- Device: Google Pixel 7a
- OS: Android 15 AP3A.241105.007
- App version: 6.9.0
- Magisk/KernelSU: Magisk 27.0

### Additional context

I don't know if this is an Iconify issue or if it's an android issue, but it catches my eye often enough when there are no notifications.
I think this is probably an android problem, as [Notification-Shade-Transparency](https://github.com/AsyJAIZ/Notification-Shade-Transparency) gives exactly the same result, but it would be nice if there was a solution to this problem.

**Comment by Mahmud0808** [comment]
Yes, it's not an issue related to Iconify module. Iconify just enables the blur from system props and removes the colored shade from QS. It doesn't control when or where the blur should appear.
