### ISSUE TITLE
[BUG] A15 Issue with radiuses

### ISSUE THREAD

**Issue by kekkodance** [Mahmud0808/Iconify#695]
### Describe the bug

I just updated to CalyxOS 6.1.0, Android 15. The outline doesn't look right anymore.

### Steps to reproduce

enable outline on QS
set QS radius to something other than stock

### Expected behavior

a full outline

### Screenshots

![Screenshot_20241208-151301](https://github.com/user-attachments/assets/95a7f808-f1a2-4414-9ada-4d4ef3c7da93)

### Device information

- Device: [Pixel 8 Pro]
- OS: [CalyxOS 6.1.0]
- App version: [6.9.0]
- Magisk/KernelSU: [Kitsune Mask Canary]

**Comment by Mahmud0808** [comment]
It's always recommended to uninstall iconify before doing a major update of android version. Reinstalling iconify should fix this issue.
