### ISSUE TITLE
[BUG] A15 notification styling

### ISSUE THREAD

**Issue by cozykitten** [Mahmud0808/Iconify#697]
### Describe the bug

since updating to A15 Notification styling is broken again :c
see screenshot below

### Steps to reproduce

Apply Notification theming from Pixel menu (or non pixel one for that matter)

### Expected behavior

should look like before (matching style of QS panels, "lighty" is applied)

### Screenshots

![Screenshot_20241209-081928](https://github.com/user-attachments/assets/748fe4cb-8cc8-46c3-a060-eb964cdd5d42)

### Device information

- Device: Pixel 6a
- OS: A15, OTA Dec
- App version: latest (6.9.0)
- Magisk/KernelSU: Magisk 28100

**Comment by Mahmud0808** [comment]
Use debug version. Reopen the issue if not fixed.

**Comment by cozykitten** [comment]
It won't let me install the latest action build xx93
Says app failed to install.
I'll just wait for the next release.
Default notification look won't kill me.
