### ISSUE TITLE
[BUG] Music player placed up custom clock 

### ISSUE THREAD

**Issue by Polep222** [Mahmud0808/Iconify#699]
### Describe the bug

So the music player is up the clock Wich is ugly now idk if there a fix or no 

### Steps to reproduce

1:Open any music app 
2:Lock ur device
And now look in ur lockscreen
Note:it only happen when using custom clock with Xposed 

### Expected behavior

The music player little bit down 

### Screenshots

![Screenshot_20241209-211510_Chrome](https://github.com/user-attachments/assets/7c78a60e-f342-4d7a-83ec-620d4e0bfbcd)

### Device information

- Device: [e.g. Google Pixel 6]
- OS:Evo x (android 15]
- App version: 6.9.0
- Magisk/KernelSU: Magisk 28.1

**Comment by DHD2280** [comment]
Increase bottom margin.
