### ISSUE TITLE
Custom Name

### ISSUE THREAD

**Issue by RipperHybrid** [Mahmud0808/Iconify#70]
### Describe the feature

Sir Can You Try To Add A Function That We Can Write Name In Header & Also give margin to move according to our liking 

Just think about it once it not like it's very important just a idead 😅

### Why would it be useful to add?

Making it more cuatomizable

### Example(s)

Like we can type name with the custom header clock

**Comment by Mahmud0808** [comment]
I can but not anytime soon.

**Comment by RipperHybrid** [comment]
> I can but not anytime soon.

Okay sir thnx
