### ISSUE TITLE
[BUG] A15 - Iconify & PixelXpert - Pixel 9 (no pro)

### ISSUE THREAD

**Issue by YanX94** [Mahmud0808/Iconify#700]
### Describe the bug

Hi to all the Iconify devs !

I come to the official Github to get some help. I must tell you, I am completely lost. Also, sorry for my bad English as this is not my native language and I am not using Google Translate.

Ok so let me get you some informations because the more you have the better:

Google Pixel 9 (not pro, regular version)
Android version: 15 (AP4A.241205.13) - Rooted, Magisk installed.

Here are the Magisk modules installed:
![Screenshot_20241209-185158](https://github.com/user-attachments/assets/b61d2a55-8358-46b8-8b06-3e00a3883ad4)

- Iconify ( 👍🏼 )
- IOS Emojies font (To get IOS emojies, I just added this not related)
- Pixel Xpert
- Play integrity Fix (To be able to pay with my phone)
- Zygisk - LSPosed

Also, in the Magisk settings, I have Zigisk enabled:
![2](https://github.com/user-attachments/assets/7d8092eb-4b29-451f-953d-e79142f10845)

==============================================================================

The issue I have is that, Iconify always enter in conflict with Pixel Xpert. I did achieved a couple of times to make it both work at the same time, but as soon as I reboot, I need to go turn off Pixel Xpert in Magisk, Reboot, Re-activate the module in Magisk, it asks for permissions, I go in Pixel Xpert and play with a toggle and boom, it works again, but it's a hell of a process that I've found by myself.

Like Martin Lutherking, I have a dream, and it is to be able to use both modules at the same time with no conflicts.

Has anyone got a solution to help me with this ? I would REALLY appreciate. 

Thank you in advance !!! :)

Yan

### Steps to reproduce

Everything is explained in the main post

### Expected behavior

Everything is explained in the main post

### Device information

Everything is explained in the main post

**Comment by Mahmud0808** [comment]
Iconify currently isn't compatible with android 15. I am still using android 14 so it might take a while.

**Comment by AdRoz78** [comment]
> Iconify currently isn't compatible with android 15.

Odd. I'm on Android 15 and while stuff was screwed up graphically all it took is a quick re-flash of iconify and everything worked fine.

As for the main post, no idea. I have android 15 too (even the exact same model and version!), and iconify and pixelxpert work in tandem nicely, only some animation lag in a place or 2.

**Comment by YanX94** [comment]
> > Iconify currently isn't compatible with android 15.
> 
> Odd. I'm on Android 15 and while stuff was screwed up graphically all it took is a quick re-flash of iconify and everything worked fine.
> 
> As for the main post, no idea. I have android 15 too (even the exact same model and version!), and iconify and pixelxpert work in tandem nicely, only some animation lag in a place or 2.

How did you do the quick re-flash of iconify ?

**Comment by AdRoz78** [comment]
> > > Iconify currently isn't compatible with android 15.
> > 
> > 
> > Odd. I'm on Android 15 and while stuff was screwed up graphically all it took is a quick re-flash of iconify and everything worked fine.
> > As for the main post, no idea. I have android 15 too (even the exact same model and version!), and iconify and pixelxpert work in tandem nicely, only some animation lag in a place or 2.
> 
> How did you do the quick re-flash of iconify ?

Wiped appdata of iconify, and let it install everything again. Then set up everything from scratch instead of restoring a backup. So far everything works perfecto
