### ISSUE TITLE
[BUG] Cut statusbar

### ISSUE THREAD

**Issue by kekkodance** [Mahmud0808/Iconify#701]
### Describe the bug

Randomly, when unlocking the phone, the statusbar will appear like the image

### Expected behavior

A normal looking statusbar

### Screenshots

![Screenshot_20241210-134821](https://github.com/user-attachments/assets/8dbea6d0-2d3d-401f-ba88-97efa9bf00eb)

### Device information

- Device: Pixel 8 Pro
- OS: CalyxOS 6.1.0, Android 15
- App version: 6.9.0
- Magisk/KernelSU: latest Magisk, JingMatrix LSPosed

### Additional context

I uploaded my config here: `https://files.catbox.moe/s3yh85.iconify (4)`

**Comment by DHD2280** [comment]
Check with debug version, available from GitHub/actions.
Remove standard iconify and install the debug one.
Clear lsposed logs.
Reboot & check again.
If you are facing the same issue, send fresh logs.

**Comment by kekkodance** [comment]
still happens.
![Screenshot_20241211-140527](https://github.com/user-attachments/assets/0baa6983-9836-418e-a9af-a4b6dad3deb0)
[LSPosed_2024-12-11T14_06_03.792209.zip](https://github.com/user-attachments/files/18095890/LSPosed_2024-12-11T14_06_03.792209.zip)
[LSPosed_2024-12-11T14_06_12.853619.zip](https://github.com/user-attachments/files/18095894/LSPosed_2024-12-11T14_06_12.853619.zip)

**Comment by Mahmud0808** [comment]
If you have notch bar killer enabled, disable it.

**Comment by kekkodance** [comment]
![Screenshot_20241211-171303](https://github.com/user-attachments/assets/4d511da9-d54b-49c3-a9d7-d600392a8b82)

**Comment by Mahmud0808** [comment]
Disable tablet landscape, restart systemui and check again

**Comment by kekkodance** [comment]
that seems to be the issue, i liked it tho

**Comment by Mahmud0808** [comment]
Unfortunately that feature also has notch bar killer integrated. And some device has issue with ignoring notch area.
