### ISSUE TITLE
[BUG] SystemUI crash after uninstall

### ISSUE THREAD

**Issue by farfromrefug** [Mahmud0808/Iconify#703]
### Describe the bug

I know iconify is fully systemless yes something seems to have changed:
So i had iconify installed with the lsposed module. Everything was working fine. Then i tried to add the volume panel magisk module created by iconify then my phone was not booted anymore. So i started in safe mode and disabled the magisk module.
Weird things started to happen then once i enabled iconify again. A lot of settings were lost so i had to configure it all again.
And from that moment on when started audio video which was showing a media playback notification then the SystemUI crashed  without restarting.
looking at the logcat i saw that it was this error which crashed SystemUI:
```
12-20 20:09:33.837  2557  2775 E AndroidRuntime: FATAL EXCEPTION: SysUiBg
12-20 20:09:33.837  2557  2775 E AndroidRuntime: Process: com.android.systemui, PID: 2557
12-20 20:09:33.837  2557  2775 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioDeviceAttributes.getInternalType()' on a null object reference
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.media.IAudioService$Stub$Proxy.getMutingExpectedDevice(IAudioService.java:7943)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.media.AudioManager.getMutingExpectedDevice(AudioManager.java:9191)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.settingslib.media.LocalMediaManager$MediaDeviceCallback.getMutingExpectedDevice(go/retraceme 37046a542765844aed0b78ca9b8d9d35c2ecafcc2dd631a505db30a841d6ec56:9)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.settingslib.media.MediaManager.dispatchDeviceListAdded(go/retraceme 37046a542765844aed0b78ca9b8d9d35c2ecafcc2dd631a505db30a841d6ec56:76)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.settingslib.media.InfoMediaManager.refreshDevices(go/retraceme 37046a542765844aed0b78ca9b8d9d35c2ecafcc2dd631a505db30a841d6ec56:25)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.settingslib.media.LocalMediaManager.startScan(go/retraceme 37046a542765844aed0b78ca9b8d9d35c2ecafcc2dd631a505db30a841d6ec56:92)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.systemui.media.controls.pipeline.MediaDeviceManager$Entry$stop$1.run(go/retraceme 37046a542765844aed0b78ca9b8d9d35c2ecafcc2dd631a505db30a841d6ec56:84)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.server.audio.AudioService.anonymizeAudioDeviceAttributesUnchecked(AudioService.java:10404)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.server.audio.AudioService.anonymizeAudioDeviceAttributes(AudioService.java:10417)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at com.android.server.audio.AudioService.getMutingExpectedDevice(AudioService.java:10509)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.media.IAudioService$Stub.onTransact(IAudioService.java:4092)
12-20 20:09:33.837  2557  2775 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1363)
```
Seeing the error it seems like `AudioDeviceAttributes` is null. 
The weird thing is that i can play audio as long as they dont try to show a notification.
I should say that i removed iconify, even uninstalled lsposed. I also flashed LOS system again and the error persists.

I know it should not be Iconify's fault as it is systemless but yet something happened and it is due to what was changed with Iconify.
I am wondering if it could be related to secure setting. Is Iconify setting/changing secure settings which would persist even after it is uninstalled?

### Steps to reproduce

1. installed Iconify
2. change settings
3. enable lsposed module
4. uninstall
5. start audio 
6. crash

Obviously this wont happen all the time...

### Expected behavior

no crash

### Device information

- Device: Hisense A9
- OS: LOS 14
- App version: 6.9.0
- Magisk/KernelSU: 28.1

**Comment by Mahmud0808** [comment]
Yes iconify is systemless, but the volume companion module hasn't been maintained for a long time. And I don't think that module is fully systemless. I suggest you to clean flash your rom.

And no, iconify doesn't change any secure settings.

**Comment by farfromrefug** [comment]
@Mahmud0808 i did erase my data without a full wipe and the issue is gone. 
Must be the volume module yes. Maybe worth adding a warning about it ? Dot think it works on android 14 and even think it puts the system in a bad state
