### ISSUE TITLE
[FEATURE] Add new wifi icon

### ISSUE THREAD

**Issue by Car0lina5** [Mahmud0808/Iconify#704]
### Describe the feature

It's a koala wifi icon, few ROMS have it (like Evolution), and since iconify already has a large part of the wifi icons I would like to suggest the cutest of all.

### Why would it be useful to add?

Because it would make mine and many other people's phones cuter.

### Example(s)

![20 12 2024  -  18 40  -  ](https://github.com/user-attachments/assets/05ee0f10-a531-432e-87cd-076bfed536da)

**Comment by Mahmud0808** [comment]
These are created by me but won't be added due to copyright/permission issue.
