### ISSUE TITLE
[FEATURE] could you please add the option to hide the status bar on the lock screen

### ISSUE THREAD

**Issue by Noahcyrus56** [Mahmud0808/Iconify#73]
### Describe the feature

hide lock screen icons

### Why would it be useful to add?

It would look cleaner

### Example(s)

![Uploading Screenshot_20230214-155045_Iconify_(Debug).png…]()

**Comment by Mahmud0808** [comment]
It's not possible to completely hide the lockscreen statusbar on A12+ roms. A tiny bit (like 1px) will still be shown at the top. So I don't know if people will appreciate that.

**Comment by Mokura** [comment]
Is it possible to hide the statusbar in other scenarios, like general use?  Xposed Edge does it somehow (on A12 and A13), but having an open source option would be nice to have.

**Comment by Mahmud0808** [comment]
> Is it possible to hide the statusbar in other scenarios, like general use? Xposed Edge does it somehow (on A12 and A13), but having an open source option would be nice to have.

Oh I was talking about non xposed method.
