### ISSUE TITLE
[Feature] Hide Carrier alternative

### ISSUE THREAD

**Issue by Libra420T** [Mahmud0808/Iconify#74]
### Describe the feature

Hide Carrier group is already included in the apk.
Unfortunately some custom roms have had UI changes that now make the current toggle irrelevant.... Carrier.xml needs to be 0dp as well, to match 0dp with carrier_group.xml.

### Why would it be useful to add?

This is useful because it will allow users to official disable(hide) Carrier via QS panel

### Example(s)

![Screenshot_20230214-143439_MT Manager](https://user-images.githubusercontent.com/71480065/218879221-01ec47dc-7b9c-4812-b6b8-3e30fe155bf6.png)

 Shows where edits are made.
Height & width ="0dp"
Focusable = "false"

### Additional context

Thank you and I appreciate all you have done for us 💕.

**Comment by Mahmud0808** [comment]
Tried this but unfortunately didn't success. I will try some other method.

**Comment by Libra420T** [comment]
Yea. I noticed a lot of xml edits are just not taking effect on roms with February patch. It's truly frustrating 😅
Either way sir, I appreciate all you do 👍

**Comment by Mahmud0808** [comment]
Added alternative method in debug build. Closing this issue.
