### ISSUE TITLE
[FEATURE] Can you please add force white background on qs pannel. on my nothing phone and pixel phone doesn't support white theme even if i turn off dark theme

### ISSUE THREAD

**Issue by allen-evan143** [Mahmud0808/Iconify#75]
### Describe the feature

Can you please add force white background on qs pannel. on my nothing phone and pixel phone doesn't support white theme even if i turn off dark theme 

### Why would it be useful to add?

There is no white Qs pannel on plenty of device. it would very much helpful.

### Example(s)

![Screenshot_20230215-090134](https://user-images.githubusercontent.com/125423779/218916263-931ffffa-96d0-41b7-8699-1181039b7d13.png)

**Comment by Mahmud0808** [comment]
You can try AOSPMods if you want. It has the feature you are asking for.
