### ISSUE TITLE
[FEATURE] Square tiles in QS and QQS

### ISSUE THREAD

**Issue by bzz11g** [Mahmud0808/Iconify#78]
### Describe the feature

Hello Dear Friend!
I hope that you will consider ability to adding fully square tiles to toggle quick settings in collapsed and expanded position, now they are rectangular in QQS

### Why would it be useful to add?

From an aesthetic point of view, square tiles look better in both cases, than when they are rectangular when collapsed and square when unfolded.

### Example(s)

Now on a regular basis I use [AOSPmods](https://github.com/siavash79/AOSPMods) and there tiles square, but I would really like to replace this mod with Iconify because it is more stable, has fewer bugs and allows you to fine-tune the appearance of quick settings
![001](https://user-images.githubusercontent.com/1549909/219602807-668ad5a1-5a31-4ac6-be32-fc33e13d3fff.png)

### Additional context

if possible - add a squareness switch, for those who prefer more compact (rectangular) tiles

Thank you!

**Comment by Mahmud0808** [comment]
Are you talking about xposed feature?

**Comment by bzz11g** [comment]
Yes, I use Xposed feature as well

**Comment by Mahmud0808** [comment]
> Yes, I use Xposed feature as well

ok I will check it out.

**Comment by bzz11g** [comment]
Hi, if it helps, the overlay with square tiles in AOSPmods here https://github.com/siavash79/AOSPMods/tree/canary/MagiskModAddon/system/product/overlay/AOSPMods_QStileNO34D

**Comment by bzz11g** [comment]
Thank you 👍
