### ISSUE TITLE
[FEATURE] Movable header clock in expanded QS

### ISSUE THREAD

**Issue by bzz11g** [Mahmud0808/Iconify#79]
### Describe the feature

Hello Dear Friend!
I hope that you will consider ability to add option move the custom clock together with other elements of QS (battery, cellular, etc.)

### Why would it be useful to add?

For aesthetic reasons, and it will also be useful for those who have a cutout for the camera in the screen and part of the text falls on the place of the cutout

### Example(s)

![002](https://user-images.githubusercontent.com/1549909/219614223-d7669686-43da-4cd6-b961-d92b19900962.png)

### Additional context

if possible - add a movement switch, for those who prefer to keep their watches in the same place at all times

Thank you!

**Comment by bzz11g** [comment]
And I also wanted to, but forgot to mention: bind the color of the numbers of hours and the vertical divider to the colors of the MaterialYou theme

**Comment by Mahmud0808** [comment]
I already did this movable header clock for one of the clocks and it was buggy in a few rom while using text scaling. That's why I had to fall back to the fixed position method. You can alternatively make the status icons' position fixed (if that option works for you).

> And I also wanted to, but forgot to mention: bind the color of the numbers of hours and the vertical divider to the colors of the MaterialYou theme

Enable Monet accent or Monet gradient from Iconify Color Engine.

**Comment by bzz11g** [comment]
ok, thank you

**Comment by bzz11g** [comment]
>You can alternatively make the status icons' position fixed (if that option works for you).

This function didn't work on Pixel 6 stock firmware with February update, icons just disappear from QS and QQS

**Comment by Mahmud0808** [comment]
Try latest debug, don't restart systemui after enabling the option. else you'll have to disabe and enable again.

**Comment by bzz11g** [comment]
yes it works on  6.0.0 Dev (#455), but disappear after SystemUI restart
but after reboot all is fine
