### ISSUE TITLE
[FEATURE] Two-Tone Accent QS Style

### ISSUE THREAD

**Issue by Abdelrahman-Muhammad** [Mahmud0808/Iconify#80]
### Describe the feature

**Can you please add Two-Tone Accent QS Style it available in many ROMs like RiceDroid,Banana,Nusantara**

### Why would it be useful to add?

it really looks good 

### Example(s)

![image](https://user-images.githubusercontent.com/97410751/219687225-940cdd13-bff0-4224-817b-6ca2dffd5aee.png)
![image](https://user-images.githubusercontent.com/97410751/219687290-a432df1f-fc50-4845-a0b8-75086c8ac0f9.png)

### Additional context

Anyway , Thank you for your efforts your app is really brilliant

**Comment by Mahmud0808** [comment]
It's just the same semi-transparent style Iconify already has but with semi-transparent accent. Or am I wrong?

**Comment by Abdelrahman-Muhammad** [comment]
Yes they almost the same but there are slight differences 
1- with **two-tone** when a tile is active, it will also be transparent, 
but with **semi-transparent** tile, when active, it has no transparency at all.

2-with **two-tone** the icon and label turn to accent color when active and white color when inactive,
with  **semi-transparent** tile the icon and label turn to black color when active and white color when in .active

3 - with **two-tone** brightness bar is colored with accent and transparent,
with **semi-transparent**  brightness bar is colored with accent only.

Semi-Transparent:
![image](https://user-images.githubusercontent.com/97410751/219851987-b5194b10-c58f-4d7a-92fc-a14a12a2ed18.png)

Two-Tone : 
![image](https://user-images.githubusercontent.com/97410751/219851627-db223567-2097-49d0-a455-28b13eb0f342.png)
 
It's already implemented in some custom ROMs like RiceDroid, Banana, and Nusantara I don't know If its easy to import this style from them .  
Have a good day ❤️

**Comment by Mahmud0808** [comment]
Provide me the commit link of this style from one of the roms you mentioned. This will be more helpful for me to figure out if it can be done easily or not.

**Comment by Abdelrahman-Muhammad** [comment]
This a link for a search for all commits on github that related to two-tone QS style because I don't know which one can help you 

https://github.com/search?q=two-tone+qs+style&type=Commits

**Comment by Mahmud0808** [comment]
> This a link for a search for all commits on github that related to two-tone QS style because I don't know which one can help you
> 
> https://github.com/search?q=two-tone+qs+style&type=Commits

Thank you. But looks like it can't be done without xposed. I am trying to avoid adding new xposed features as they might not work on different roms and I don't want to limit Iconify to one specific rom either.

**Comment by Abdelrahman-Muhammad** [comment]
I get you, I sincerely appreciate your flexibility and willingness to help. ❤️
