### ISSUE TITLE
[BUG]  Tint on Lockscreen if Transparent QS Panel is enabled

### ISSUE THREAD

**Issue by Shabinder** [Mahmud0808/Iconify#81]
### Describe the feature

Removal of useless tint from lockscreen/

### Why would it be useful to add?

Aesthetically Pleasing + Actual Amoled Benefit.

### Example(s)

![image](https://user-images.githubusercontent.com/44765050/219905458-8e1268cb-8b20-417b-8092-7301afceb899.png)
![image](https://user-images.githubusercontent.com/44765050/219905463-9814c399-c8a4-4f9d-8a2e-25d82108aaff.png)

tint is clearly visible in above black wallpaper.

**Comment by Mahmud0808** [comment]
This feature is already available in AOSPMods. Please try that.

**Comment by Shabinder** [comment]
On further diagnosis,
would like this to be as a bug report because this is actually not intended behaviour.

Clarifying on above.
 - There is no tint to begin with in stock rom.
 - After turning on Transparent Notification Panel, the tint appears on lockscreen.
 
 https://user-images.githubusercontent.com/44765050/221035114-25db2bcd-802e-4843-a413-dd35908a09d4.mp4

 
After some experimentation and workarounds I am able to remove lockscreen tint while keeping QS panel transparency by running below Xposed Hooks in a module while Iconfiy is also active with transparent panel and no tint on lockscreen.
 
https://gist.github.com/Shabinder/2177cfecbccef44408b36b665cec72b8

Pls look into this, I am sure u can implement this in a more cleaner way and maybe could implement same into iconify in some way.

**Comment by Mahmud0808** [comment]
Lemme know if it solved your issue. As I can't reproduce this issue on my device, I couldn't test it.

**Comment by Shabinder** [comment]
didnt worked for some reason.

Have issues in debugging, since a re-install and reboot doesnt show the new changes I make in debug apk.

Need to do below:
- uninstall
- reboot
- install
- overlay build + xposed module activation.
- reboot

and repeat to see effect of every change which is quite annoying, any idea why whole above charade is needed before seeing changes effect.

**Comment by Mahmud0808** [comment]
Xposed features shouldn't need reboot to see the changes. But yeah it checks for version code on every launch, so a mismatched version code will trigger building of overlays.
