### ISSUE TITLE
[FEATURE] Circle Battery Icon?

### ISSUE THREAD

**Issue by devycarol** [Mahmud0808/Iconify#82]
### Describe the feature

Old CyanogenMod used to have an option for a circular battery icon, with the meter being how much of the circle surrounded the number. The circle would spin around when charging.

LineageOS recently re-implemented the option, without the spinning and it turns red-orange when low.

### Why would it be useful to add?

CM11-era Holo nostalgists would probably find the option appreciable, with or without the spinning. It'd also be cool to be able to config the color of the 'full' potion of the circle and the color/presence of the 'empty' portion.

It's also nice and compact, placing the percentage number within the icon itself and the charging indicator being whether or not it's spinning. This saves a handful of pixels in the statusbar for those who reeally like to have a minimal amount of visuals.

### Example(s)

Here it is, still:
![PXL_20230219_203155856](https://user-images.githubusercontent.com/69347329/219973662-45782638-df41-44f7-9eb1-461c12cfde35.jpg)

Here it is, mid-spin:
![PXL_20230219_203143670](https://user-images.githubusercontent.com/69347329/219973689-f698b351-a13f-4014-a498-cb252f7629ce.jpg)

### Additional context

The spinning was reasonably slow, taking about eight seconds to complete a rotation.

**Comment by Mahmud0808** [comment]
If I am not wrong, AOSPMods already has circle battery. You can try that.

**Comment by harphere** [comment]
I respect you closed this but if I may offer input: PixelXpert (AOSPMods) does have circle battery icons but they are flaky when used with Custom ROM. I understand it only supports stock Pixel but it would be nice to have the option in Iconify for circle batteries. By flaky, I mean for example when a circle battery is set in PixelXpert, and the display is switched from portrait to landscape, the circle battery reverts to the default battery icon as noted [here](https://github.com/siavash79/PixelXpert/issues/329#issuecomment-1230946331). It would be great if you could reconsider this.

**Comment by harphere** [comment]
Thanks again for implementing this. Much appreciated.
