### ISSUE TITLE
[BUG] QS 'Hide Label' Setting Also Disables Other Text Such as the Status Bar Clock

### ISSUE THREAD

**Issue by devycarol** [Mahmud0808/Iconify#83]
### Describe the bug

The 'Hide Label' setting for the quick settings seems to also disable the display for the text contents of the status bar. I believe that the notification shade status bar and the system status bar are somewhat distinct objects.

### Steps to reproduce

1. QS Panel Tiles > Icon and Label
2. Toggle 'Hide Label'
3. Pull down the notification shade
4. Status bar icons and text are likely hidden

### Expected behavior

I would expect this setting to only affect the text within the QS tiles, not the entire pulldown interface. A simple scope issue would be my guess.

### Screenshots

Labels on:
![Screenshot_20230219-135600](https://user-images.githubusercontent.com/69347329/219974716-fafc5502-25f5-45ec-8036-6e7aea6015f8.png)

Labels off:
![Screenshot_20230219-135624](https://user-images.githubusercontent.com/69347329/219974725-fc808732-d521-477e-b502-b44eb6db1798.png)

### Device information

- Device: Google Pixel 5a
- OS: CalyxOS 4.5.1-UNOFFICIAL (Self-built, based on AOSP 13)
- App version: 6.0.0 Dev (#484)

### Additional context

I have the pure black theme toggles enabled both in CalyxOS settings as well as Iconify, but I doubt that has to do with the issue.

**Comment by devycarol** [comment]
Oh, and it's worth noting that the same problem applies to the 'text size' setting within the same submenu.

**Comment by Mahmud0808** [comment]
> Oh, and it's worth noting that the same problem applies to the 'text size' setting within the same submenu.

Some custom rom devs (probably) are implementing their own custom clocks where they are using the same resource which is used for QS text size. So changing one also changes the other. Pretty bad thing to implement ik. Anyway you can use the hide label option from XPosed Menu as a workaround.
