### ISSUE TITLE
[FEATURE] Ability to move notifications down with no LS clock

### ISSUE THREAD

**Issue by benarla** [Mahmud0808/Iconify#85]
### Describe the feature

It would be useful to allow the user to move the notifications down on LS when none is chosed in LS clock settings

### Why would it be useful to add?

To allow us to use lockscreen widgets to replace the clock

### Example(s)

Move notifications just like on other clocks

**Comment by Mahmud0808** [comment]
Just out of curiosity, which lockscreen widgets do you use?

**Comment by benarla** [comment]
> Just out of curiosity, which lockscreen widgets do you use?

I'm using the app lockscreen widgets on play store
