### ISSUE TITLE
[BUG] Transparency QS (Xposed feature) is not working

### ISSUE THREAD

**Issue by akmsk1999** [Mahmud0808/Iconify#88]
### Describe the bug

Well the title says it all....it was working on previous stable release 6.0(i am on same rom,in both version)...but it Isn't now on 6.1.0

### Steps to reproduce

..

### Expected behavior

..

### Screenshots

![Screenshot_20230221-154946_Chrome](https://user-images.githubusercontent.com/16622098/220309909-21b57fc0-f8b5-4b9c-bbc6-eb0f6ac372d6.png)
![Screenshot_20230221-154948_Chrome](https://user-images.githubusercontent.com/16622098/220309917-f60195af-4735-410f-89ec-1800c95fb756.png)

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. v4.0-Beta]
Poco x3 pro
Crdroid 9.2
App-6.1.0

### Additional context

..

**Comment by Mahmud0808** [comment]
![IMG_20230221_155403](https://user-images.githubusercontent.com/29881338/220311060-5669d756-3102-45ec-8f64-511b67004802.jpg)

Did you follow this properly? Try doing this again.

**Comment by akmsk1999** [comment]
I followed it...but still the same....reinstalled-rebooted everything from start...still same sir...

**Comment by Mahmud0808** [comment]
Update to the latest debug build. If it fixes your problem, then kindly close the issue.

**Comment by akmsk1999** [comment]
Sir how to install debug builds...it downloaded a zip

**Comment by Mahmud0808** [comment]
> it downloaded a zip

Just extract the zip. You'll get the APK.

**Comment by akmsk1999** [comment]
Sorry for Being late....yes this debug build fixes the transparency issue....

Now Transparency is working again....

One thing though.....i had to reapply tranparency level(%) to make it work every time i reboot my phone..(same as 6.0
