### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by LostCat123** [Mahmud0808/Iconify#9]
![Screenshot_20221115-202608~2](https://user-images.githubusercontent.com/91554842/201920889-1f735f24-cb4f-4f24-b840-e3a06f453a3c.png)
![Screenshot_20221115-202613~2](https://user-images.githubusercontent.com/91554842/201920896-0d4c5f0f-13d7-4049-b1f6-6e737e666b1a.png)

Be able to add an header image in this part of the qs panel, 

I like your work very much 👍

**Comment by Mahmud0808** [comment]
SystemUI Patcher magisk module will be needed for that. And the module will have to be created by the users themselves.
