### ISSUE TITLE
[FEATURE] Missing settings notifications icon

### ISSUE THREAD

**Issue by rabinjk** [Mahmud0808/Iconify#92]
### Describe the feature

ic_notifications.xml
![Screenshot_20230228-025130_MT_Manager](https://user-images.githubusercontent.com/126519955/221685915-2d4da1d4-05a7-45ea-a1f8-72594af79109.png)

### Why would it be useful to add?

Missing icon

### Example(s)

![Screenshot_20230228-025019_Settings](https://user-images.githubusercontent.com/126519955/221685478-11406662-016b-40e2-a34f-be4f49bad951.png)

**Comment by Mahmud0808** [comment]
Already available

https://github.com/Mahmud0808/Iconify/blob/beta/app/src/main/assets/Overlays/com.android.settings/SIP1/res/drawable-anydpi/ic_notifications.xml
