### ISSUE TITLE
[FEATURE] Be able to use you own finger print icon on lockscreen

### ISSUE THREAD

**Issue by eddro22** [Mahmud0808/Iconify#93]
### Describe the feature

Be able to use you own finger print icon on lockscreen.

### Why would it be useful to add?

Better customization on lockscreen.

### Example(s)

![Screenshot_20230227-191810_Telegram](https://user-images.githubusercontent.com/98064723/221719300-3330333e-9b1f-4938-8008-ffab666b7aba.png)

**Comment by Mahmud0808** [comment]
I don't have a device with UDFPS, hence I can't make and test it.
