### ISSUE TITLE
[FEATURE] Manual color change in monet engine

### ISSUE THREAD

**Issue by vxtk** [Mahmud0808/Iconify#94]
### Describe the feature

Allow for colors generated using monet engine to be manually edited

### Why would it be useful to add?

Sometimes colors generated by the monet engine look out of place, especialy when using pure dark mode, for example version number is screenshot below would look better if text was darker than the background:
![1](https://user-images.githubusercontent.com/99820286/222111273-c40ca4e4-4feb-43ce-8ae5-8d2111cd5873.png)

### Example(s)

Clicking on a color in this pallete shoud open color picker:
![2](https://user-images.githubusercontent.com/99820286/222111389-d27eee18-f316-40b0-8f60-f744d340cdf8.png)

**Comment by Mahmud0808** [comment]
That's not impossible to do but I don't think that's a good idea as it might create visibility issue here and there. Also the background of version number is dark accent colored, so a dark text will create visibility issue ig.

**Comment by VitoFe** [comment]
If you could make the number of steps configurable, this feature would greatly improve customization. I don't know how many steps can or have to be setup for the monet engine, but maybe if the steps where like 5-6, manual configuration of the single colors in each step would make more sense.
